"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TargetContractMock__factory = exports.AdapterMock__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var AdapterMock__factory_1 = require("./AdapterMock__factory");
Object.defineProperty(exports, "AdapterMock__factory", { enumerable: true, get: function () { return AdapterMock__factory_1.AdapterMock__factory; } });
var TargetContractMock__factory_1 = require("./TargetContractMock__factory");
Object.defineProperty(exports, "TargetContractMock__factory", { enumerable: true, get: function () { return TargetContractMock__factory_1.TargetContractMock__factory; } });
