import type { AbiParameter } from "viem";

export type VersionedAbi = Record<number, readonly AbiParameter[]>;

export type AdapterContractTypeLegacy =
  | "AD_AAVE_V3_LENDING_POOL"
  | "AD_BALANCER_VAULT"
  | "AD_CAMELOT_V3_ROUTER"
  | "AD_CONVEX_L2_BOOSTER"
  | "AD_CONVEX_L2_REWARD_POOL"
  | "AD_CONVEX_V1_BASE_REWARD_POOL"
  | "AD_CONVEX_V1_BOOSTER"
  | "AD_CURVE_STABLE_NG"
  | "AD_CURVE_V1_2ASSETS"
  | "AD_CURVE_V1_3ASSETS"
  | "AD_CURVE_V1_4ASSETS"
  | "AD_CURVE_V1_EXCHANGE_ONLY"
  | "AD_CURVE_V1_STECRV_POOL"
  | "AD_CURVE_V1_WRAPPER"
  | "AD_DAI_USDS_EXCHANGE"
  | "AD_EQUALIZER_ROUTER"
  | "AD_ERC4626_VAULT"
  | "AD_LIDO_V1"
  | "AD_LIDO_WSTETH_V1"
  | "AD_MELLOW_ERC4626_VAULT"
  | "AD_MELLOW_LRT_VAULT"
  | "AD_PENDLE_ROUTER"
  | "AD_STAKING_REWARDS"
  | "AD_SYMBIOTIC_DEFAULT_COLLATERAL"
  | "AD_UNISWAP_V2_ROUTER"
  | "AD_UNISWAP_V3_ROUTER"
  | "AD_VELODROME_V2_ROUTER"
  | "AD_YEARN_V2"
  | "AD_ZIRCUIT_POOL";

export type AdapterContractType =
  | "ADAPTER::BALANCER_V3_ROUTER"
  | "ADAPTER::BALANCER_VAULT"
  | "ADAPTER::CAMELOT_V3_ROUTER"
  | "ADAPTER::CURVE_STABLE_NG"
  | "ADAPTER::CURVE_V1_2ASSETS"
  | "ADAPTER::CURVE_V1_3ASSETS"
  | "ADAPTER::CURVE_V1_4ASSETS"
  | "ADAPTER::CURVE_V1_STECRV_POOL"
  | "ADAPTER::CURVE_V1_WRAPPER"
  | "ADAPTER::CVX_V1_BASE_REWARD_POOL"
  | "ADAPTER::CVX_V1_BOOSTER"
  | "ADAPTER::DAI_USDS_EXCHANGE"
  | "ADAPTER::EQUALIZER_ROUTER"
  | "ADAPTER::ERC4626_VAULT"
  | "ADAPTER::ERC4626_VAULT_REFERRAL"
  | "ADAPTER::FLUID_DEX"
  | "ADAPTER::INFRARED_VAULT"
  | "ADAPTER::KODIAK_ISLAND_GATEWAY"
  | "ADAPTER::LIDO_V1"
  | "ADAPTER::LIDO_WSTETH_V1"
  | "ADAPTER::MELLOW_CLAIMER"
  | "ADAPTER::MELLOW_DVV"
  | "ADAPTER::MELLOW_ERC4626_VAULT"
  | "ADAPTER::MELLOW_LRT_VAULT"
  | "ADAPTER::MELLOW_WRAPPER"
  | "ADAPTER::PENDLE_ROUTER"
  | "ADAPTER::STAKING_REWARDS"
  | "ADAPTER::TRADERJOE_ROUTER"
  | "ADAPTER::UNISWAP_V2_ROUTER"
  | "ADAPTER::UNISWAP_V3_ROUTER"
  | "ADAPTER::UPSHIFT_VAULT"
  | "ADAPTER::VELODROME_V2_ROUTER"
  | "ADAPTER::YEARN_V2";

export enum AdapterType {
  BALANCER_V3_ROUTER = "BALANCER_V3_ROUTER",
  BALANCER_VAULT = "BALANCER_VAULT",
  CAMELOT_V3_ROUTER = "CAMELOT_V3_ROUTER",
  CURVE_STABLE_NG = "CURVE_STABLE_NG",
  CURVE_V1_2ASSETS = "CURVE_V1_2ASSETS",
  CURVE_V1_3ASSETS = "CURVE_V1_3ASSETS",
  CURVE_V1_4ASSETS = "CURVE_V1_4ASSETS",
  CURVE_V1_STECRV_POOL = "CURVE_V1_STECRV_POOL",
  CURVE_V1_WRAPPER = "CURVE_V1_WRAPPER",
  CVX_V1_BASE_REWARD_POOL = "CVX_V1_BASE_REWARD_POOL",
  CVX_V1_BOOSTER = "CVX_V1_BOOSTER",
  DAI_USDS_EXCHANGE = "DAI_USDS_EXCHANGE",
  EQUALIZER_ROUTER = "EQUALIZER_ROUTER",
  ERC4626_VAULT = "ERC4626_VAULT",
  ERC4626_VAULT_REFERRAL = "ERC4626_VAULT_REFERRAL",
  FLUID_DEX = "FLUID_DEX",
  INFRARED_VAULT = "INFRARED_VAULT",
  KODIAK_ISLAND_GATEWAY = "KODIAK_ISLAND_GATEWAY",
  LIDO_V1 = "LIDO_V1",
  LIDO_WSTETH_V1 = "LIDO_WSTETH_V1",
  MELLOW_CLAIMER = "MELLOW_CLAIMER",
  MELLOW_DVV = "MELLOW_DVV",
  MELLOW_ERC4626_VAULT = "MELLOW_ERC4626_VAULT",
  MELLOW_LRT_VAULT = "MELLOW_LRT_VAULT",
  MELLOW_WRAPPER = "MELLOW_WRAPPER",
  PENDLE_ROUTER = "PENDLE_ROUTER",
  STAKING_REWARDS = "STAKING_REWARDS",
  TRADERJOE_ROUTER = "TRADERJOE_ROUTER",
  UNISWAP_V2_ROUTER = "UNISWAP_V2_ROUTER",
  UNISWAP_V3_ROUTER = "UNISWAP_V3_ROUTER",
  UPSHIFT_VAULT = "UPSHIFT_VAULT",
  VELODROME_V2_ROUTER = "VELODROME_V2_ROUTER",
  YEARN_V2 = "YEARN_V2",
}
