export const iPartialLiquidationBotV310Abi = [
  {
    type: "function",
    name: "contractType",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "feeScaleFactor",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxHealthFactor",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "minHealthFactor",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "partiallyLiquidate",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "address" },
      { name: "repaidAmount", type: "uint256", internalType: "uint256" },
      { name: "minSeizedAmount", type: "uint256", internalType: "uint256" },
      { name: "to", type: "address", internalType: "address" },
      {
        name: "priceUpdates",
        type: "tuple[]",
        internalType: "struct PriceUpdate[]",
        components: [
          { name: "priceFeed", type: "address", internalType: "address" },
          { name: "data", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    outputs: [
      { name: "seizedAmount", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "premiumScaleFactor",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "requiredPermissions",
    inputs: [],
    outputs: [{ name: "", type: "uint192", internalType: "uint192" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "serialize",
    inputs: [],
    outputs: [{ name: "serializedData", type: "bytes", internalType: "bytes" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "treasury",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "version",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "PartiallyLiquidate",
    inputs: [
      {
        name: "creditManager",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "creditAccount",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "liquidator",
        type: "address",
        indexed: false,
        internalType: "address",
      },
      {
        name: "repaidDebt",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "seizedCollateral",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      { name: "fee", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  { type: "error", name: "LiquidatedLessThanNeededException", inputs: [] },
  { type: "error", name: "LiquidatedMoreThanNeededException", inputs: [] },
  { type: "error", name: "SeizedLessThanRequiredException", inputs: [] },
  { type: "error", name: "UnderlyingNotLiquidatableException", inputs: [] },
] as const;
