"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.ITokenFactory__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        name: "CreateDepositToken",
        outputs: [
            {
                internalType: "address",
                name: "",
                type: "address",
            },
        ],
        stateMutability: "nonpayable",
        type: "function",
    },
];
var ITokenFactory__factory = /** @class */ (function () {
    function ITokenFactory__factory() {
    }
    ITokenFactory__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    ITokenFactory__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    ITokenFactory__factory.abi = _abi;
    return ITokenFactory__factory;
}());
exports.ITokenFactory__factory = ITokenFactory__factory;
