export const NO_VERSION = 0;

export const AP_ACCOUNT_FACTORY = "ACCOUNT_FACTORY";
export const AP_ACL = "ACL";
export const AP_BOT_LIST = "BOT_LIST";
export const AP_BYTECODE_REPOSITORY = "BYTECODE_REPOSITORY";
export const AP_CONTRACTS_REGISTER = "CONTRACTS_REGISTER";
export const AP_CONTROLLER_TIMELOCK = "CONTROLLER_TIMELOCK";
export const AP_CREDIT_ACCOUNT_COMPRESSOR = "GLOBAL::ACCOUNT_COMPRESSOR";
export const AP_CREDIT_SUITE_COMPRESSOR = "GLOBAL::CREDIT_SUITE_COMPRESSOR";
export const AP_DATA_COMPRESSOR = "DATA_COMPRESSOR";
export const AP_DELEVERAGE_BOT_HV = "DELEVERAGE_BOT_HV";
export const AP_DELEVERAGE_BOT_LV = "DELEVERAGE_BOT_LV";
export const AP_DELEVERAGE_BOT_PEGGED = "DELEVERAGE_BOT_PEGGED";
export const AP_GAUGE_COMPRESSOR = "GLOBAL::GAUGE_COMPRESSOR";
export const AP_GEAR_STAKING = "GEAR_STAKING";
export const AP_GEAR_TOKEN = "GLOBAL::GEAR_TOKEN";
export const AP_INFLATION_ATTACK_BLOCKER = "INFLATION_ATTACK_BLOCKER";
export const AP_INSOLVENCY_CHECKER = "INSOLVENCY_CHECKER";
export const AP_MARKET_COMPRESSOR = "GLOBAL::MARKET_COMPRESSOR";
export const AP_MARKET_CONFIGURATOR = "MARKET_CONFIGURATOR";
export const AP_PARTIAL_LIQUIDATION_BOT = "PARTIAL_LIQUIDATION_BOT";
export const AP_PERIPHERY_COMPRESSOR = "GLOBAL::PERIPHERY_COMPRESSOR";
export const AP_PRICE_FEED_COMPRESSOR = "GLOBAL::PRICE_FEED_COMPRESSOR";
export const AP_PRICE_FEED_STORE = "PRICE_FEED_STORE";
export const AP_PRICE_ORACLE = "PRICE_ORACLE";
export const AP_REWARDS_COMPRESSOR = "GLOBAL::REWARDS_COMPRESSOR";
export const AP_ROUTER = "GLOBAL::ROUTER";
export const AP_TOKEN_COMPRESSOR = "GLOBAL::TOKEN_COMPRESSOR";
export const AP_TREASURY = "TREASURY";
export const AP_WETH_GATEWAY = "WETH_GATEWAY";
export const AP_WETH_TOKEN = "WETH_TOKEN";
export const AP_ZAPPER_REGISTER = "ZAPPER_REGISTER";
export const AP_ZERO_PRICE_FEED = "ZERO_PRICE_FEED";

/**
 * Default address provider address for v3.1.0
 * Is determenistic and does not depend on the network type
 */
export const ADDRESS_PROVIDER_V310 =
  "0xF7f0a609BfAb9a0A98786951ef10e5FE26cC1E38";
