export const PHANTOM_TOKEN_CONTRACT_TYPES = [
  "PHANTOM_TOKEN::CONVEX",
  "PHANTOM_TOKEN::INFINIFI_UNWIND",
  "PHANTOM_TOKEN::INFRARED",
  "PHANTOM_TOKEN::MELLOW_WITHDRAWAL",
  "PHANTOM_TOKEN::MIDAS_REDEMPTION",
  "PHANTOM_TOKEN::STAKING_REWARDS",
  "PHANTOM_TOKEN::UPSHIFT_WITHDRAW",
] as const;

export type PhantomTokenContractType =
  (typeof PHANTOM_TOKEN_CONTRACT_TYPES)[number];
