"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Errors__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Errors__factory_1 = require("./Errors__factory");
Object.defineProperty(exports, "Errors__factory", { enumerable: true, get: function () { return Errors__factory_1.Errors__factory; } });
