export const iRedstonePriceFeedExceptionsAbi = [
  { type: "error", inputs: [], name: "DataPackageTimestampIncorrect" },
  { type: "error", inputs: [], name: "DuplicateSignersException" },
  { type: "error", inputs: [], name: "IncorrectSignersThresholdException" },
  { type: "error", inputs: [], name: "NotEnoughSignersException" },
  { type: "error", inputs: [], name: "RedstonePayloadTimestampIncorrect" },
] as const;

export const ilpPriceFeedExceptionsAbi = [
  { type: "error", inputs: [], name: "ExchangeRateOutOfBoundsException" },
  { type: "error", inputs: [], name: "LowerBoundCantBeZeroException" },
  { type: "error", inputs: [], name: "ReserveFeedMustNotBeSelfException" },
  { type: "error", inputs: [], name: "UpdateBoundsBeforeCooldownException" },
  { type: "error", inputs: [], name: "UpdateBoundsNotAllowedException" },
] as const;

export const iRouterErrorsV300Abi = [
  {
    type: "error",
    inputs: [
      { name: "tokenIn", internalType: "address", type: "address" },
      { name: "tokenOut", internalType: "address", type: "address" },
    ],
    name: "PathNotFoundException",
  },
  {
    type: "error",
    inputs: [
      { name: "ttIn", internalType: "uint8", type: "uint8" },
      { name: "tokenOut", internalType: "address", type: "address" },
    ],
    name: "PathNotFoundExceptionTyped",
  },
  {
    type: "error",
    inputs: [{ name: "tokenOut", internalType: "address", type: "address" }],
    name: "PathToTargetNotFound",
  },
  { type: "error", inputs: [], name: "UnsupportedAdapterType" },
  {
    type: "error",
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "UnsupportedRouterComponent",
  },
] as const;

export const iRouterErrorsV310Abi = [
  {
    type: "error",
    name: "PathNotFoundException",
    inputs: [
      { name: "tokenIn", type: "address", internalType: "address" },
      { name: "tokenOut", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "PathNotFoundExceptionTyped",
    inputs: [
      { name: "ttIn", type: "uint8", internalType: "uint8" },
      { name: "tokenOut", type: "address", internalType: "address" },
    ],
  },
  {
    type: "error",
    name: "PathToTargetNotFound",
    inputs: [{ name: "tokenOut", type: "address", internalType: "address" }],
  },
  { type: "error", name: "UnsupportedAdapterType", inputs: [] },
  {
    type: "error",
    name: "UnsupportedRouterComponent",
    inputs: [{ name: "", type: "address", internalType: "address" }],
  },
] as const;

export const iExceptionsV300Abi = [
  { type: "error", inputs: [], name: "ActiveCreditAccountNotSetException" },
  { type: "error", inputs: [], name: "ActiveCreditAccountOverridenException" },
  { type: "error", inputs: [], name: "AdapterIsNotRegisteredException" },
  {
    type: "error",
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "AddressIsNotContractException",
  },
  { type: "error", inputs: [], name: "AddressNotFoundException" },
  { type: "error", inputs: [], name: "AllowanceFailedException" },
  { type: "error", inputs: [], name: "AmountCantBeZeroException" },
  { type: "error", inputs: [], name: "BalanceLessThanExpectedException" },
  { type: "error", inputs: [], name: "BorrowAmountOutOfLimitsException" },
  { type: "error", inputs: [], name: "BorrowedBlockLimitException" },
  { type: "error", inputs: [], name: "BorrowingMoreThanU2ForbiddenException" },
  { type: "error", inputs: [], name: "CallerNotAccountFactoryException" },
  { type: "error", inputs: [], name: "CallerNotAdapterException" },
  { type: "error", inputs: [], name: "CallerNotConfiguratorException" },
  { type: "error", inputs: [], name: "CallerNotControllerException" },
  { type: "error", inputs: [], name: "CallerNotCreditAccountOwnerException" },
  { type: "error", inputs: [], name: "CallerNotCreditFacadeException" },
  { type: "error", inputs: [], name: "CallerNotCreditManagerException" },
  { type: "error", inputs: [], name: "CallerNotExecutorException" },
  { type: "error", inputs: [], name: "CallerNotGaugeException" },
  { type: "error", inputs: [], name: "CallerNotMigratorException" },
  { type: "error", inputs: [], name: "CallerNotPausableAdminException" },
  { type: "error", inputs: [], name: "CallerNotPoolQuotaKeeperException" },
  { type: "error", inputs: [], name: "CallerNotUnpausableAdminException" },
  { type: "error", inputs: [], name: "CallerNotVetoAdminException" },
  { type: "error", inputs: [], name: "CallerNotVoterException" },
  { type: "error", inputs: [], name: "CloseAccountWithEnabledTokensException" },
  { type: "error", inputs: [], name: "CloseAccountWithNonZeroDebtException" },
  { type: "error", inputs: [], name: "CreditAccountDoesNotExistException" },
  { type: "error", inputs: [], name: "CreditAccountIsInUseException" },
  { type: "error", inputs: [], name: "CreditAccountNotLiquidatableException" },
  { type: "error", inputs: [], name: "CreditManagerCantBorrowException" },
  { type: "error", inputs: [], name: "CustomHealthFactorTooLowException" },
  { type: "error", inputs: [], name: "DebtToZeroWithActiveQuotasException" },
  { type: "error", inputs: [], name: "DebtUpdatedTwiceInOneBlockException" },
  { type: "error", inputs: [], name: "ExpectedBalancesAlreadySetException" },
  { type: "error", inputs: [], name: "ExpectedBalancesNotSetException" },
  { type: "error", inputs: [], name: "ForbiddenInWhitelistedModeException" },
  {
    type: "error",
    inputs: [],
    name: "ForbiddenTokenBalanceIncreasedException",
  },
  { type: "error", inputs: [], name: "ForbiddenTokenEnabledException" },
  { type: "error", inputs: [], name: "ForbiddenTokensException" },
  { type: "error", inputs: [], name: "IncompatibleContractException" },
  { type: "error", inputs: [], name: "IncompatibleCreditManagerException" },
  { type: "error", inputs: [], name: "IncompatiblePoolQuotaKeeperException" },
  { type: "error", inputs: [], name: "IncompatibleSuccessorException" },
  { type: "error", inputs: [], name: "IncorrectExpirationDateException" },
  { type: "error", inputs: [], name: "IncorrectLimitsException" },
  { type: "error", inputs: [], name: "IncorrectLiquidationThresholdException" },
  { type: "error", inputs: [], name: "IncorrectParameterException" },
  { type: "error", inputs: [], name: "IncorrectPriceException" },
  { type: "error", inputs: [], name: "IncorrectPriceFeedException" },
  { type: "error", inputs: [], name: "IncorrectTokenContractException" },
  { type: "error", inputs: [], name: "InsufficientBalanceException" },
  { type: "error", inputs: [], name: "InsufficientRemainingFundsException" },
  { type: "error", inputs: [], name: "InsufficientVotesException" },
  { type: "error", inputs: [], name: "InvalidBotException" },
  { type: "error", inputs: [], name: "InvalidCollateralHintException" },
  {
    type: "error",
    inputs: [],
    name: "MasterCreditAccountAlreadyDeployedException",
  },
  {
    type: "error",
    inputs: [{ name: "permission", internalType: "uint256", type: "uint256" }],
    name: "NoPermissionException",
  },
  { type: "error", inputs: [], name: "NotAllowedAfterExpirationException" },
  { type: "error", inputs: [], name: "NotAllowedWhenNotExpirableException" },
  { type: "error", inputs: [], name: "NotApprovedBotException" },
  { type: "error", inputs: [], name: "NotEnoughCollateralException" },
  { type: "error", inputs: [], name: "NotImplementedException" },
  { type: "error", inputs: [], name: "ParameterChangedAfterQueuedTxException" },
  { type: "error", inputs: [], name: "ParameterChecksFailedException" },
  { type: "error", inputs: [], name: "PriceFeedDoesNotExistException" },
  { type: "error", inputs: [], name: "QuotaIsOutOfBoundsException" },
  { type: "error", inputs: [], name: "ReceiveIsNotAllowedException" },
  { type: "error", inputs: [], name: "RegisteredCreditManagerOnlyException" },
  { type: "error", inputs: [], name: "RegisteredPoolOnlyException" },
  {
    type: "error",
    inputs: [],
    name: "RemainingTokenBalanceIncreasedException",
  },
  { type: "error", inputs: [], name: "StalePriceException" },
  { type: "error", inputs: [], name: "TargetContractNotAllowedException" },
  { type: "error", inputs: [], name: "TokenAlreadyAddedException" },
  { type: "error", inputs: [], name: "TokenIsNotQuotedException" },
  { type: "error", inputs: [], name: "TokenNotAllowedException" },
  { type: "error", inputs: [], name: "TooManyEnabledTokensException" },
  { type: "error", inputs: [], name: "TooManyTokensException" },
  { type: "error", inputs: [], name: "TxExecutedOutsideTimeWindowException" },
  { type: "error", inputs: [], name: "TxExecutionRevertedException" },
  { type: "error", inputs: [], name: "TxNotQueuedException" },
  { type: "error", inputs: [], name: "UnexpectedPermissionsException" },
  { type: "error", inputs: [], name: "UnknownMethodException" },
  { type: "error", inputs: [], name: "UpdateQuotaOnZeroDebtAccountException" },
  { type: "error", inputs: [], name: "ValueOutOfRangeException" },
  { type: "error", inputs: [], name: "VotingContractNotAllowedException" },
  { type: "error", inputs: [], name: "ZeroAddressException" },
] as const;

export const iRedstoneErrorsAbi = [
  { type: "error", inputs: [], name: "CalldataMustHaveValidPayload" },
  { type: "error", inputs: [], name: "CalldataOverOrUnderFlow" },
  { type: "error", inputs: [], name: "EachSignerMustProvideTheSameValue" },
  { type: "error", inputs: [], name: "EmptyCalldataPointersArr" },
  { type: "error", inputs: [], name: "IncorrectUnsignedMetadataSize" },
  {
    type: "error",
    inputs: [
      {
        name: "receivedSignersCount",
        internalType: "uint256",
        type: "uint256",
      },
      {
        name: "requiredSignersCount",
        internalType: "uint256",
        type: "uint256",
      },
    ],
    name: "InsufficientNumberOfUniqueSigners",
  },
  { type: "error", inputs: [], name: "InvalidCalldataPointer" },
  {
    type: "error",
    inputs: [
      { name: "receivedSigner", internalType: "address", type: "address" },
    ],
    name: "SignerNotAuthorised",
  },
] as const;

export const iExceptionsV310Abi = [
  { type: "error", name: "ActiveCreditAccountNotSetException", inputs: [] },
  { type: "error", name: "ActiveCreditAccountOverridenException", inputs: [] },
  { type: "error", name: "AdapterIsNotRegisteredException", inputs: [] },
  {
    type: "error",
    name: "AddressIsNotContractException",
    inputs: [{ name: "", type: "address", internalType: "address" }],
  },
  { type: "error", name: "AddressNotFoundException", inputs: [] },
  { type: "error", name: "AllowanceFailedException", inputs: [] },
  { type: "error", name: "AmountCantBeZeroException", inputs: [] },
  {
    type: "error",
    name: "BalanceLessThanExpectedException",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  { type: "error", name: "BorrowAmountOutOfLimitsException", inputs: [] },
  { type: "error", name: "BorrowedBlockLimitException", inputs: [] },
  { type: "error", name: "BorrowingMoreThanU2ForbiddenException", inputs: [] },
  { type: "error", name: "CallerNotAccountFactoryException", inputs: [] },
  { type: "error", name: "CallerNotAdapterException", inputs: [] },
  { type: "error", name: "CallerNotConfiguratorException", inputs: [] },
  { type: "error", name: "CallerNotCreditAccountOwnerException", inputs: [] },
  { type: "error", name: "CallerNotCreditFacadeException", inputs: [] },
  { type: "error", name: "CallerNotCreditManagerException", inputs: [] },
  { type: "error", name: "CallerNotExecutorException", inputs: [] },
  { type: "error", name: "CallerNotGaugeException", inputs: [] },
  { type: "error", name: "CallerNotMigratorException", inputs: [] },
  { type: "error", name: "CallerNotPausableAdminException", inputs: [] },
  { type: "error", name: "CallerNotPoolQuotaKeeperException", inputs: [] },
  { type: "error", name: "CallerNotUnpausableAdminException", inputs: [] },
  { type: "error", name: "CallerNotVetoAdminException", inputs: [] },
  { type: "error", name: "CallerNotVoterException", inputs: [] },
  { type: "error", name: "CloseAccountWithNonZeroDebtException", inputs: [] },
  { type: "error", name: "CreditAccountDoesNotExistException", inputs: [] },
  { type: "error", name: "CreditAccountIsInUseException", inputs: [] },
  { type: "error", name: "CreditAccountNotLiquidatableException", inputs: [] },
  {
    type: "error",
    name: "CreditAccountNotLiquidatableWithLossException",
    inputs: [],
  },
  { type: "error", name: "CreditManagerCantBorrowException", inputs: [] },
  { type: "error", name: "CustomHealthFactorTooLowException", inputs: [] },
  { type: "error", name: "DebtToZeroWithActiveQuotasException", inputs: [] },
  { type: "error", name: "DebtUpdatedTwiceInOneBlockException", inputs: [] },
  { type: "error", name: "ExpectedBalancesAlreadySetException", inputs: [] },
  { type: "error", name: "ExpectedBalancesNotSetException", inputs: [] },
  { type: "error", name: "ForbiddenInWhitelistedModeException", inputs: [] },
  {
    type: "error",
    name: "ForbiddenTokenBalanceIncreasedException",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ForbiddenTokenQuotaIncreasedException",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "ForbiddenTokensException",
    inputs: [
      { name: "forbiddenTokensMask", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "IncompatibleContractException", inputs: [] },
  { type: "error", name: "IncompatibleCreditManagerException", inputs: [] },
  { type: "error", name: "IncompatibleGaugeException", inputs: [] },
  { type: "error", name: "IncompatiblePoolQuotaKeeperException", inputs: [] },
  { type: "error", name: "IncompatibleSuccessorException", inputs: [] },
  {
    type: "error",
    name: "InconsistentExpiredLiquidationFeesException",
    inputs: [],
  },
  { type: "error", name: "InconsistentLiquidationFeesException", inputs: [] },
  { type: "error", name: "IncorrectAdaptersSetException", inputs: [] },
  { type: "error", name: "IncorrectBotPermissionsException", inputs: [] },
  { type: "error", name: "IncorrectExpirationDateException", inputs: [] },
  { type: "error", name: "IncorrectLimitsException", inputs: [] },
  { type: "error", name: "IncorrectLiquidationThresholdException", inputs: [] },
  { type: "error", name: "IncorrectParameterException", inputs: [] },
  { type: "error", name: "IncorrectPriceException", inputs: [] },
  { type: "error", name: "IncorrectPriceFeedException", inputs: [] },
  { type: "error", name: "IncorrectTokenContractException", inputs: [] },
  { type: "error", name: "InsufficientBalanceException", inputs: [] },
  { type: "error", name: "InsufficientRemainingFundsException", inputs: [] },
  { type: "error", name: "InsufficientVotesException", inputs: [] },
  { type: "error", name: "InvalidBotException", inputs: [] },
  {
    type: "error",
    name: "InvalidCollateralHintException",
    inputs: [{ name: "mask", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "MasterCreditAccountAlreadyDeployedException",
    inputs: [],
  },
  {
    type: "error",
    name: "NoPermissionException",
    inputs: [{ name: "permission", type: "uint256", internalType: "uint256" }],
  },
  { type: "error", name: "NotAllowedAfterExpirationException", inputs: [] },
  { type: "error", name: "NotAllowedWhenNotExpirableException", inputs: [] },
  {
    type: "error",
    name: "NotApprovedBotException",
    inputs: [{ name: "bot", type: "address", internalType: "address" }],
  },
  { type: "error", name: "NotEnoughCollateralException", inputs: [] },
  { type: "error", name: "NotImplementedException", inputs: [] },
  { type: "error", name: "PriceFeedDoesNotExistException", inputs: [] },
  { type: "error", name: "PriceFeedIsNotUpdatableException", inputs: [] },
  { type: "error", name: "QuotaIsOutOfBoundsException", inputs: [] },
  { type: "error", name: "RampDurationTooShortException", inputs: [] },
  { type: "error", name: "ReceiveIsNotAllowedException", inputs: [] },
  { type: "error", name: "RegisteredCreditManagerOnlyException", inputs: [] },
  { type: "error", name: "RegisteredPoolOnlyException", inputs: [] },
  {
    type: "error",
    name: "RemainingTokenBalanceIncreasedException",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
  },
  {
    type: "error",
    name: "SeizedLessThanRequiredException",
    inputs: [
      { name: "seizedAmount", type: "uint256", internalType: "uint256" },
    ],
  },
  { type: "error", name: "StalePriceException", inputs: [] },
  { type: "error", name: "TargetContractNotAllowedException", inputs: [] },
  { type: "error", name: "TokenAlreadyAddedException", inputs: [] },
  { type: "error", name: "TokenIsNotQuotedException", inputs: [] },
  { type: "error", name: "TokenNotAllowedException", inputs: [] },
  { type: "error", name: "TooManyActiveBotsException", inputs: [] },
  { type: "error", name: "TooManyEnabledTokensException", inputs: [] },
  { type: "error", name: "TooManyTokensException", inputs: [] },
  { type: "error", name: "UnderlyingIsNotLiquidatableException", inputs: [] },
  {
    type: "error",
    name: "UnexpectedPermissionsException",
    inputs: [{ name: "permissions", type: "uint256", internalType: "uint256" }],
  },
  {
    type: "error",
    name: "UnknownMethodException",
    inputs: [{ name: "selector", type: "bytes4", internalType: "bytes4" }],
  },
  { type: "error", name: "UpdateQuotaOnZeroDebtAccountException", inputs: [] },
  { type: "error", name: "ValueOutOfRangeException", inputs: [] },
  { type: "error", name: "VotingContractNotAllowedException", inputs: [] },
  { type: "error", name: "ZeroAddressException", inputs: [] },
] as const;

export const errorAbis = [
  ...iExceptionsV300Abi,
  ...iExceptionsV310Abi,
  ...iRedstonePriceFeedExceptionsAbi,
  ...iRedstoneErrorsAbi,
  ...ilpPriceFeedExceptionsAbi,
  ...iRouterErrorsV300Abi,
  ...iRouterErrorsV310Abi,
] as const;

export type errorAbis = typeof errorAbis;
