/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// DataCompressorV3
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const dataCompressorV3Abi = [
  {
    type: "constructor",
    inputs: [
      { name: "_addressProvider", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "contractsRegister",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "_creditAccount", internalType: "address", type: "address" },
      {
        name: "priceUpdates",
        internalType: "struct PriceOnDemand[]",
        type: "tuple[]",
        components: [
          { name: "token", internalType: "address", type: "address" },
          { name: "callData", internalType: "bytes", type: "bytes" },
        ],
      },
    ],
    name: "getCreditAccountData",
    outputs: [
      {
        name: "result",
        internalType: "struct CreditAccountData",
        type: "tuple",
        components: [
          { name: "isSuccessful", internalType: "bool", type: "bool" },
          {
            name: "priceFeedsNeeded",
            internalType: "address[]",
            type: "address[]",
          },
          { name: "addr", internalType: "address", type: "address" },
          { name: "borrower", internalType: "address", type: "address" },
          { name: "creditManager", internalType: "address", type: "address" },
          { name: "cmName", internalType: "string", type: "string" },
          { name: "creditFacade", internalType: "address", type: "address" },
          { name: "underlying", internalType: "address", type: "address" },
          { name: "debt", internalType: "uint256", type: "uint256" },
          {
            name: "cumulativeIndexLastUpdate",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "cumulativeQuotaInterest",
            internalType: "uint128",
            type: "uint128",
          },
          { name: "accruedInterest", internalType: "uint256", type: "uint256" },
          { name: "accruedFees", internalType: "uint256", type: "uint256" },
          { name: "totalDebtUSD", internalType: "uint256", type: "uint256" },
          { name: "totalValue", internalType: "uint256", type: "uint256" },
          { name: "totalValueUSD", internalType: "uint256", type: "uint256" },
          { name: "twvUSD", internalType: "uint256", type: "uint256" },
          {
            name: "enabledTokensMask",
            internalType: "uint256",
            type: "uint256",
          },
          { name: "healthFactor", internalType: "uint256", type: "uint256" },
          { name: "baseBorrowRate", internalType: "uint256", type: "uint256" },
          {
            name: "aggregatedBorrowRate",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "balances",
            internalType: "struct TokenBalance[]",
            type: "tuple[]",
            components: [
              { name: "token", internalType: "address", type: "address" },
              { name: "balance", internalType: "uint256", type: "uint256" },
              { name: "isForbidden", internalType: "bool", type: "bool" },
              { name: "isEnabled", internalType: "bool", type: "bool" },
              { name: "isQuoted", internalType: "bool", type: "bool" },
              { name: "quota", internalType: "uint256", type: "uint256" },
              { name: "quotaRate", internalType: "uint16", type: "uint16" },
              {
                name: "quotaCumulativeIndexLU",
                internalType: "uint256",
                type: "uint256",
              },
            ],
          },
          { name: "since", internalType: "uint64", type: "uint64" },
          { name: "cfVersion", internalType: "uint256", type: "uint256" },
          { name: "expirationDate", internalType: "uint40", type: "uint40" },
          { name: "activeBots", internalType: "address[]", type: "address[]" },
        ],
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "borrower", internalType: "address", type: "address" },
      {
        name: "priceUpdates",
        internalType: "struct PriceOnDemand[]",
        type: "tuple[]",
        components: [
          { name: "token", internalType: "address", type: "address" },
          { name: "callData", internalType: "bytes", type: "bytes" },
        ],
      },
    ],
    name: "getCreditAccountsByBorrower",
    outputs: [
      {
        name: "result",
        internalType: "struct CreditAccountData[]",
        type: "tuple[]",
        components: [
          { name: "isSuccessful", internalType: "bool", type: "bool" },
          {
            name: "priceFeedsNeeded",
            internalType: "address[]",
            type: "address[]",
          },
          { name: "addr", internalType: "address", type: "address" },
          { name: "borrower", internalType: "address", type: "address" },
          { name: "creditManager", internalType: "address", type: "address" },
          { name: "cmName", internalType: "string", type: "string" },
          { name: "creditFacade", internalType: "address", type: "address" },
          { name: "underlying", internalType: "address", type: "address" },
          { name: "debt", internalType: "uint256", type: "uint256" },
          {
            name: "cumulativeIndexLastUpdate",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "cumulativeQuotaInterest",
            internalType: "uint128",
            type: "uint128",
          },
          { name: "accruedInterest", internalType: "uint256", type: "uint256" },
          { name: "accruedFees", internalType: "uint256", type: "uint256" },
          { name: "totalDebtUSD", internalType: "uint256", type: "uint256" },
          { name: "totalValue", internalType: "uint256", type: "uint256" },
          { name: "totalValueUSD", internalType: "uint256", type: "uint256" },
          { name: "twvUSD", internalType: "uint256", type: "uint256" },
          {
            name: "enabledTokensMask",
            internalType: "uint256",
            type: "uint256",
          },
          { name: "healthFactor", internalType: "uint256", type: "uint256" },
          { name: "baseBorrowRate", internalType: "uint256", type: "uint256" },
          {
            name: "aggregatedBorrowRate",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "balances",
            internalType: "struct TokenBalance[]",
            type: "tuple[]",
            components: [
              { name: "token", internalType: "address", type: "address" },
              { name: "balance", internalType: "uint256", type: "uint256" },
              { name: "isForbidden", internalType: "bool", type: "bool" },
              { name: "isEnabled", internalType: "bool", type: "bool" },
              { name: "isQuoted", internalType: "bool", type: "bool" },
              { name: "quota", internalType: "uint256", type: "uint256" },
              { name: "quotaRate", internalType: "uint16", type: "uint16" },
              {
                name: "quotaCumulativeIndexLU",
                internalType: "uint256",
                type: "uint256",
              },
            ],
          },
          { name: "since", internalType: "uint64", type: "uint64" },
          { name: "cfVersion", internalType: "uint256", type: "uint256" },
          { name: "expirationDate", internalType: "uint40", type: "uint40" },
          { name: "activeBots", internalType: "address[]", type: "address[]" },
        ],
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "creditManager", internalType: "address", type: "address" },
      {
        name: "priceUpdates",
        internalType: "struct PriceOnDemand[]",
        type: "tuple[]",
        components: [
          { name: "token", internalType: "address", type: "address" },
          { name: "callData", internalType: "bytes", type: "bytes" },
        ],
      },
    ],
    name: "getCreditAccountsByCreditManager",
    outputs: [
      {
        name: "result",
        internalType: "struct CreditAccountData[]",
        type: "tuple[]",
        components: [
          { name: "isSuccessful", internalType: "bool", type: "bool" },
          {
            name: "priceFeedsNeeded",
            internalType: "address[]",
            type: "address[]",
          },
          { name: "addr", internalType: "address", type: "address" },
          { name: "borrower", internalType: "address", type: "address" },
          { name: "creditManager", internalType: "address", type: "address" },
          { name: "cmName", internalType: "string", type: "string" },
          { name: "creditFacade", internalType: "address", type: "address" },
          { name: "underlying", internalType: "address", type: "address" },
          { name: "debt", internalType: "uint256", type: "uint256" },
          {
            name: "cumulativeIndexLastUpdate",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "cumulativeQuotaInterest",
            internalType: "uint128",
            type: "uint128",
          },
          { name: "accruedInterest", internalType: "uint256", type: "uint256" },
          { name: "accruedFees", internalType: "uint256", type: "uint256" },
          { name: "totalDebtUSD", internalType: "uint256", type: "uint256" },
          { name: "totalValue", internalType: "uint256", type: "uint256" },
          { name: "totalValueUSD", internalType: "uint256", type: "uint256" },
          { name: "twvUSD", internalType: "uint256", type: "uint256" },
          {
            name: "enabledTokensMask",
            internalType: "uint256",
            type: "uint256",
          },
          { name: "healthFactor", internalType: "uint256", type: "uint256" },
          { name: "baseBorrowRate", internalType: "uint256", type: "uint256" },
          {
            name: "aggregatedBorrowRate",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "balances",
            internalType: "struct TokenBalance[]",
            type: "tuple[]",
            components: [
              { name: "token", internalType: "address", type: "address" },
              { name: "balance", internalType: "uint256", type: "uint256" },
              { name: "isForbidden", internalType: "bool", type: "bool" },
              { name: "isEnabled", internalType: "bool", type: "bool" },
              { name: "isQuoted", internalType: "bool", type: "bool" },
              { name: "quota", internalType: "uint256", type: "uint256" },
              { name: "quotaRate", internalType: "uint16", type: "uint16" },
              {
                name: "quotaCumulativeIndexLU",
                internalType: "uint256",
                type: "uint256",
              },
            ],
          },
          { name: "since", internalType: "uint64", type: "uint64" },
          { name: "cfVersion", internalType: "uint256", type: "uint256" },
          { name: "expirationDate", internalType: "uint40", type: "uint40" },
          { name: "activeBots", internalType: "address[]", type: "address[]" },
        ],
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_cm", internalType: "address", type: "address" }],
    name: "getCreditManagerData",
    outputs: [
      {
        name: "result",
        internalType: "struct CreditManagerData",
        type: "tuple",
        components: [
          { name: "addr", internalType: "address", type: "address" },
          { name: "name", internalType: "string", type: "string" },
          { name: "cfVersion", internalType: "uint256", type: "uint256" },
          { name: "creditFacade", internalType: "address", type: "address" },
          {
            name: "creditConfigurator",
            internalType: "address",
            type: "address",
          },
          { name: "underlying", internalType: "address", type: "address" },
          { name: "pool", internalType: "address", type: "address" },
          { name: "totalDebt", internalType: "uint256", type: "uint256" },
          { name: "totalDebtLimit", internalType: "uint256", type: "uint256" },
          { name: "baseBorrowRate", internalType: "uint256", type: "uint256" },
          { name: "minDebt", internalType: "uint256", type: "uint256" },
          { name: "maxDebt", internalType: "uint256", type: "uint256" },
          {
            name: "availableToBorrow",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "collateralTokens",
            internalType: "address[]",
            type: "address[]",
          },
          {
            name: "adapters",
            internalType: "struct ContractAdapter[]",
            type: "tuple[]",
            components: [
              {
                name: "targetContract",
                internalType: "address",
                type: "address",
              },
              { name: "adapter", internalType: "address", type: "address" },
            ],
          },
          {
            name: "liquidationThresholds",
            internalType: "uint256[]",
            type: "uint256[]",
          },
          { name: "isDegenMode", internalType: "bool", type: "bool" },
          { name: "degenNFT", internalType: "address", type: "address" },
          {
            name: "forbiddenTokenMask",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "maxEnabledTokensLength",
            internalType: "uint8",
            type: "uint8",
          },
          { name: "feeInterest", internalType: "uint16", type: "uint16" },
          { name: "feeLiquidation", internalType: "uint16", type: "uint16" },
          {
            name: "liquidationDiscount",
            internalType: "uint16",
            type: "uint16",
          },
          {
            name: "feeLiquidationExpired",
            internalType: "uint16",
            type: "uint16",
          },
          {
            name: "liquidationDiscountExpired",
            internalType: "uint16",
            type: "uint16",
          },
          {
            name: "quotas",
            internalType: "struct QuotaInfo[]",
            type: "tuple[]",
            components: [
              { name: "token", internalType: "address", type: "address" },
              { name: "rate", internalType: "uint16", type: "uint16" },
              {
                name: "quotaIncreaseFee",
                internalType: "uint16",
                type: "uint16",
              },
              { name: "totalQuoted", internalType: "uint96", type: "uint96" },
              { name: "limit", internalType: "uint96", type: "uint96" },
              { name: "isActive", internalType: "bool", type: "bool" },
            ],
          },
          {
            name: "lirm",
            internalType: "struct LinearModel",
            type: "tuple",
            components: [
              {
                name: "interestModel",
                internalType: "address",
                type: "address",
              },
              { name: "version", internalType: "uint256", type: "uint256" },
              { name: "U_1", internalType: "uint16", type: "uint16" },
              { name: "U_2", internalType: "uint16", type: "uint16" },
              { name: "R_base", internalType: "uint16", type: "uint16" },
              { name: "R_slope1", internalType: "uint16", type: "uint16" },
              { name: "R_slope2", internalType: "uint16", type: "uint16" },
              { name: "R_slope3", internalType: "uint16", type: "uint16" },
              {
                name: "isBorrowingMoreU2Forbidden",
                internalType: "bool",
                type: "bool",
              },
            ],
          },
          { name: "isPaused", internalType: "bool", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "getCreditManagersV3List",
    outputs: [
      {
        name: "result",
        internalType: "struct CreditManagerData[]",
        type: "tuple[]",
        components: [
          { name: "addr", internalType: "address", type: "address" },
          { name: "name", internalType: "string", type: "string" },
          { name: "cfVersion", internalType: "uint256", type: "uint256" },
          { name: "creditFacade", internalType: "address", type: "address" },
          {
            name: "creditConfigurator",
            internalType: "address",
            type: "address",
          },
          { name: "underlying", internalType: "address", type: "address" },
          { name: "pool", internalType: "address", type: "address" },
          { name: "totalDebt", internalType: "uint256", type: "uint256" },
          { name: "totalDebtLimit", internalType: "uint256", type: "uint256" },
          { name: "baseBorrowRate", internalType: "uint256", type: "uint256" },
          { name: "minDebt", internalType: "uint256", type: "uint256" },
          { name: "maxDebt", internalType: "uint256", type: "uint256" },
          {
            name: "availableToBorrow",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "collateralTokens",
            internalType: "address[]",
            type: "address[]",
          },
          {
            name: "adapters",
            internalType: "struct ContractAdapter[]",
            type: "tuple[]",
            components: [
              {
                name: "targetContract",
                internalType: "address",
                type: "address",
              },
              { name: "adapter", internalType: "address", type: "address" },
            ],
          },
          {
            name: "liquidationThresholds",
            internalType: "uint256[]",
            type: "uint256[]",
          },
          { name: "isDegenMode", internalType: "bool", type: "bool" },
          { name: "degenNFT", internalType: "address", type: "address" },
          {
            name: "forbiddenTokenMask",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "maxEnabledTokensLength",
            internalType: "uint8",
            type: "uint8",
          },
          { name: "feeInterest", internalType: "uint16", type: "uint16" },
          { name: "feeLiquidation", internalType: "uint16", type: "uint16" },
          {
            name: "liquidationDiscount",
            internalType: "uint16",
            type: "uint16",
          },
          {
            name: "feeLiquidationExpired",
            internalType: "uint16",
            type: "uint16",
          },
          {
            name: "liquidationDiscountExpired",
            internalType: "uint16",
            type: "uint16",
          },
          {
            name: "quotas",
            internalType: "struct QuotaInfo[]",
            type: "tuple[]",
            components: [
              { name: "token", internalType: "address", type: "address" },
              { name: "rate", internalType: "uint16", type: "uint16" },
              {
                name: "quotaIncreaseFee",
                internalType: "uint16",
                type: "uint16",
              },
              { name: "totalQuoted", internalType: "uint96", type: "uint96" },
              { name: "limit", internalType: "uint96", type: "uint96" },
              { name: "isActive", internalType: "bool", type: "bool" },
            ],
          },
          {
            name: "lirm",
            internalType: "struct LinearModel",
            type: "tuple",
            components: [
              {
                name: "interestModel",
                internalType: "address",
                type: "address",
              },
              { name: "version", internalType: "uint256", type: "uint256" },
              { name: "U_1", internalType: "uint16", type: "uint16" },
              { name: "U_2", internalType: "uint16", type: "uint16" },
              { name: "R_base", internalType: "uint16", type: "uint16" },
              { name: "R_slope1", internalType: "uint16", type: "uint16" },
              { name: "R_slope2", internalType: "uint16", type: "uint16" },
              { name: "R_slope3", internalType: "uint16", type: "uint16" },
              {
                name: "isBorrowingMoreU2Forbidden",
                internalType: "bool",
                type: "bool",
              },
            ],
          },
          { name: "isPaused", internalType: "bool", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "staker", internalType: "address", type: "address" }],
    name: "getGaugesV3Data",
    outputs: [
      {
        name: "result",
        internalType: "struct GaugeInfo[]",
        type: "tuple[]",
        components: [
          { name: "addr", internalType: "address", type: "address" },
          { name: "pool", internalType: "address", type: "address" },
          { name: "symbol", internalType: "string", type: "string" },
          { name: "name", internalType: "string", type: "string" },
          { name: "underlying", internalType: "address", type: "address" },
          { name: "currentEpoch", internalType: "uint16", type: "uint16" },
          { name: "epochFrozen", internalType: "bool", type: "bool" },
          {
            name: "quotaParams",
            internalType: "struct GaugeQuotaParams[]",
            type: "tuple[]",
            components: [
              { name: "token", internalType: "address", type: "address" },
              { name: "minRate", internalType: "uint16", type: "uint16" },
              { name: "maxRate", internalType: "uint16", type: "uint16" },
              {
                name: "totalVotesLpSide",
                internalType: "uint96",
                type: "uint96",
              },
              {
                name: "totalVotesCaSide",
                internalType: "uint96",
                type: "uint96",
              },
              { name: "rate", internalType: "uint16", type: "uint16" },
              {
                name: "quotaIncreaseFee",
                internalType: "uint16",
                type: "uint16",
              },
              { name: "totalQuoted", internalType: "uint96", type: "uint96" },
              { name: "limit", internalType: "uint96", type: "uint96" },
              { name: "isActive", internalType: "bool", type: "bool" },
              {
                name: "stakerVotesLpSide",
                internalType: "uint96",
                type: "uint96",
              },
              {
                name: "stakerVotesCaSide",
                internalType: "uint96",
                type: "uint96",
              },
            ],
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      {
        name: "priceUpdates",
        internalType: "struct PriceOnDemand[]",
        type: "tuple[]",
        components: [
          { name: "token", internalType: "address", type: "address" },
          { name: "callData", internalType: "bytes", type: "bytes" },
        ],
      },
    ],
    name: "getLiquidatableCreditAccounts",
    outputs: [
      {
        name: "result",
        internalType: "struct CreditAccountData[]",
        type: "tuple[]",
        components: [
          { name: "isSuccessful", internalType: "bool", type: "bool" },
          {
            name: "priceFeedsNeeded",
            internalType: "address[]",
            type: "address[]",
          },
          { name: "addr", internalType: "address", type: "address" },
          { name: "borrower", internalType: "address", type: "address" },
          { name: "creditManager", internalType: "address", type: "address" },
          { name: "cmName", internalType: "string", type: "string" },
          { name: "creditFacade", internalType: "address", type: "address" },
          { name: "underlying", internalType: "address", type: "address" },
          { name: "debt", internalType: "uint256", type: "uint256" },
          {
            name: "cumulativeIndexLastUpdate",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "cumulativeQuotaInterest",
            internalType: "uint128",
            type: "uint128",
          },
          { name: "accruedInterest", internalType: "uint256", type: "uint256" },
          { name: "accruedFees", internalType: "uint256", type: "uint256" },
          { name: "totalDebtUSD", internalType: "uint256", type: "uint256" },
          { name: "totalValue", internalType: "uint256", type: "uint256" },
          { name: "totalValueUSD", internalType: "uint256", type: "uint256" },
          { name: "twvUSD", internalType: "uint256", type: "uint256" },
          {
            name: "enabledTokensMask",
            internalType: "uint256",
            type: "uint256",
          },
          { name: "healthFactor", internalType: "uint256", type: "uint256" },
          { name: "baseBorrowRate", internalType: "uint256", type: "uint256" },
          {
            name: "aggregatedBorrowRate",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "balances",
            internalType: "struct TokenBalance[]",
            type: "tuple[]",
            components: [
              { name: "token", internalType: "address", type: "address" },
              { name: "balance", internalType: "uint256", type: "uint256" },
              { name: "isForbidden", internalType: "bool", type: "bool" },
              { name: "isEnabled", internalType: "bool", type: "bool" },
              { name: "isQuoted", internalType: "bool", type: "bool" },
              { name: "quota", internalType: "uint256", type: "uint256" },
              { name: "quotaRate", internalType: "uint16", type: "uint16" },
              {
                name: "quotaCumulativeIndexLU",
                internalType: "uint256",
                type: "uint256",
              },
            ],
          },
          { name: "since", internalType: "uint64", type: "uint64" },
          { name: "cfVersion", internalType: "uint256", type: "uint256" },
          { name: "expirationDate", internalType: "uint40", type: "uint40" },
          { name: "activeBots", internalType: "address[]", type: "address[]" },
        ],
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "_pool", internalType: "address", type: "address" }],
    name: "getPoolData",
    outputs: [
      {
        name: "result",
        internalType: "struct PoolData",
        type: "tuple",
        components: [
          { name: "addr", internalType: "address", type: "address" },
          { name: "underlying", internalType: "address", type: "address" },
          { name: "dieselToken", internalType: "address", type: "address" },
          { name: "symbol", internalType: "string", type: "string" },
          { name: "name", internalType: "string", type: "string" },
          {
            name: "baseInterestIndex",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "availableLiquidity",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "expectedLiquidity",
            internalType: "uint256",
            type: "uint256",
          },
          { name: "totalBorrowed", internalType: "uint256", type: "uint256" },
          { name: "totalDebtLimit", internalType: "uint256", type: "uint256" },
          {
            name: "creditManagerDebtParams",
            internalType: "struct CreditManagerDebtParams[]",
            type: "tuple[]",
            components: [
              {
                name: "creditManager",
                internalType: "address",
                type: "address",
              },
              { name: "borrowed", internalType: "uint256", type: "uint256" },
              { name: "limit", internalType: "uint256", type: "uint256" },
              {
                name: "availableToBorrow",
                internalType: "uint256",
                type: "uint256",
              },
            ],
          },
          { name: "totalAssets", internalType: "uint256", type: "uint256" },
          { name: "totalSupply", internalType: "uint256", type: "uint256" },
          { name: "supplyRate", internalType: "uint256", type: "uint256" },
          {
            name: "baseInterestRate",
            internalType: "uint256",
            type: "uint256",
          },
          { name: "dieselRate_RAY", internalType: "uint256", type: "uint256" },
          { name: "withdrawFee", internalType: "uint256", type: "uint256" },
          {
            name: "lastBaseInterestUpdate",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "baseInterestIndexLU",
            internalType: "uint256",
            type: "uint256",
          },
          { name: "version", internalType: "uint256", type: "uint256" },
          { name: "poolQuotaKeeper", internalType: "address", type: "address" },
          { name: "gauge", internalType: "address", type: "address" },
          {
            name: "quotas",
            internalType: "struct QuotaInfo[]",
            type: "tuple[]",
            components: [
              { name: "token", internalType: "address", type: "address" },
              { name: "rate", internalType: "uint16", type: "uint16" },
              {
                name: "quotaIncreaseFee",
                internalType: "uint16",
                type: "uint16",
              },
              { name: "totalQuoted", internalType: "uint96", type: "uint96" },
              { name: "limit", internalType: "uint96", type: "uint96" },
              { name: "isActive", internalType: "bool", type: "bool" },
            ],
          },
          {
            name: "zappers",
            internalType: "struct ZapperInfo[]",
            type: "tuple[]",
            components: [
              { name: "zapper", internalType: "address", type: "address" },
              { name: "tokenIn", internalType: "address", type: "address" },
              { name: "tokenOut", internalType: "address", type: "address" },
            ],
          },
          {
            name: "lirm",
            internalType: "struct LinearModel",
            type: "tuple",
            components: [
              {
                name: "interestModel",
                internalType: "address",
                type: "address",
              },
              { name: "version", internalType: "uint256", type: "uint256" },
              { name: "U_1", internalType: "uint16", type: "uint16" },
              { name: "U_2", internalType: "uint16", type: "uint16" },
              { name: "R_base", internalType: "uint16", type: "uint16" },
              { name: "R_slope1", internalType: "uint16", type: "uint16" },
              { name: "R_slope2", internalType: "uint16", type: "uint16" },
              { name: "R_slope3", internalType: "uint16", type: "uint16" },
              {
                name: "isBorrowingMoreU2Forbidden",
                internalType: "bool",
                type: "bool",
              },
            ],
          },
          { name: "isPaused", internalType: "bool", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "getPoolsV3List",
    outputs: [
      {
        name: "result",
        internalType: "struct PoolData[]",
        type: "tuple[]",
        components: [
          { name: "addr", internalType: "address", type: "address" },
          { name: "underlying", internalType: "address", type: "address" },
          { name: "dieselToken", internalType: "address", type: "address" },
          { name: "symbol", internalType: "string", type: "string" },
          { name: "name", internalType: "string", type: "string" },
          {
            name: "baseInterestIndex",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "availableLiquidity",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "expectedLiquidity",
            internalType: "uint256",
            type: "uint256",
          },
          { name: "totalBorrowed", internalType: "uint256", type: "uint256" },
          { name: "totalDebtLimit", internalType: "uint256", type: "uint256" },
          {
            name: "creditManagerDebtParams",
            internalType: "struct CreditManagerDebtParams[]",
            type: "tuple[]",
            components: [
              {
                name: "creditManager",
                internalType: "address",
                type: "address",
              },
              { name: "borrowed", internalType: "uint256", type: "uint256" },
              { name: "limit", internalType: "uint256", type: "uint256" },
              {
                name: "availableToBorrow",
                internalType: "uint256",
                type: "uint256",
              },
            ],
          },
          { name: "totalAssets", internalType: "uint256", type: "uint256" },
          { name: "totalSupply", internalType: "uint256", type: "uint256" },
          { name: "supplyRate", internalType: "uint256", type: "uint256" },
          {
            name: "baseInterestRate",
            internalType: "uint256",
            type: "uint256",
          },
          { name: "dieselRate_RAY", internalType: "uint256", type: "uint256" },
          { name: "withdrawFee", internalType: "uint256", type: "uint256" },
          {
            name: "lastBaseInterestUpdate",
            internalType: "uint256",
            type: "uint256",
          },
          {
            name: "baseInterestIndexLU",
            internalType: "uint256",
            type: "uint256",
          },
          { name: "version", internalType: "uint256", type: "uint256" },
          { name: "poolQuotaKeeper", internalType: "address", type: "address" },
          { name: "gauge", internalType: "address", type: "address" },
          {
            name: "quotas",
            internalType: "struct QuotaInfo[]",
            type: "tuple[]",
            components: [
              { name: "token", internalType: "address", type: "address" },
              { name: "rate", internalType: "uint16", type: "uint16" },
              {
                name: "quotaIncreaseFee",
                internalType: "uint16",
                type: "uint16",
              },
              { name: "totalQuoted", internalType: "uint96", type: "uint96" },
              { name: "limit", internalType: "uint96", type: "uint96" },
              { name: "isActive", internalType: "bool", type: "bool" },
            ],
          },
          {
            name: "zappers",
            internalType: "struct ZapperInfo[]",
            type: "tuple[]",
            components: [
              { name: "zapper", internalType: "address", type: "address" },
              { name: "tokenIn", internalType: "address", type: "address" },
              { name: "tokenOut", internalType: "address", type: "address" },
            ],
          },
          {
            name: "lirm",
            internalType: "struct LinearModel",
            type: "tuple",
            components: [
              {
                name: "interestModel",
                internalType: "address",
                type: "address",
              },
              { name: "version", internalType: "uint256", type: "uint256" },
              { name: "U_1", internalType: "uint16", type: "uint16" },
              { name: "U_2", internalType: "uint16", type: "uint16" },
              { name: "R_base", internalType: "uint16", type: "uint16" },
              { name: "R_slope1", internalType: "uint16", type: "uint16" },
              { name: "R_slope2", internalType: "uint16", type: "uint16" },
              { name: "R_slope3", internalType: "uint16", type: "uint16" },
              {
                name: "isBorrowingMoreU2Forbidden",
                internalType: "bool",
                type: "bool",
              },
            ],
          },
          { name: "isPaused", internalType: "bool", type: "bool" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "version",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "zapperRegister",
    outputs: [
      { name: "", internalType: "contract IZapperRegister", type: "address" },
    ],
    stateMutability: "view",
  },
  { type: "error", inputs: [], name: "CreditManagerIsNotV3Exception" },
  { type: "error", inputs: [], name: "PriceFeedDoesNotExistException" },
  { type: "error", inputs: [], name: "RegisteredCreditManagerOnlyException" },
  { type: "error", inputs: [], name: "RegisteredPoolOnlyException" },
  { type: "error", inputs: [], name: "ZeroAddressException" },
] as const;

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// DegenDistributorV3
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const degenDistributorV3Abi = [
  {
    type: "constructor",
    inputs: [
      { name: "addressProvider", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "index", internalType: "uint256", type: "uint256" },
      { name: "account", internalType: "address", type: "address" },
      { name: "totalAmount", internalType: "uint256", type: "uint256" },
      { name: "merkleProof", internalType: "bytes32[]", type: "bytes32[]" },
    ],
    name: "claim",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [{ name: "", internalType: "address", type: "address" }],
    name: "claimed",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "degenNFT",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "merkleRoot",
    outputs: [{ name: "", internalType: "bytes32", type: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "treasury",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "newRoot", internalType: "bytes32", type: "bytes32" }],
    name: "updateMerkleRoot",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "version",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: true,
      },
      {
        name: "amount",
        internalType: "uint256",
        type: "uint256",
        indexed: false,
      },
    ],
    name: "Claimed",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "oldRoot",
        internalType: "bytes32",
        type: "bytes32",
        indexed: false,
      },
      {
        name: "newRoot",
        internalType: "bytes32",
        type: "bytes32",
        indexed: true,
      },
    ],
    name: "RootUpdated",
  },
  { type: "error", inputs: [], name: "TreasuryOnlyException" },
] as const;

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// MultiPause
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const multiPauseAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "addressProvider", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "acl",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "contractsRegister",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "controller",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "pauseAllContracts",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "pauseAllCreditManagers",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "pauseAllPools",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "contracts", internalType: "address[]", type: "address[]" },
    ],
    name: "pauseContracts",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "paused",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [
      { name: "newController", internalType: "address", type: "address" },
    ],
    name: "setController",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "unpauseAllContracts",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newController",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "NewController",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Paused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Unpaused",
  },
  { type: "error", inputs: [], name: "CallerNotConfiguratorException" },
  { type: "error", inputs: [], name: "CallerNotPausableAdminException" },
  { type: "error", inputs: [], name: "CallerNotUnpausableAdminException" },
  { type: "error", inputs: [], name: "ZeroAddressException" },
] as const;

/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// ZapperRegister
/// ///////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const zapperRegisterAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "addressProvider", internalType: "address", type: "address" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "acl",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "zapper", internalType: "address", type: "address" }],
    name: "addZapper",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "contractsRegister",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "controller",
    outputs: [{ name: "", internalType: "address", type: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [],
    name: "pause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "paused",
    outputs: [{ name: "", internalType: "bool", type: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "zapper", internalType: "address", type: "address" }],
    name: "removeZapper",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [
      { name: "newController", internalType: "address", type: "address" },
    ],
    name: "setController",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "unpause",
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    inputs: [],
    name: "version",
    outputs: [{ name: "", internalType: "uint256", type: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    inputs: [{ name: "pool", internalType: "address", type: "address" }],
    name: "zappers",
    outputs: [{ name: "", internalType: "address[]", type: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "", internalType: "address", type: "address", indexed: false },
    ],
    name: "AddZapper",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "newController",
        internalType: "address",
        type: "address",
        indexed: true,
      },
    ],
    name: "NewController",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Paused",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      { name: "", internalType: "address", type: "address", indexed: false },
    ],
    name: "RemoveZapper",
  },
  {
    type: "event",
    anonymous: false,
    inputs: [
      {
        name: "account",
        internalType: "address",
        type: "address",
        indexed: false,
      },
    ],
    name: "Unpaused",
  },
  { type: "error", inputs: [], name: "CallerNotConfiguratorException" },
  { type: "error", inputs: [], name: "CallerNotControllerException" },
  { type: "error", inputs: [], name: "CallerNotPausableAdminException" },
  { type: "error", inputs: [], name: "CallerNotUnpausableAdminException" },
  { type: "error", inputs: [], name: "RegisteredPoolOnlyException" },
  { type: "error", inputs: [], name: "ZeroAddressException" },
] as const;
