"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.IYVault__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var IYVault__factory_1 = require("./IYVault__factory");
Object.defineProperty(exports, "IYVault__factory", { enumerable: true, get: function () { return IYVault__factory_1.IYVault__factory; } });
