"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LPPriceFeedTest__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var LPPriceFeedTest__factory_1 = require("./LPPriceFeedTest__factory");
Object.defineProperty(exports, "LPPriceFeedTest__factory", { enumerable: true, get: function () { return LPPriceFeedTest__factory_1.LPPriceFeedTest__factory; } });
