export declare enum AdapterInterface {
    NO_SWAP = 0,
    UNISWAP_V2_ROUTER = 1,
    UNISWAP_V3_ROUTER = 2,
    CURVE_V1_2ASSETS = 3,
    CURVE_V1_3ASSETS = 4,
    CURVE_V1_4ASSETS = 5,
    CURVE_V1_STECRV_POOL = 6,
    CURVE_V1_DEPOSIT = 7,
    YEARN_V2 = 8,
    CONVEX_V1_BASE_REWARD_POOL = 9,
    CONVEX_V1_BOOSTER = 10,
    CONVEX_V1_CLAIM_ZAP = 11,
    LIDO_V1 = 12
}
