import { BigNumber } from "ethers";
export declare const MAX_INT: BigNumber;
export declare const MAINNET_NETWORK = 1;
export declare const KOVAN_NETWORK = 42;
export declare const LOCAL_NETWORK = 1337;
export declare type NetworkType = "Mainnet" | "Kovan";
export declare const getNetworkType: (chainId: number) => NetworkType;
export declare const RAY_DECIMALS = 27;
export declare const RAY: BigNumber;
export declare const halfRAY: BigNumber;
export declare const WAD_DECIMALS = 18;
export declare const WAD: BigNumber;
export declare const PRICE_DECIMALS_POW = 8;
export declare const PRICE_DECIMALS: BigNumber;
export declare const SECONDS_PER_YEAR: number;
export declare const PERCENTAGE_DECIMALS = 100;
export declare const PERCENTAGE_FACTOR = 10000;
export declare const LIQUIDATION_DISCOUNTED_SUM = 9500;
export declare const UNDERLYING_TOKEN_LIQUIDATION_THRESHOLD = 9300;
export declare const timeRanges: Record<string, number>;
export declare const LEVERAGE_DECIMALS = 100;
export declare const SLIPPAGE_DECIMALS = 100;
export declare const ADDRESS_0x0 = "0x0000000000000000000000000000000000000000";
