"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.TradeType = void 0;
var TradeType;
(function (TradeType) {
    TradeType[TradeType["UniswapV2Swap"] = 0] = "UniswapV2Swap";
    TradeType[TradeType["UniswapV3Swap"] = 1] = "UniswapV3Swap";
    TradeType[TradeType["CurveExchange"] = 2] = "CurveExchange";
    TradeType[TradeType["CurveExchangeUnderlying"] = 3] = "CurveExchangeUnderlying";
    TradeType[TradeType["CurveDepositLP"] = 4] = "CurveDepositLP";
    TradeType[TradeType["CurveWithdrawLP"] = 5] = "CurveWithdrawLP";
    TradeType[TradeType["YearnDeposit"] = 6] = "YearnDeposit";
    TradeType[TradeType["YearnWithdraw"] = 7] = "YearnWithdraw";
    TradeType[TradeType["LidoStake"] = 8] = "LidoStake";
    TradeType[TradeType["ConvexDepositLP"] = 9] = "ConvexDepositLP";
    TradeType[TradeType["ConvexStake"] = 10] = "ConvexStake";
    TradeType[TradeType["ConvexDepositLPAndStake"] = 11] = "ConvexDepositLPAndStake";
    TradeType[TradeType["ConvexWithdrawLP"] = 12] = "ConvexWithdrawLP";
    TradeType[TradeType["ConvexWithdraw"] = 13] = "ConvexWithdraw";
    TradeType[TradeType["ConvexWithdrawAndUnwrap"] = 14] = "ConvexWithdrawAndUnwrap";
})(TradeType = exports.TradeType || (exports.TradeType = {}));
