import { BigNumber, BigNumberish } from "ethers";
export declare function rayToNumber(num: BigNumberish): number;
export declare function formatRAY(num?: BigNumber): string;
export declare function formatBN(num: BigNumberish | undefined, decimals: number, precision?: number): string;
export declare function formatBn4dig(num: BigNumber, precision?: number): string;
export declare function toHumanFormat(num: BigNumber, precision?: number): string;
export declare function toSignificant(num: BigNumber, decimals: number): string;
export declare function toBN(num: string, decimals: number): BigNumber;
export declare function shortAddress(address?: string): string;
export declare function shortHash(address?: string): string;
export declare const formatRate: (rate: BigNumberish | undefined) => string;
export declare function formatDate(date: Date): string;
export declare function formatHf(healthFactor: number): string;
export declare function formatLeverage(leverage: number, decimals?: number): string;
