export const RWA_FACTORY_SECURITIZE = "RWA_FACTORY::SECURITIZE";

export const RWA_LIQUIDATOR_SECURITIZE = "RWA_LIQUIDATOR::SECURITIZE";

export const PHANTOM_TOKEN_SECURITIZE_REDEMPTION =
  "PHANTOM_TOKEN::SECURITIZE_RD";
