export const RWA_LIQUIDATOR_SECURITIZE = "RWA_LIQUIDATOR::SECURITIZE";

export const PHANTOM_TOKEN_SECURITIZE_REDEMPTION =
  "PHANTOM_TOKEN::SECURITIZE_RD";

export const DEGEN_NFT_SECURITIZE = "DEGEN_NFT::SECURITIZE";
