"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MainnetTokensTestSuite__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var MainnetTokensTestSuite__factory_1 = require("./MainnetTokensTestSuite__factory");
Object.defineProperty(exports, "MainnetTokensTestSuite__factory", { enumerable: true, get: function () { return MainnetTokensTestSuite__factory_1.MainnetTokensTestSuite__factory; } });
