"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ICreditManagerV2Exceptions__factory = exports.ICreditManagerV2Events__factory = exports.ICreditManagerV2__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ICreditManagerV2__factory_1 = require("./ICreditManagerV2__factory");
Object.defineProperty(exports, "ICreditManagerV2__factory", { enumerable: true, get: function () { return ICreditManagerV2__factory_1.ICreditManagerV2__factory; } });
var ICreditManagerV2Events__factory_1 = require("./ICreditManagerV2Events__factory");
Object.defineProperty(exports, "ICreditManagerV2Events__factory", { enumerable: true, get: function () { return ICreditManagerV2Events__factory_1.ICreditManagerV2Events__factory; } });
var ICreditManagerV2Exceptions__factory_1 = require("./ICreditManagerV2Exceptions__factory");
Object.defineProperty(exports, "ICreditManagerV2Exceptions__factory", { enumerable: true, get: function () { return ICreditManagerV2Exceptions__factory_1.ICreditManagerV2Exceptions__factory; } });
