export enum AdapterInterface {
  NO_SWAP, // 0
  UNISWAP_V2_ROUTER, // 1
  UNISWAP_V3_ROUTER, // 2
  CURVE_V1_EXCHANGE_ONLY, // 3
  YEARN_V2, // 4
  CURVE_V1_2ASSETS, // 5
  CURVE_V1_3ASSETS, // 6
  CURVE_V1_4ASSETS, // 7
  CURVE_V1_STECRV_POOL, // 8
  CURVE_V1_WRAPPER, // 9
  CONVEX_V1_BASE_REWARD_POOL, // 10
  CONVEX_V1_BOOSTER, // 11
  CONVEX_V1_CLAIM_ZAP, // 12
  LIDO_V1, // 13
  UNIVERSAL, // 14
}
