export const governorAbi = [
  {
    type: "constructor",
    inputs: [
      { name: "_owner", type: "address", internalType: "address" },
      { name: "_vetoAdmin", type: "address", internalType: "address" },
      { name: "_delay", type: "uint256", internalType: "uint256" },
      {
        name: "_allowPermissionlessExecution",
        type: "bool",
        internalType: "bool",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "acceptOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addExecutionAdmin",
    inputs: [{ name: "admin", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addQueueAdmin",
    inputs: [{ name: "admin", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "allowPermissionlessExecution",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "batchInfo",
    inputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "initiator", type: "address", internalType: "address" },
      { name: "length", type: "uint16", internalType: "uint16" },
      { name: "eta", type: "uint80", internalType: "uint80" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "batchedTxInfo",
    inputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    outputs: [
      { name: "batchBlock", type: "uint64", internalType: "uint64" },
      { name: "index", type: "uint16", internalType: "uint16" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cancelBatch",
    inputs: [
      {
        name: "txs",
        type: "tuple[]",
        internalType: "struct IGovernor.TxParams[]",
        components: [
          { name: "target", type: "address", internalType: "address" },
          { name: "value", type: "uint256", internalType: "uint256" },
          { name: "signature", type: "string", internalType: "string" },
          { name: "data", type: "bytes", internalType: "bytes" },
          { name: "eta", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "cancelTransaction",
    inputs: [
      { name: "target", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
      { name: "signature", type: "string", internalType: "string" },
      { name: "data", type: "bytes", internalType: "bytes" },
      { name: "eta", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "contractType",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "executeBatch",
    inputs: [
      {
        name: "txs",
        type: "tuple[]",
        internalType: "struct IGovernor.TxParams[]",
        components: [
          { name: "target", type: "address", internalType: "address" },
          { name: "value", type: "uint256", internalType: "uint256" },
          { name: "signature", type: "string", internalType: "string" },
          { name: "data", type: "bytes", internalType: "bytes" },
          { name: "eta", type: "uint256", internalType: "uint256" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "executeTransaction",
    inputs: [
      { name: "target", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
      { name: "signature", type: "string", internalType: "string" },
      { name: "data", type: "bytes", internalType: "bytes" },
      { name: "eta", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bytes", internalType: "bytes" }],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "executionAdmins",
    inputs: [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "forbidPermissionlessExecution",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "isPermissionlessExecutionAllowed",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "owner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pendingOwner",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "queueAdmins",
    inputs: [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "queueTransaction",
    inputs: [
      { name: "target", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
      { name: "signature", type: "string", internalType: "string" },
      { name: "data", type: "bytes", internalType: "bytes" },
      { name: "eta", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "txHash", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeExecutionAdmin",
    inputs: [{ name: "admin", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeQueueAdmin",
    inputs: [{ name: "admin", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "renounceOwnership",
    inputs: [],
    outputs: [],
    stateMutability: "pure",
  },
  {
    type: "function",
    name: "startBatch",
    inputs: [{ name: "eta", type: "uint80", internalType: "uint80" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "timeLock",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transferOwnership",
    inputs: [{ name: "newOwner", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateVetoAdmin",
    inputs: [{ name: "admin", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "version",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "vetoAdmin",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AddExecutionAdmin",
    inputs: [
      {
        name: "admin",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AddQueueAdmin",
    inputs: [
      {
        name: "admin",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AllowPermissionlessExecution",
    inputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "CancelBatch",
    inputs: [
      {
        name: "caller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "batchBlock",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ExecuteBatch",
    inputs: [
      {
        name: "caller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "batchBlock",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ForbidPermissionlessExecution",
    inputs: [],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferStarted",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OwnershipTransferred",
    inputs: [
      {
        name: "previousOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newOwner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "QueueBatch",
    inputs: [
      {
        name: "caller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "batchBlock",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RemoveExecutionAdmin",
    inputs: [
      {
        name: "admin",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RemoveQueueAdmin",
    inputs: [
      {
        name: "admin",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UpdateVetoAdmin",
    inputs: [
      {
        name: "admin",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  { type: "error", name: "AdminCantBeZeroAddressException", inputs: [] },
  { type: "error", name: "BatchAlreadyStartedException", inputs: [] },
  { type: "error", name: "CallerNotBatchInitiatorException", inputs: [] },
  { type: "error", name: "CallerNotExecutionAdminException", inputs: [] },
  { type: "error", name: "CallerNotQueueAdminException", inputs: [] },
  { type: "error", name: "CallerNotTimelockException", inputs: [] },
  { type: "error", name: "CallerNotVetoAdminException", inputs: [] },
  { type: "error", name: "CannotRenounceOwnershipException", inputs: [] },
  { type: "error", name: "CantPerformActionOutsideBatchException", inputs: [] },
  { type: "error", name: "ETAMistmatchException", inputs: [] },
  { type: "error", name: "IncorrectBatchException", inputs: [] },
  { type: "error", name: "TransactionAlreadyQueuedException", inputs: [] },
  {
    type: "error",
    name: "UnexpectedTransactionException",
    inputs: [{ name: "txHash", type: "bytes32", internalType: "bytes32" }],
  },
] as const;
