"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.LidoMock__factory = exports.ILidoMockEvents__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ILidoMockEvents__factory_1 = require("./ILidoMockEvents__factory");
Object.defineProperty(exports, "ILidoMockEvents__factory", { enumerable: true, get: function () { return ILidoMockEvents__factory_1.ILidoMockEvents__factory; } });
var LidoMock__factory_1 = require("./LidoMock__factory");
Object.defineProperty(exports, "LidoMock__factory", { enumerable: true, get: function () { return LidoMock__factory_1.LidoMock__factory; } });
