export const CROSS_CHAIN_GOVERNANCE = "CROSS_CHAIN_GOVERNANCE";
export const BYTECODE_REPOSITORY = "BYTECODE_REPOSITORY";
export const INSTANCE_MANAGER = "INSTANCE_MANAGER";
export const TOKEN_COMPRESSOR = "GLOBAL::TOKEN_COMPRESSOR";
export const CROSS_CHAIN_MULTISIG = "CROSS_CHAIN_MULTISIG";
export const PRICE_FEED_STORE = "PRICE_FEED_STORE";
export const MARKET_CONFIGURATOR_FACTORY = "MARKET_CONFIGURATOR_FACTORY";
