"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.ISwapRouter__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var ISwapRouter__factory_1 = require("./ISwapRouter__factory");
Object.defineProperty(exports, "ISwapRouter__factory", { enumerable: true, get: function () { return ISwapRouter__factory_1.ISwapRouter__factory; } });
