export enum TokenType {
  // CONNECTOR,
  NORMAL_TOKEN,
  CURVE_LP,
  META_CURVE_LP,
  YEARN_VAULT,
  YEARN_VAULT_OF_CURVE_LP,
  YEARN_VAULT_OF_META_CURVE_LP,
  CONVEX_LP_TOKEN,
  CONVEX_STAKED_PHANTOM_TOKEN,
  DIESEL_LP_TOKEN,
}
