export enum TokenType {
  NO_TOKEN,
  NORMAL_TOKEN,
  CURVE_LP_TOKEN,
  YEARN_ON_NORMAL_TOKEN,
  YEARN_ON_CURVE_TOKEN,
  CONVEX_LP_TOKEN,
  CONVEX_STAKED_TOKEN,
  DIESEL_LP_TOKEN,
  GEAR_TOKEN,
  C_TOKEN,
  BALANCER_LP_TOKEN,
}
