import type { Address } from "viem";

import type { NetworkType } from "../../chain/index.js";
import { NOT_DEPLOYED } from "../../constants/index.js";
import {
  type CurveLPToken,
  type ERC4626LPToken,
  type NormalToken,
  tokenDataByNetwork,
} from "../tokens/index.js";
import { AdapterInterface } from "./adapters.js";

type UniswapV2Contract =
  | "UNISWAP_V2_ROUTER"
  | "SUSHISWAP_ROUTER"
  | "FRAXSWAP_ROUTER";

export type CurvePoolContract =
  | "CURVE_3CRV_POOL"
  | "CURVE_FRAX_USDC_POOL"
  | "CURVE_STETH_GATEWAY"
  | "CURVE_FRAX_POOL"
  | "CURVE_LUSD_POOL"
  | "CURVE_GUSD_POOL"
  | "CURVE_SUSD_POOL"
  | "CURVE_SUSD_DEPOSIT"
  | "CURVE_CRVETH_POOL"
  | "CURVE_CVXETH_POOL"
  | "CURVE_3CRYPTO_POOL"
  | "CURVE_LDOETH_POOL"
  | "CURVE_CRVUSD_USDC_POOL"
  | "CURVE_CRVUSD_USDT_POOL"
  | "CURVE_CRVUSD_FRAX_POOL"
  | "CURVE_TRI_CRV_POOL"
  | "CURVE_RETH_ETH_POOL"
  | "CURVE_USDE_USDC_POOL"
  | "CURVE_FRAX_USDE_POOL"
  | "CURVE_USDE_CRVUSD_POOL"
  | "CURVE_FRAX_SDAI_POOL"
  | "CURVE_DOLA_SUSDE_POOL"
  | "CURVE_DOLA_FRAXBP_POOL"
  | "CURVE_DOLA_CRVUSD_POOL"
  | "CURVE_USDE_DAI_POOL"
  | "CURVE_SDAI_SUSDE_POOL"
  | "CURVE_GHO_USDE_POOL"
  | "CURVE_PUFETH_WSTETH_POOL"
  | "CURVE_GHO_CRVUSD_POOL"
  | "CURVE_EZETH_ETH_POOL"
  | "CURVE_EZPZ_ETH_POOL"
  | "CURVE_LBTC_WBTC_POOL"
  | "CURVE_EBTC_WBTC_POOL"
  | "CURVE_PUMPBTC_WBTC_POOL"
  | "CURVE_TRIBTC_POOL"
  | "CURVE_tBTC_WBTC_POOL"
  | "CURVE_2CRV_POOL_ARB"
  | "CURVE_TRICRYPTO_CRVUSD_POOL_ARB"
  | "CURVE_CRVUSD_USDC_POOL_ARB"
  | "CURVE_CRVUSD_USDT_POOL_ARB"
  | "CURVE_CRVUSD_USDC_E_POOL_ARB"
  | "CURVE_USDE_USDC_POOL_ARB"
  | "CURVE_3CRV_POOL_OP"
  | "CURVE_ETH_WSTETH_GATEWAY_OP"
  | "CURVE_CRVUSD_SUSDE_POOL"
  | "CURVE_LLAMA_THENA_POOL"
  | "CURVE_tETH_wstETH_POOL"
  | "CURVE_tETH_weETH_POOL"
  | "CURVE_pzETH_stETH_POOL"
  | "CURVE_USDL_USDC_POOL";

export type YearnVaultContract =
  | "YEARN_DAI_VAULT"
  | "YEARN_USDC_VAULT"
  | "YEARN_USDC_E_VAULT"
  | "YEARN_WETH_VAULT"
  | "YEARN_WBTC_VAULT"
  | "YEARN_USDT_VAULT"
  | "YEARN_OP_VAULT"
  | "YEARN_CURVE_FRAX_VAULT"
  | "YEARN_CURVE_STETH_VAULT";

export type ERC4626VaultContract =
  | "MAKER_DSR_VAULT"
  | "YIELD_ETH_VAULT"
  | "STAKED_USDE_VAULT"
  | "STAKED_USDS_VAULT"
  | "SAVINGS_CRVUSD_VAULT"
  | "AAVE_WSTETH_VAULT"
  | "WRAPPED_USDL_VAULT"
  | "COINSHIFT_USDL_VAULT";

export type ConvexPoolContract =
  | "CONVEX_3CRV_POOL"
  | "CONVEX_FRAX_USDC_POOL"
  | "CONVEX_GUSD_POOL"
  | "CONVEX_SUSD_POOL"
  | "CONVEX_STECRV_POOL"
  | "CONVEX_FRAX3CRV_POOL"
  | "CONVEX_LUSD3CRV_POOL"
  | "CONVEX_CRVETH_POOL"
  | "CONVEX_CVXETH_POOL"
  | "CONVEX_3CRYPTO_POOL"
  | "CONVEX_LDOETH_POOL"
  | "CONVEX_CRVUSD_USDC_POOL"
  | "CONVEX_CRVUSD_USDT_POOL"
  | "CONVEX_CRVUSD_FRAX_POOL"
  | "CONVEX_TRI_CRV_POOL"
  | "CONVEX_GHO_CRVUSD_POOL"
  | "CONVEX_CRVUSD_USDT_POOL_ARB"
  | "CONVEX_LLAMA_THENA_POOL";

export type AuraPoolContract =
  | "AURA_B_RETH_STABLE_POOL"
  | "AURA_WEETH_RETH_POOL"
  | "AURA_OSETH_WETH_POOL"
  | "AURA_BPT_RETH_ETH_POOL"
  | "AURA_BPT_WSTETH_ETH_POOL"
  | "AURA_WSTETH_WETH_POOL_ARB"
  | "AURA_WSTETH_RETH_SFRXETH_POOL_ARB"
  | "AURA_CBETH_RETH_WSTETH_POOL_ARB"
  | "AURA_RETH_WETH_POOL_ARB";

type AaveV2TokenWrapperContract =
  | "AAVE_V2_DAI_TOKEN_WRAPPER"
  | "AAVE_V2_USDC_TOKEN_WRAPPER"
  | "AAVE_V2_USDT_TOKEN_WRAPPER"
  | "AAVE_V2_WETH_TOKEN_WRAPPER";

type CompoundV2PoolContract =
  | "COMPOUND_V2_DAI_POOL"
  | "COMPOUND_V2_USDC_POOL"
  | "COMPOUND_V2_USDT_POOL"
  | "COMPOUND_V2_ETH_GATEWAY"
  | "COMPOUND_V2_LINK_POOL"
  | "FLUX_USDC_POOL";

type MellowVaultContract =
  | "MELLOW_STEAKHOUSE_VAULT"
  | "MELLOW_RE7_LABS_VAULT"
  | "MELLOW_AMPHOR_VAULT"
  | "MELLOW_RESTAKING_VAULT"
  | "MELLOW_RENZO_VAULT"
  | "MELLOW_DECENTALIZED_VALIDATOR_VAULT";

export type StakingRewardsContract = "SKY_STAKING_REWARDS";

export type SupportedContract =
  | UniswapV2Contract
  | "UNISWAP_V3_ROUTER"
  | "PANCAKESWAP_V3_ROUTER"
  | CurvePoolContract
  | "CURVE_GEAR_POOL"
  | YearnVaultContract
  | "CONVEX_BOOSTER"
  | "CONVEX_BOOSTER_ARB"
  | ConvexPoolContract
  | "AURA_BOOSTER"
  | AuraPoolContract
  | "LIDO_STETH_GATEWAY"
  | "LIDO_WSTETH"
  | "UNIVERSAL_ADAPTER"
  | "BALANCER_VAULT"
  | "BALANCER_V3_ROUTER"
  | "AAVE_V2_LENDING_POOL"
  | AaveV2TokenWrapperContract
  | CompoundV2PoolContract
  | ERC4626VaultContract
  | MellowVaultContract
  | "VELODROME_V2_ROUTER"
  | "EQUALIZER_ROUTER"
  | "VELODROME_CL_ROUTER"
  | "SHADOW_ROUTER"
  | "CAMELOT_V3_ROUTER"
  | "AAVE_V3_LENDING_POOL"
  | "ZIRCUIT_POOL"
  | "PENDLE_ROUTER"
  | StakingRewardsContract
  | "DAI_USDS";

export const contractsByNetwork: Record<
  NetworkType,
  Record<SupportedContract, Address>
> = {
  Mainnet: {
    UNISWAP_V2_ROUTER: "0x7a250d5630B4cF539739dF2C5dAcb4c659F2488D",
    UNISWAP_V3_ROUTER: "0xE592427A0AEce92De3Edee1F18E0157C05861564",
    PANCAKESWAP_V3_ROUTER: "0x1b81D678ffb9C0263b24A97847620C99d213eB14",
    SUSHISWAP_ROUTER: "0xd9e1cE17f2641f24aE83637ab66a2cca9C378B9F",
    FRAXSWAP_ROUTER: "0xC14d550632db8592D1243Edc8B95b0Ad06703867",
    VELODROME_V2_ROUTER: NOT_DEPLOYED,
    VELODROME_CL_ROUTER: NOT_DEPLOYED,
    EQUALIZER_ROUTER: NOT_DEPLOYED,
    SHADOW_ROUTER: NOT_DEPLOYED,
    CAMELOT_V3_ROUTER: NOT_DEPLOYED,
    PENDLE_ROUTER: "0x888888888889758F76e7103c6CbF23ABbF58F946",

    // CURVE
    CURVE_3CRV_POOL: "0xbEbc44782C7dB0a1A60Cb6fe97d0b483032FF1C7", // SEPARATE TOKEN
    CURVE_FRAX_USDC_POOL: "0xDcEF968d416a41Cdac0ED8702fAC8128A64241A2",
    CURVE_STETH_GATEWAY: "0xEf0D72C594b28252BF7Ea2bfbF098792430815b1", // SEPARATE TOKEN
    CURVE_FRAX_POOL: tokenDataByNetwork.Mainnet.FRAX3CRV,
    CURVE_LUSD_POOL: tokenDataByNetwork.Mainnet.LUSD3CRV,
    CURVE_SUSD_POOL: "0xA5407eAE9Ba41422680e2e00537571bcC53efBfD", // SEPARATE TOKEN
    CURVE_SUSD_DEPOSIT: "0xFCBa3E75865d2d561BE8D220616520c171F12851",
    CURVE_GUSD_POOL: "0x4f062658EaAF2C1ccf8C8e36D6824CDf41167956", // SEPARATE TOKEN
    CURVE_CRVETH_POOL: "0x8301AE4fc9c624d1D396cbDAa1ed877821D7C511",
    CURVE_CVXETH_POOL: "0xB576491F1E6e5E62f1d8F26062Ee822B40B0E0d4",
    CURVE_3CRYPTO_POOL: tokenDataByNetwork.Mainnet.crvUSDTWBTCWETH,
    CURVE_LDOETH_POOL: "0x9409280DC1e6D33AB7A8C6EC03e5763FB61772B5",
    CURVE_ETH_WSTETH_GATEWAY_OP: NOT_DEPLOYED,
    CURVE_USDE_USDC_POOL: tokenDataByNetwork.Mainnet.USDeUSDC,
    CURVE_FRAX_USDE_POOL: tokenDataByNetwork.Mainnet.FRAXUSDe,
    CURVE_USDE_CRVUSD_POOL: tokenDataByNetwork.Mainnet.USDecrvUSD,
    CURVE_FRAX_SDAI_POOL: tokenDataByNetwork.Mainnet.FRAXsDAI,
    CURVE_DOLA_SUSDE_POOL: tokenDataByNetwork.Mainnet.DOLAsUSDe,
    CURVE_DOLA_FRAXBP_POOL: tokenDataByNetwork.Mainnet.DOLAFRAXBP3CRV_f,
    CURVE_DOLA_CRVUSD_POOL: tokenDataByNetwork.Mainnet.crvUSDDOLA_f,
    CURVE_USDE_DAI_POOL: tokenDataByNetwork.Mainnet.USDeDAI,
    CURVE_SDAI_SUSDE_POOL: tokenDataByNetwork.Mainnet.MtEthena,
    CURVE_GHO_USDE_POOL: tokenDataByNetwork.Mainnet.GHOUSDe,
    CURVE_PUFETH_WSTETH_POOL: tokenDataByNetwork.Mainnet.pufETHwstE,
    CURVE_GHO_CRVUSD_POOL: tokenDataByNetwork.Mainnet.GHOcrvUSD,
    CURVE_EZETH_ETH_POOL: tokenDataByNetwork.Mainnet.ezETHWETH,
    CURVE_EZPZ_ETH_POOL: tokenDataByNetwork.Mainnet.ezpzETH,
    CURVE_LBTC_WBTC_POOL: tokenDataByNetwork.Mainnet.LBTCWBTC,
    CURVE_EBTC_WBTC_POOL: tokenDataByNetwork.Mainnet.eBTCWBTC,
    CURVE_PUMPBTC_WBTC_POOL: tokenDataByNetwork.Mainnet.pumpBTCWBTC,
    CURVE_TRIBTC_POOL: tokenDataByNetwork.Mainnet.TriBTC,
    CURVE_tBTC_WBTC_POOL: tokenDataByNetwork.Mainnet["2BTC-f"],
    CURVE_tETH_wstETH_POOL: tokenDataByNetwork.Mainnet.tETHwstETH,
    CURVE_tETH_weETH_POOL: tokenDataByNetwork.Mainnet.tETHweETH,
    CURVE_pzETH_stETH_POOL: tokenDataByNetwork.Mainnet.pzETHstETH,
    CURVE_USDL_USDC_POOL: tokenDataByNetwork.Mainnet.USDLUSDC,

    CURVE_GEAR_POOL: "0x0E9B5B092caD6F1c5E6bc7f89Ffe1abb5c95F1C2",

    CURVE_CRVUSD_USDC_POOL: tokenDataByNetwork.Mainnet.crvUSDUSDC,
    CURVE_CRVUSD_USDT_POOL: tokenDataByNetwork.Mainnet.crvUSDUSDT,
    CURVE_CRVUSD_FRAX_POOL: tokenDataByNetwork.Mainnet.crvUSDFRAX,
    CURVE_TRI_CRV_POOL: tokenDataByNetwork.Mainnet.crvUSDETHCRV,
    CURVE_CRVUSD_SUSDE_POOL: tokenDataByNetwork.Mainnet.crvUsUSDe,
    CURVE_LLAMA_THENA_POOL: tokenDataByNetwork.Mainnet.llamathena,

    CURVE_RETH_ETH_POOL: "0x0f3159811670c117c372428D4E69AC32325e4D0F",

    CURVE_3CRV_POOL_OP: NOT_DEPLOYED,
    CURVE_2CRV_POOL_ARB: tokenDataByNetwork.Mainnet["2CRV"],
    CURVE_TRICRYPTO_CRVUSD_POOL_ARB: tokenDataByNetwork.Mainnet["3c-crvUSD"],
    CURVE_CRVUSD_USDC_POOL_ARB: tokenDataByNetwork.Mainnet.crvUSDC,
    CURVE_CRVUSD_USDT_POOL_ARB: tokenDataByNetwork.Mainnet.crvUSDT,
    CURVE_CRVUSD_USDC_E_POOL_ARB: tokenDataByNetwork.Mainnet.crvUSDC_e,
    CURVE_USDE_USDC_POOL_ARB: tokenDataByNetwork.Mainnet.USDEUSDC,

    // YEARN
    YEARN_DAI_VAULT: tokenDataByNetwork.Mainnet.yvDAI,
    YEARN_USDC_VAULT: tokenDataByNetwork.Mainnet.yvUSDC,
    YEARN_USDC_E_VAULT: tokenDataByNetwork.Mainnet.yvUSDC_e,
    YEARN_WETH_VAULT: tokenDataByNetwork.Mainnet.yvWETH,
    YEARN_WBTC_VAULT: tokenDataByNetwork.Mainnet.yvWBTC,
    YEARN_USDT_VAULT: tokenDataByNetwork.Mainnet.yvUSDT,
    YEARN_OP_VAULT: tokenDataByNetwork.Mainnet.yvOP,
    YEARN_CURVE_FRAX_VAULT: tokenDataByNetwork.Mainnet.yvCurve_FRAX,
    YEARN_CURVE_STETH_VAULT: tokenDataByNetwork.Mainnet.yvCurve_stETH,

    // ERC4626
    MAKER_DSR_VAULT: tokenDataByNetwork.Mainnet.sDAI,
    YIELD_ETH_VAULT: tokenDataByNetwork.Mainnet.YieldETH,
    STAKED_USDE_VAULT: tokenDataByNetwork.Mainnet.sUSDe,
    STAKED_USDS_VAULT: tokenDataByNetwork.Mainnet.sUSDS,
    SAVINGS_CRVUSD_VAULT: tokenDataByNetwork.Mainnet.scrvUSD,
    AAVE_WSTETH_VAULT: tokenDataByNetwork.Mainnet.waEthLidowstETH,
    WRAPPED_USDL_VAULT: tokenDataByNetwork.Mainnet.wUSDL,
    COINSHIFT_USDL_VAULT: tokenDataByNetwork.Mainnet.csUSDL,

    // CONVEX
    CONVEX_BOOSTER: "0xF403C135812408BFbE8713b5A23a04b3D48AAE31",
    CONVEX_3CRV_POOL: "0x689440f2Ff927E1f24c72F1087E1FAF471eCe1c8",
    CONVEX_FRAX_USDC_POOL: "0x7e880867363A7e321f5d260Cade2B0Bb2F717B02",
    CONVEX_GUSD_POOL: "0x7A7bBf95C44b144979360C3300B54A7D34b44985",
    CONVEX_SUSD_POOL: "0x22eE18aca7F3Ee920D01F25dA85840D12d98E8Ca",
    CONVEX_STECRV_POOL: "0x0A760466E1B4621579a82a39CB56Dda2F4E70f03",
    CONVEX_FRAX3CRV_POOL: "0xB900EF131301B307dB5eFcbed9DBb50A3e209B2e",
    CONVEX_LUSD3CRV_POOL: "0x2ad92A7aE036a038ff02B96c88de868ddf3f8190",
    CONVEX_CRVETH_POOL: "0x085A2054c51eA5c91dbF7f90d65e728c0f2A270f",
    CONVEX_CVXETH_POOL: "0xb1Fb0BA0676A1fFA83882c7F4805408bA232C1fA",
    CONVEX_3CRYPTO_POOL: "0xb05262D4aaAA38D0Af4AaB244D446ebDb5afd4A7",
    CONVEX_LDOETH_POOL: "0x8CA990E954611E5E3d2cc51C013fCC372c8c1D38",
    CONVEX_CRVUSD_USDC_POOL: "0x44D8FaB7CD8b7877D5F79974c2F501aF6E65AbBA",
    CONVEX_CRVUSD_USDT_POOL: "0xD1DdB0a0815fD28932fBb194C84003683AF8a824",
    CONVEX_CRVUSD_FRAX_POOL: "0x3CfB4B26dc96B124D15A6f360503d028cF2a3c00",
    CONVEX_TRI_CRV_POOL: "0xF956a46DbA1A0a567168db8655bc18E9050C7738",
    CONVEX_GHO_CRVUSD_POOL: "0x5eC758f79b96AE74e7F1Ba9583009aFB3fc8eACB",
    CONVEX_LLAMA_THENA_POOL: "0x11fD8801a051b296E337a3e1168839fb346D5940",

    CONVEX_BOOSTER_ARB: NOT_DEPLOYED,
    CONVEX_CRVUSD_USDT_POOL_ARB: tokenDataByNetwork.Mainnet.cvxcrvUSDT,

    // AURA
    AURA_BOOSTER: "0xA57b8d98dAE62B26Ec3bcC4a365338157060B234",
    AURA_WEETH_RETH_POOL: tokenDataByNetwork.Mainnet.auraweETH_rETH_vault,
    AURA_OSETH_WETH_POOL: tokenDataByNetwork.Mainnet.auraosETH_wETH_BPT_vault,
    AURA_B_RETH_STABLE_POOL: tokenDataByNetwork.Mainnet.auraB_rETH_STABLE_vault,
    AURA_BPT_RETH_ETH_POOL: tokenDataByNetwork.Mainnet.auraBPT_rETH_ETH_vault,
    AURA_BPT_WSTETH_ETH_POOL:
      tokenDataByNetwork.Mainnet.auraBPT_WSTETH_ETH_vault,
    AURA_RETH_WETH_POOL_ARB: tokenDataByNetwork.Mainnet.aurarETH_wETH_BPT_vault,
    AURA_WSTETH_WETH_POOL_ARB:
      tokenDataByNetwork.Mainnet.aurawstETH_WETH_BPT_vault,
    AURA_CBETH_RETH_WSTETH_POOL_ARB:
      tokenDataByNetwork.Mainnet.auracbETH_rETH_wstETH_vault,
    AURA_WSTETH_RETH_SFRXETH_POOL_ARB:
      tokenDataByNetwork.Mainnet.aurawstETH_rETH_sfrxETH_vault,

    // LIDO
    LIDO_STETH_GATEWAY: "0x6f4b4aB5142787c05b7aB9A9692A0f46b997C29D",
    LIDO_WSTETH: tokenDataByNetwork.Mainnet.wstETH,

    // BALANCER
    BALANCER_VAULT: "0xBA12222222228d8Ba445958a75a0704d566BF2C8",
    BALANCER_V3_ROUTER: "0x5C6fb490BDFD3246EB0bB062c168DeCAF4bD9FDd",

    // GEARBOX
    UNIVERSAL_ADAPTER: "0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC",

    // AAVE
    AAVE_V2_LENDING_POOL: "0x7d2768dE32b0b80b7a3454c06BdAc94A69DDc7A9",
    AAVE_V3_LENDING_POOL: "0x87870Bca3F3fD6335C3F4ce8392D69350B4fA4E2",

    AAVE_V2_DAI_TOKEN_WRAPPER: tokenDataByNetwork.Mainnet.waDAI,
    AAVE_V2_USDC_TOKEN_WRAPPER: tokenDataByNetwork.Mainnet.waUSDC,
    AAVE_V2_USDT_TOKEN_WRAPPER: tokenDataByNetwork.Mainnet.waUSDT,
    AAVE_V2_WETH_TOKEN_WRAPPER: tokenDataByNetwork.Mainnet.waWETH,

    COMPOUND_V2_DAI_POOL: tokenDataByNetwork.Mainnet.cDAI,
    COMPOUND_V2_USDC_POOL: tokenDataByNetwork.Mainnet.cUSDC,
    COMPOUND_V2_USDT_POOL: tokenDataByNetwork.Mainnet.cUSDT,
    COMPOUND_V2_LINK_POOL: tokenDataByNetwork.Mainnet.cLINK,
    COMPOUND_V2_ETH_GATEWAY: NOT_DEPLOYED,

    FLUX_USDC_POOL: tokenDataByNetwork.Mainnet.fUSDC,

    ZIRCUIT_POOL: "0xF047ab4c75cebf0eB9ed34Ae2c186f3611aEAfa6",

    // MELLOW
    MELLOW_STEAKHOUSE_VAULT: tokenDataByNetwork.Mainnet.steakLRT,
    MELLOW_RE7_LABS_VAULT: tokenDataByNetwork.Mainnet.Re7LRT,
    MELLOW_AMPHOR_VAULT: tokenDataByNetwork.Mainnet.amphrETH,
    MELLOW_RESTAKING_VAULT: tokenDataByNetwork.Mainnet.rstETH,
    MELLOW_RENZO_VAULT: tokenDataByNetwork.Mainnet.pzETH,
    MELLOW_DECENTALIZED_VALIDATOR_VAULT: tokenDataByNetwork.Mainnet.DVstETH,

    // SKY
    SKY_STAKING_REWARDS: "0x0650CAF159C5A49f711e8169D4336ECB9b950275",
    DAI_USDS: "0x3225737a9Bbb6473CB4a45b7244ACa2BeFdB276A",
  },

  //
  //
  //
  //
  //  A R B I T R U M
  //
  //
  //
  //
  Arbitrum: {
    UNISWAP_V2_ROUTER: NOT_DEPLOYED,
    UNISWAP_V3_ROUTER: "0xE592427A0AEce92De3Edee1F18E0157C05861564",
    PANCAKESWAP_V3_ROUTER: "0x1b81D678ffb9C0263b24A97847620C99d213eB14",
    SUSHISWAP_ROUTER: NOT_DEPLOYED,
    FRAXSWAP_ROUTER: NOT_DEPLOYED,
    VELODROME_V2_ROUTER: NOT_DEPLOYED,
    VELODROME_CL_ROUTER: NOT_DEPLOYED,
    EQUALIZER_ROUTER: NOT_DEPLOYED,
    SHADOW_ROUTER: NOT_DEPLOYED,
    CAMELOT_V3_ROUTER: "0x1F721E2E82F6676FCE4eA07A5958cF098D339e18",
    PENDLE_ROUTER: NOT_DEPLOYED,

    // CURVE
    CURVE_3CRV_POOL: NOT_DEPLOYED,
    CURVE_FRAX_USDC_POOL: NOT_DEPLOYED,
    CURVE_STETH_GATEWAY: NOT_DEPLOYED,
    CURVE_FRAX_POOL: tokenDataByNetwork.Arbitrum.FRAX3CRV,
    CURVE_LUSD_POOL: tokenDataByNetwork.Arbitrum.LUSD3CRV,
    CURVE_SUSD_POOL: NOT_DEPLOYED,
    CURVE_SUSD_DEPOSIT: NOT_DEPLOYED,
    CURVE_GUSD_POOL: NOT_DEPLOYED,
    CURVE_CRVETH_POOL: NOT_DEPLOYED,
    CURVE_CVXETH_POOL: NOT_DEPLOYED,
    CURVE_3CRYPTO_POOL: NOT_DEPLOYED,
    CURVE_LDOETH_POOL: NOT_DEPLOYED,
    CURVE_USDE_USDC_POOL: tokenDataByNetwork.Arbitrum.USDeUSDC,
    CURVE_FRAX_USDE_POOL: tokenDataByNetwork.Arbitrum.FRAXUSDe,
    CURVE_USDE_CRVUSD_POOL: tokenDataByNetwork.Arbitrum.USDecrvUSD,
    CURVE_FRAX_SDAI_POOL: tokenDataByNetwork.Arbitrum.FRAXsDAI,
    CURVE_DOLA_SUSDE_POOL: tokenDataByNetwork.Arbitrum.DOLAsUSDe,
    CURVE_DOLA_FRAXBP_POOL: tokenDataByNetwork.Arbitrum.DOLAFRAXBP3CRV_f,
    CURVE_DOLA_CRVUSD_POOL: tokenDataByNetwork.Arbitrum.crvUSDDOLA_f,
    CURVE_USDE_DAI_POOL: tokenDataByNetwork.Arbitrum.USDeDAI,
    CURVE_SDAI_SUSDE_POOL: tokenDataByNetwork.Arbitrum.MtEthena,
    CURVE_GHO_USDE_POOL: tokenDataByNetwork.Arbitrum.GHOUSDe,
    CURVE_PUFETH_WSTETH_POOL: tokenDataByNetwork.Arbitrum.pufETHwstE,
    CURVE_GHO_CRVUSD_POOL: tokenDataByNetwork.Arbitrum.GHOcrvUSD,
    CURVE_ETH_WSTETH_GATEWAY_OP: NOT_DEPLOYED,
    CURVE_EZETH_ETH_POOL: NOT_DEPLOYED,
    CURVE_EZPZ_ETH_POOL: NOT_DEPLOYED,
    CURVE_LBTC_WBTC_POOL: NOT_DEPLOYED,
    CURVE_EBTC_WBTC_POOL: NOT_DEPLOYED,
    CURVE_PUMPBTC_WBTC_POOL: NOT_DEPLOYED,
    CURVE_TRIBTC_POOL: NOT_DEPLOYED,
    CURVE_tBTC_WBTC_POOL: NOT_DEPLOYED,
    CURVE_tETH_wstETH_POOL: NOT_DEPLOYED,
    CURVE_tETH_weETH_POOL: NOT_DEPLOYED,
    CURVE_pzETH_stETH_POOL: NOT_DEPLOYED,
    CURVE_USDL_USDC_POOL: NOT_DEPLOYED,

    CURVE_GEAR_POOL: NOT_DEPLOYED,

    CURVE_CRVUSD_USDC_POOL: tokenDataByNetwork.Arbitrum.crvUSDUSDC,
    CURVE_CRVUSD_USDT_POOL: tokenDataByNetwork.Arbitrum.crvUSDUSDT,
    CURVE_CRVUSD_FRAX_POOL: tokenDataByNetwork.Arbitrum.crvUSDFRAX,
    CURVE_TRI_CRV_POOL: tokenDataByNetwork.Arbitrum.crvUSDETHCRV,
    CURVE_CRVUSD_SUSDE_POOL: tokenDataByNetwork.Arbitrum.crvUsUSDe,
    CURVE_LLAMA_THENA_POOL: tokenDataByNetwork.Arbitrum.llamathena,

    CURVE_RETH_ETH_POOL: NOT_DEPLOYED,
    CURVE_3CRV_POOL_OP: NOT_DEPLOYED,

    CURVE_2CRV_POOL_ARB: tokenDataByNetwork.Arbitrum["2CRV"],
    CURVE_TRICRYPTO_CRVUSD_POOL_ARB: tokenDataByNetwork.Arbitrum["3c-crvUSD"],
    CURVE_CRVUSD_USDC_POOL_ARB: tokenDataByNetwork.Arbitrum.crvUSDC,
    CURVE_CRVUSD_USDT_POOL_ARB: tokenDataByNetwork.Arbitrum.crvUSDT,
    CURVE_CRVUSD_USDC_E_POOL_ARB: tokenDataByNetwork.Arbitrum.crvUSDC_e,
    CURVE_USDE_USDC_POOL_ARB: tokenDataByNetwork.Arbitrum.USDEUSDC,

    // YEARN
    YEARN_DAI_VAULT: tokenDataByNetwork.Arbitrum.yvDAI,
    YEARN_USDC_VAULT: tokenDataByNetwork.Arbitrum.yvUSDC,
    YEARN_USDC_E_VAULT: tokenDataByNetwork.Arbitrum.yvUSDC_e,
    YEARN_WETH_VAULT: tokenDataByNetwork.Arbitrum.yvWETH,
    YEARN_WBTC_VAULT: tokenDataByNetwork.Arbitrum.yvWBTC,
    YEARN_USDT_VAULT: tokenDataByNetwork.Arbitrum.yvUSDT,
    YEARN_OP_VAULT: tokenDataByNetwork.Arbitrum.yvOP,
    YEARN_CURVE_FRAX_VAULT: tokenDataByNetwork.Arbitrum.yvCurve_FRAX,
    YEARN_CURVE_STETH_VAULT: tokenDataByNetwork.Arbitrum.yvCurve_stETH,

    /// ERC4626
    MAKER_DSR_VAULT: tokenDataByNetwork.Arbitrum.sDAI,
    YIELD_ETH_VAULT: tokenDataByNetwork.Arbitrum.YieldETH,
    STAKED_USDE_VAULT: tokenDataByNetwork.Arbitrum.sUSDe,
    STAKED_USDS_VAULT: tokenDataByNetwork.Arbitrum.sUSDS,
    SAVINGS_CRVUSD_VAULT: tokenDataByNetwork.Arbitrum.scrvUSD,
    AAVE_WSTETH_VAULT: tokenDataByNetwork.Arbitrum.waEthLidowstETH,
    WRAPPED_USDL_VAULT: tokenDataByNetwork.Arbitrum.wUSDL,
    COINSHIFT_USDL_VAULT: tokenDataByNetwork.Arbitrum.csUSDL,

    // CONVEX
    CONVEX_BOOSTER: NOT_DEPLOYED,
    CONVEX_3CRV_POOL: NOT_DEPLOYED,
    CONVEX_FRAX_USDC_POOL: NOT_DEPLOYED,
    CONVEX_STECRV_POOL: NOT_DEPLOYED,
    CONVEX_SUSD_POOL: NOT_DEPLOYED,
    CONVEX_FRAX3CRV_POOL: NOT_DEPLOYED,
    CONVEX_LUSD3CRV_POOL: NOT_DEPLOYED,
    CONVEX_GUSD_POOL: NOT_DEPLOYED,
    CONVEX_CRVETH_POOL: NOT_DEPLOYED,
    CONVEX_CVXETH_POOL: NOT_DEPLOYED,
    CONVEX_3CRYPTO_POOL: NOT_DEPLOYED,
    CONVEX_LDOETH_POOL: NOT_DEPLOYED,
    CONVEX_CRVUSD_USDC_POOL: NOT_DEPLOYED,
    CONVEX_CRVUSD_USDT_POOL: NOT_DEPLOYED,
    CONVEX_CRVUSD_FRAX_POOL: NOT_DEPLOYED,
    CONVEX_TRI_CRV_POOL: NOT_DEPLOYED,
    CONVEX_GHO_CRVUSD_POOL: NOT_DEPLOYED,
    CONVEX_LLAMA_THENA_POOL: NOT_DEPLOYED,

    CONVEX_BOOSTER_ARB: "0xF403C135812408BFbE8713b5A23a04b3D48AAE31",
    CONVEX_CRVUSD_USDT_POOL_ARB: tokenDataByNetwork.Arbitrum.cvxcrvUSDT,

    AURA_BOOSTER: "0x98Ef32edd24e2c92525E59afc4475C1242a30184",
    AURA_WEETH_RETH_POOL: tokenDataByNetwork.Arbitrum.auraweETH_rETH_vault,
    AURA_OSETH_WETH_POOL: tokenDataByNetwork.Arbitrum.auraosETH_wETH_BPT_vault,
    AURA_B_RETH_STABLE_POOL:
      tokenDataByNetwork.Arbitrum.auraB_rETH_STABLE_vault,
    AURA_BPT_RETH_ETH_POOL: tokenDataByNetwork.Arbitrum.auraBPT_rETH_ETH_vault,
    AURA_BPT_WSTETH_ETH_POOL:
      tokenDataByNetwork.Arbitrum.auraBPT_WSTETH_ETH_vault,
    AURA_RETH_WETH_POOL_ARB:
      tokenDataByNetwork.Arbitrum.aurarETH_wETH_BPT_vault,
    AURA_WSTETH_WETH_POOL_ARB:
      tokenDataByNetwork.Arbitrum.aurawstETH_WETH_BPT_vault,
    AURA_CBETH_RETH_WSTETH_POOL_ARB:
      tokenDataByNetwork.Arbitrum.auracbETH_rETH_wstETH_vault,
    AURA_WSTETH_RETH_SFRXETH_POOL_ARB:
      tokenDataByNetwork.Arbitrum.aurawstETH_rETH_sfrxETH_vault,

    // LIDO
    LIDO_STETH_GATEWAY: NOT_DEPLOYED,
    LIDO_WSTETH: NOT_DEPLOYED,

    // BALANCER
    BALANCER_VAULT: "0xBA12222222228d8Ba445958a75a0704d566BF2C8",
    BALANCER_V3_ROUTER: NOT_DEPLOYED,

    // GEARBOX
    UNIVERSAL_ADAPTER: "0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC",

    // AAVE
    AAVE_V2_LENDING_POOL: NOT_DEPLOYED,
    AAVE_V3_LENDING_POOL: "0x794a61358D6845594F94dc1DB02A252b5b4814aD",

    AAVE_V2_DAI_TOKEN_WRAPPER: tokenDataByNetwork.Arbitrum.waDAI,
    AAVE_V2_USDC_TOKEN_WRAPPER: tokenDataByNetwork.Arbitrum.waUSDC,
    AAVE_V2_USDT_TOKEN_WRAPPER: tokenDataByNetwork.Arbitrum.waUSDT,
    AAVE_V2_WETH_TOKEN_WRAPPER: tokenDataByNetwork.Arbitrum.waWETH,

    COMPOUND_V2_DAI_POOL: tokenDataByNetwork.Arbitrum.cDAI,
    COMPOUND_V2_USDC_POOL: tokenDataByNetwork.Arbitrum.cUSDC,
    COMPOUND_V2_USDT_POOL: tokenDataByNetwork.Arbitrum.cUSDT,
    COMPOUND_V2_LINK_POOL: tokenDataByNetwork.Arbitrum.cLINK,
    COMPOUND_V2_ETH_GATEWAY: NOT_DEPLOYED,

    FLUX_USDC_POOL: tokenDataByNetwork.Arbitrum.fUSDC,
    ZIRCUIT_POOL: NOT_DEPLOYED,

    // MELLOW
    MELLOW_STEAKHOUSE_VAULT: tokenDataByNetwork.Arbitrum.steakLRT,
    MELLOW_RE7_LABS_VAULT: tokenDataByNetwork.Arbitrum.Re7LRT,
    MELLOW_AMPHOR_VAULT: tokenDataByNetwork.Arbitrum.amphrETH,
    MELLOW_RESTAKING_VAULT: tokenDataByNetwork.Arbitrum.rstETH,
    MELLOW_RENZO_VAULT: tokenDataByNetwork.Arbitrum.pzETH,
    MELLOW_DECENTALIZED_VALIDATOR_VAULT: tokenDataByNetwork.Arbitrum.DVstETH,

    SKY_STAKING_REWARDS: NOT_DEPLOYED,
    DAI_USDS: NOT_DEPLOYED,
  },
  //
  //
  //
  //
  //  OPTIMISM
  //
  //
  //
  //
  Optimism: {
    UNISWAP_V2_ROUTER: NOT_DEPLOYED,
    UNISWAP_V3_ROUTER: "0xE592427A0AEce92De3Edee1F18E0157C05861564", // UNVERIFIED!
    PANCAKESWAP_V3_ROUTER: NOT_DEPLOYED,
    SUSHISWAP_ROUTER: NOT_DEPLOYED,
    FRAXSWAP_ROUTER: "0xB9A55F455e46e8D717eEA5E47D2c449416A0437F", // UNVERIFIED!
    VELODROME_V2_ROUTER: "0xa062aE8A9c5e11aaA026fc2670B0D65cCc8B2858",
    VELODROME_CL_ROUTER: "0x0792a633F0c19c351081CF4B211F68F79bCc9676",
    EQUALIZER_ROUTER: NOT_DEPLOYED,
    SHADOW_ROUTER: NOT_DEPLOYED,
    CAMELOT_V3_ROUTER: NOT_DEPLOYED,
    PENDLE_ROUTER: NOT_DEPLOYED,

    // CURVE
    CURVE_3CRV_POOL_OP: "0x1337BedC9D22ecbe766dF105c9623922A27963EC",
    CURVE_3CRV_POOL: NOT_DEPLOYED,
    CURVE_FRAX_USDC_POOL: NOT_DEPLOYED,
    CURVE_STETH_GATEWAY: NOT_DEPLOYED,
    CURVE_FRAX_POOL: tokenDataByNetwork.Optimism.FRAX3CRV,
    CURVE_LUSD_POOL: tokenDataByNetwork.Optimism.LUSD3CRV,
    CURVE_SUSD_POOL: NOT_DEPLOYED,
    CURVE_SUSD_DEPOSIT: NOT_DEPLOYED,
    CURVE_GUSD_POOL: NOT_DEPLOYED,
    CURVE_CRVETH_POOL: NOT_DEPLOYED,
    CURVE_CVXETH_POOL: NOT_DEPLOYED,
    CURVE_3CRYPTO_POOL: NOT_DEPLOYED,
    CURVE_LDOETH_POOL: NOT_DEPLOYED,
    CURVE_USDE_USDC_POOL: tokenDataByNetwork.Optimism.USDeUSDC,
    CURVE_FRAX_USDE_POOL: tokenDataByNetwork.Optimism.FRAXUSDe,
    CURVE_USDE_CRVUSD_POOL: tokenDataByNetwork.Optimism.USDecrvUSD,
    CURVE_FRAX_SDAI_POOL: tokenDataByNetwork.Optimism.FRAXsDAI,
    CURVE_DOLA_SUSDE_POOL: tokenDataByNetwork.Optimism.DOLAsUSDe,
    CURVE_DOLA_FRAXBP_POOL: tokenDataByNetwork.Optimism.DOLAFRAXBP3CRV_f,
    CURVE_DOLA_CRVUSD_POOL: tokenDataByNetwork.Optimism.crvUSDDOLA_f,
    CURVE_USDE_DAI_POOL: tokenDataByNetwork.Optimism.USDeDAI,
    CURVE_SDAI_SUSDE_POOL: tokenDataByNetwork.Optimism.MtEthena,
    CURVE_GHO_USDE_POOL: tokenDataByNetwork.Optimism.GHOUSDe,
    CURVE_PUFETH_WSTETH_POOL: tokenDataByNetwork.Optimism.pufETHwstE,
    CURVE_GHO_CRVUSD_POOL: tokenDataByNetwork.Optimism.GHOcrvUSD,
    CURVE_ETH_WSTETH_GATEWAY_OP: "0xF12057505cd8e3256d3654C0dC32BEB0c531eb77",
    CURVE_EZETH_ETH_POOL: NOT_DEPLOYED,
    CURVE_EZPZ_ETH_POOL: NOT_DEPLOYED,
    CURVE_LBTC_WBTC_POOL: NOT_DEPLOYED,
    CURVE_EBTC_WBTC_POOL: NOT_DEPLOYED,
    CURVE_PUMPBTC_WBTC_POOL: NOT_DEPLOYED,
    CURVE_TRIBTC_POOL: NOT_DEPLOYED,
    CURVE_tBTC_WBTC_POOL: NOT_DEPLOYED,
    CURVE_tETH_wstETH_POOL: NOT_DEPLOYED,
    CURVE_tETH_weETH_POOL: NOT_DEPLOYED,
    CURVE_pzETH_stETH_POOL: NOT_DEPLOYED,
    CURVE_USDL_USDC_POOL: NOT_DEPLOYED,

    CURVE_GEAR_POOL: NOT_DEPLOYED,

    CURVE_CRVUSD_USDC_POOL: tokenDataByNetwork.Optimism.crvUSDUSDC,
    CURVE_CRVUSD_USDT_POOL: tokenDataByNetwork.Optimism.crvUSDUSDT,
    CURVE_CRVUSD_FRAX_POOL: tokenDataByNetwork.Optimism.crvUSDFRAX,
    CURVE_TRI_CRV_POOL: tokenDataByNetwork.Optimism.crvUSDETHCRV,
    CURVE_CRVUSD_SUSDE_POOL: tokenDataByNetwork.Optimism.crvUsUSDe,
    CURVE_LLAMA_THENA_POOL: tokenDataByNetwork.Optimism.llamathena,

    CURVE_RETH_ETH_POOL: NOT_DEPLOYED,

    CURVE_2CRV_POOL_ARB: tokenDataByNetwork.Optimism["2CRV"],
    CURVE_TRICRYPTO_CRVUSD_POOL_ARB: tokenDataByNetwork.Optimism["3c-crvUSD"],
    CURVE_CRVUSD_USDC_POOL_ARB: tokenDataByNetwork.Optimism.crvUSDC,
    CURVE_CRVUSD_USDT_POOL_ARB: tokenDataByNetwork.Optimism.crvUSDT,
    CURVE_CRVUSD_USDC_E_POOL_ARB: tokenDataByNetwork.Optimism.crvUSDC_e,
    CURVE_USDE_USDC_POOL_ARB: tokenDataByNetwork.Optimism.USDEUSDC,

    // YEARN
    YEARN_DAI_VAULT: tokenDataByNetwork.Optimism.yvDAI,
    YEARN_USDC_VAULT: tokenDataByNetwork.Optimism.yvUSDC,
    YEARN_USDC_E_VAULT: tokenDataByNetwork.Optimism.yvUSDC_e,
    YEARN_WETH_VAULT: tokenDataByNetwork.Optimism.yvWETH,
    YEARN_WBTC_VAULT: tokenDataByNetwork.Optimism.yvWBTC,
    YEARN_USDT_VAULT: tokenDataByNetwork.Optimism.yvUSDT,
    YEARN_OP_VAULT: tokenDataByNetwork.Optimism.yvOP,
    YEARN_CURVE_FRAX_VAULT: tokenDataByNetwork.Optimism.yvCurve_FRAX,
    YEARN_CURVE_STETH_VAULT: tokenDataByNetwork.Optimism.yvCurve_stETH,

    /// ERC4626
    MAKER_DSR_VAULT: tokenDataByNetwork.Optimism.sDAI,
    YIELD_ETH_VAULT: tokenDataByNetwork.Optimism.YieldETH,
    STAKED_USDE_VAULT: tokenDataByNetwork.Optimism.sUSDe,
    STAKED_USDS_VAULT: tokenDataByNetwork.Optimism.sUSDS,
    SAVINGS_CRVUSD_VAULT: tokenDataByNetwork.Optimism.scrvUSD,
    AAVE_WSTETH_VAULT: tokenDataByNetwork.Optimism.waEthLidowstETH,
    WRAPPED_USDL_VAULT: tokenDataByNetwork.Optimism.wUSDL,
    COINSHIFT_USDL_VAULT: tokenDataByNetwork.Optimism.csUSDL,

    // CONVEX
    CONVEX_BOOSTER: NOT_DEPLOYED,
    CONVEX_3CRV_POOL: NOT_DEPLOYED,
    CONVEX_FRAX_USDC_POOL: NOT_DEPLOYED,
    CONVEX_STECRV_POOL: NOT_DEPLOYED,
    CONVEX_SUSD_POOL: NOT_DEPLOYED,
    CONVEX_FRAX3CRV_POOL: NOT_DEPLOYED,
    CONVEX_LUSD3CRV_POOL: NOT_DEPLOYED,
    CONVEX_GUSD_POOL: NOT_DEPLOYED,
    CONVEX_CRVETH_POOL: NOT_DEPLOYED,
    CONVEX_CVXETH_POOL: NOT_DEPLOYED,
    CONVEX_3CRYPTO_POOL: NOT_DEPLOYED,
    CONVEX_LDOETH_POOL: NOT_DEPLOYED,
    CONVEX_CRVUSD_USDC_POOL: NOT_DEPLOYED,
    CONVEX_CRVUSD_USDT_POOL: NOT_DEPLOYED,
    CONVEX_CRVUSD_FRAX_POOL: NOT_DEPLOYED,
    CONVEX_TRI_CRV_POOL: NOT_DEPLOYED,
    CONVEX_GHO_CRVUSD_POOL: NOT_DEPLOYED,
    CONVEX_LLAMA_THENA_POOL: NOT_DEPLOYED,

    CONVEX_BOOSTER_ARB: NOT_DEPLOYED,
    CONVEX_CRVUSD_USDT_POOL_ARB: tokenDataByNetwork.Optimism.cvxcrvUSDT,

    // AURA
    AURA_BOOSTER: "0x98Ef32edd24e2c92525E59afc4475C1242a30184",
    AURA_WEETH_RETH_POOL: tokenDataByNetwork.Optimism.auraweETH_rETH_vault,
    AURA_OSETH_WETH_POOL: tokenDataByNetwork.Optimism.auraosETH_wETH_BPT_vault,
    AURA_B_RETH_STABLE_POOL:
      tokenDataByNetwork.Optimism.auraB_rETH_STABLE_vault,
    AURA_BPT_RETH_ETH_POOL: tokenDataByNetwork.Optimism.auraBPT_rETH_ETH_vault,
    AURA_BPT_WSTETH_ETH_POOL:
      tokenDataByNetwork.Optimism.auraBPT_WSTETH_ETH_vault,
    AURA_RETH_WETH_POOL_ARB:
      tokenDataByNetwork.Optimism.aurarETH_wETH_BPT_vault,
    AURA_WSTETH_WETH_POOL_ARB:
      tokenDataByNetwork.Optimism.aurawstETH_WETH_BPT_vault,
    AURA_CBETH_RETH_WSTETH_POOL_ARB:
      tokenDataByNetwork.Optimism.auracbETH_rETH_wstETH_vault,
    AURA_WSTETH_RETH_SFRXETH_POOL_ARB:
      tokenDataByNetwork.Optimism.aurawstETH_rETH_sfrxETH_vault,

    // LIDO
    LIDO_STETH_GATEWAY: NOT_DEPLOYED,
    LIDO_WSTETH: NOT_DEPLOYED,

    // BALANCER
    BALANCER_VAULT: "0xBA12222222228d8Ba445958a75a0704d566BF2C8",
    BALANCER_V3_ROUTER: NOT_DEPLOYED,

    // GEARBOX
    UNIVERSAL_ADAPTER: "0xCcCCccccCCCCcCCCCCCcCcCccCcCCCcCcccccccC",

    // AAVE
    AAVE_V2_LENDING_POOL: NOT_DEPLOYED,
    AAVE_V3_LENDING_POOL: "0x794a61358D6845594F94dc1DB02A252b5b4814aD",

    AAVE_V2_DAI_TOKEN_WRAPPER: tokenDataByNetwork.Optimism.waDAI,
    AAVE_V2_USDC_TOKEN_WRAPPER: tokenDataByNetwork.Optimism.waUSDC,
    AAVE_V2_USDT_TOKEN_WRAPPER: tokenDataByNetwork.Optimism.waUSDT,
    AAVE_V2_WETH_TOKEN_WRAPPER: tokenDataByNetwork.Optimism.waWETH,

    COMPOUND_V2_DAI_POOL: tokenDataByNetwork.Optimism.cDAI,
    COMPOUND_V2_USDC_POOL: tokenDataByNetwork.Optimism.cUSDC,
    COMPOUND_V2_USDT_POOL: tokenDataByNetwork.Optimism.cUSDT,
    COMPOUND_V2_LINK_POOL: tokenDataByNetwork.Optimism.cLINK,
    COMPOUND_V2_ETH_GATEWAY: NOT_DEPLOYED,

    FLUX_USDC_POOL: tokenDataByNetwork.Optimism.fUSDC,
    ZIRCUIT_POOL: NOT_DEPLOYED,

    // MELLOW
    MELLOW_STEAKHOUSE_VAULT: tokenDataByNetwork.Optimism.steakLRT,
    MELLOW_RE7_LABS_VAULT: tokenDataByNetwork.Optimism.Re7LRT,
    MELLOW_AMPHOR_VAULT: tokenDataByNetwork.Optimism.amphrETH,
    MELLOW_RESTAKING_VAULT: tokenDataByNetwork.Optimism.rstETH,
    MELLOW_RENZO_VAULT: tokenDataByNetwork.Optimism.pzETH,
    MELLOW_DECENTALIZED_VALIDATOR_VAULT: tokenDataByNetwork.Optimism.DVstETH,

    SKY_STAKING_REWARDS: NOT_DEPLOYED,
    DAI_USDS: NOT_DEPLOYED,
  },
  //
  //
  //
  //
  //  BASE
  //
  //
  //
  //
  Base: {
    UNISWAP_V2_ROUTER: NOT_DEPLOYED,
    UNISWAP_V3_ROUTER: NOT_DEPLOYED,
    PANCAKESWAP_V3_ROUTER: "0x1b81D678ffb9C0263b24A97847620C99d213eB14",
    SUSHISWAP_ROUTER: NOT_DEPLOYED,
    FRAXSWAP_ROUTER: NOT_DEPLOYED,
    VELODROME_V2_ROUTER: NOT_DEPLOYED,
    VELODROME_CL_ROUTER: NOT_DEPLOYED,
    EQUALIZER_ROUTER: NOT_DEPLOYED,
    SHADOW_ROUTER: NOT_DEPLOYED,
    CAMELOT_V3_ROUTER: NOT_DEPLOYED,
    PENDLE_ROUTER: NOT_DEPLOYED,

    // CURVE
    CURVE_3CRV_POOL_OP: NOT_DEPLOYED,
    CURVE_3CRV_POOL: NOT_DEPLOYED,
    CURVE_FRAX_USDC_POOL: NOT_DEPLOYED,
    CURVE_STETH_GATEWAY: NOT_DEPLOYED,
    CURVE_FRAX_POOL: tokenDataByNetwork.Base.FRAX3CRV,
    CURVE_LUSD_POOL: tokenDataByNetwork.Base.LUSD3CRV,
    CURVE_SUSD_POOL: NOT_DEPLOYED,
    CURVE_SUSD_DEPOSIT: NOT_DEPLOYED,
    CURVE_GUSD_POOL: NOT_DEPLOYED,
    CURVE_CRVETH_POOL: NOT_DEPLOYED,
    CURVE_CVXETH_POOL: NOT_DEPLOYED,
    CURVE_3CRYPTO_POOL: NOT_DEPLOYED,
    CURVE_LDOETH_POOL: NOT_DEPLOYED,
    CURVE_USDE_USDC_POOL: tokenDataByNetwork.Base.USDeUSDC,
    CURVE_FRAX_USDE_POOL: tokenDataByNetwork.Base.FRAXUSDe,
    CURVE_USDE_CRVUSD_POOL: tokenDataByNetwork.Base.USDecrvUSD,
    CURVE_FRAX_SDAI_POOL: tokenDataByNetwork.Base.FRAXsDAI,
    CURVE_DOLA_SUSDE_POOL: tokenDataByNetwork.Base.DOLAsUSDe,
    CURVE_DOLA_FRAXBP_POOL: tokenDataByNetwork.Base.DOLAFRAXBP3CRV_f,
    CURVE_DOLA_CRVUSD_POOL: tokenDataByNetwork.Base.crvUSDDOLA_f,
    CURVE_USDE_DAI_POOL: tokenDataByNetwork.Base.USDeDAI,
    CURVE_SDAI_SUSDE_POOL: tokenDataByNetwork.Base.MtEthena,
    CURVE_PUFETH_WSTETH_POOL: tokenDataByNetwork.Base.pufETHwstE,
    CURVE_GHO_CRVUSD_POOL: tokenDataByNetwork.Base.GHOcrvUSD,
    CURVE_ETH_WSTETH_GATEWAY_OP: NOT_DEPLOYED,
    CURVE_EZETH_ETH_POOL: NOT_DEPLOYED,
    CURVE_EZPZ_ETH_POOL: NOT_DEPLOYED,
    CURVE_LBTC_WBTC_POOL: NOT_DEPLOYED,
    CURVE_EBTC_WBTC_POOL: NOT_DEPLOYED,
    CURVE_PUMPBTC_WBTC_POOL: NOT_DEPLOYED,
    CURVE_TRIBTC_POOL: NOT_DEPLOYED,
    CURVE_tBTC_WBTC_POOL: NOT_DEPLOYED,
    CURVE_tETH_wstETH_POOL: NOT_DEPLOYED,
    CURVE_tETH_weETH_POOL: NOT_DEPLOYED,
    CURVE_pzETH_stETH_POOL: NOT_DEPLOYED,
    CURVE_USDL_USDC_POOL: NOT_DEPLOYED,

    CURVE_GEAR_POOL: NOT_DEPLOYED,

    CURVE_CRVUSD_USDC_POOL: tokenDataByNetwork.Base.crvUSDUSDC,
    CURVE_CRVUSD_USDT_POOL: tokenDataByNetwork.Base.crvUSDUSDT,
    CURVE_CRVUSD_FRAX_POOL: tokenDataByNetwork.Base.crvUSDFRAX,
    CURVE_TRI_CRV_POOL: tokenDataByNetwork.Base.crvUSDETHCRV,
    CURVE_CRVUSD_SUSDE_POOL: tokenDataByNetwork.Base.crvUsUSDe,
    CURVE_LLAMA_THENA_POOL: tokenDataByNetwork.Base.llamathena,

    CURVE_RETH_ETH_POOL: NOT_DEPLOYED,

    CURVE_2CRV_POOL_ARB: tokenDataByNetwork.Base["2CRV"],
    CURVE_TRICRYPTO_CRVUSD_POOL_ARB: tokenDataByNetwork.Base["3c-crvUSD"],
    CURVE_CRVUSD_USDC_POOL_ARB: tokenDataByNetwork.Base.crvUSDC,
    CURVE_CRVUSD_USDT_POOL_ARB: tokenDataByNetwork.Base.crvUSDT,
    CURVE_CRVUSD_USDC_E_POOL_ARB: tokenDataByNetwork.Base.crvUSDC_e,
    CURVE_USDE_USDC_POOL_ARB: tokenDataByNetwork.Base.USDEUSDC,

    // YEARN
    YEARN_DAI_VAULT: tokenDataByNetwork.Base.yvDAI,
    YEARN_USDC_VAULT: tokenDataByNetwork.Base.yvUSDC,
    YEARN_USDC_E_VAULT: tokenDataByNetwork.Base.yvUSDC_e,
    YEARN_WETH_VAULT: tokenDataByNetwork.Base.yvWETH,
    YEARN_WBTC_VAULT: tokenDataByNetwork.Base.yvWBTC,
    YEARN_USDT_VAULT: tokenDataByNetwork.Base.yvUSDT,
    YEARN_OP_VAULT: tokenDataByNetwork.Base.yvOP,
    YEARN_CURVE_FRAX_VAULT: tokenDataByNetwork.Base.yvCurve_FRAX,
    YEARN_CURVE_STETH_VAULT: tokenDataByNetwork.Base.yvCurve_stETH,

    /// ERC4626
    MAKER_DSR_VAULT: tokenDataByNetwork.Base.sDAI,
    YIELD_ETH_VAULT: tokenDataByNetwork.Base.YieldETH,
    STAKED_USDE_VAULT: tokenDataByNetwork.Base.sUSDe,
    STAKED_USDS_VAULT: tokenDataByNetwork.Base.sUSDS,
    SAVINGS_CRVUSD_VAULT: tokenDataByNetwork.Base.scrvUSD,
    AAVE_WSTETH_VAULT: tokenDataByNetwork.Base.waEthLidowstETH,
    WRAPPED_USDL_VAULT: tokenDataByNetwork.Base.wUSDL,
    COINSHIFT_USDL_VAULT: tokenDataByNetwork.Base.csUSDL,

    // CONVEX
    CONVEX_BOOSTER: NOT_DEPLOYED,
    CONVEX_3CRV_POOL: NOT_DEPLOYED,
    CONVEX_FRAX_USDC_POOL: NOT_DEPLOYED,
    CONVEX_STECRV_POOL: NOT_DEPLOYED,
    CONVEX_SUSD_POOL: NOT_DEPLOYED,
    CONVEX_FRAX3CRV_POOL: NOT_DEPLOYED,
    CONVEX_LUSD3CRV_POOL: NOT_DEPLOYED,
    CONVEX_GUSD_POOL: NOT_DEPLOYED,
    CONVEX_CRVETH_POOL: NOT_DEPLOYED,
    CONVEX_CVXETH_POOL: NOT_DEPLOYED,
    CONVEX_3CRYPTO_POOL: NOT_DEPLOYED,
    CONVEX_LDOETH_POOL: NOT_DEPLOYED,
    CONVEX_CRVUSD_USDC_POOL: NOT_DEPLOYED,
    CONVEX_CRVUSD_USDT_POOL: NOT_DEPLOYED,
    CONVEX_CRVUSD_FRAX_POOL: NOT_DEPLOYED,
    CONVEX_TRI_CRV_POOL: NOT_DEPLOYED,
    CONVEX_GHO_CRVUSD_POOL: NOT_DEPLOYED,
    CONVEX_LLAMA_THENA_POOL: NOT_DEPLOYED,

    CONVEX_BOOSTER_ARB: NOT_DEPLOYED,
    CONVEX_CRVUSD_USDT_POOL_ARB: tokenDataByNetwork.Base.cvxcrvUSDT,

    // AURA
    AURA_BOOSTER: NOT_DEPLOYED,
    AURA_WEETH_RETH_POOL: tokenDataByNetwork.Base.auraweETH_rETH_vault,
    AURA_OSETH_WETH_POOL: tokenDataByNetwork.Base.auraosETH_wETH_BPT_vault,
    AURA_B_RETH_STABLE_POOL: tokenDataByNetwork.Base.auraB_rETH_STABLE_vault,
    AURA_BPT_RETH_ETH_POOL: tokenDataByNetwork.Base.auraBPT_rETH_ETH_vault,
    AURA_BPT_WSTETH_ETH_POOL: tokenDataByNetwork.Base.auraBPT_WSTETH_ETH_vault,
    AURA_RETH_WETH_POOL_ARB: tokenDataByNetwork.Base.aurarETH_wETH_BPT_vault,
    AURA_WSTETH_WETH_POOL_ARB:
      tokenDataByNetwork.Base.aurawstETH_WETH_BPT_vault,
    AURA_CBETH_RETH_WSTETH_POOL_ARB:
      tokenDataByNetwork.Base.auracbETH_rETH_wstETH_vault,
    AURA_WSTETH_RETH_SFRXETH_POOL_ARB:
      tokenDataByNetwork.Base.aurawstETH_rETH_sfrxETH_vault,

    // LIDO
    LIDO_STETH_GATEWAY: NOT_DEPLOYED,
    LIDO_WSTETH: NOT_DEPLOYED,

    // BALANCER
    BALANCER_VAULT: NOT_DEPLOYED,
    BALANCER_V3_ROUTER: NOT_DEPLOYED,

    // GEARBOX
    UNIVERSAL_ADAPTER: NOT_DEPLOYED,

    // AAVE
    AAVE_V2_LENDING_POOL: NOT_DEPLOYED,
    AAVE_V3_LENDING_POOL: "0xA238Dd80C259a72e81d7e4664a9801593F98d1c5",

    AAVE_V2_DAI_TOKEN_WRAPPER: tokenDataByNetwork.Base.waDAI,
    AAVE_V2_USDC_TOKEN_WRAPPER: tokenDataByNetwork.Base.waUSDC,
    AAVE_V2_USDT_TOKEN_WRAPPER: tokenDataByNetwork.Base.waUSDT,
    AAVE_V2_WETH_TOKEN_WRAPPER: tokenDataByNetwork.Base.waWETH,

    COMPOUND_V2_DAI_POOL: tokenDataByNetwork.Base.cDAI,
    COMPOUND_V2_USDC_POOL: tokenDataByNetwork.Base.cUSDC,
    COMPOUND_V2_USDT_POOL: tokenDataByNetwork.Base.cUSDT,
    COMPOUND_V2_LINK_POOL: tokenDataByNetwork.Base.cLINK,
    COMPOUND_V2_ETH_GATEWAY: NOT_DEPLOYED,

    FLUX_USDC_POOL: tokenDataByNetwork.Base.fUSDC,
    CURVE_GHO_USDE_POOL: NOT_DEPLOYED,
    ZIRCUIT_POOL: NOT_DEPLOYED,

    // MELLOW
    MELLOW_STEAKHOUSE_VAULT: tokenDataByNetwork.Base.steakLRT,
    MELLOW_RE7_LABS_VAULT: tokenDataByNetwork.Base.Re7LRT,
    MELLOW_AMPHOR_VAULT: tokenDataByNetwork.Base.amphrETH,
    MELLOW_RESTAKING_VAULT: tokenDataByNetwork.Base.rstETH,
    MELLOW_RENZO_VAULT: tokenDataByNetwork.Base.pzETH,
    MELLOW_DECENTALIZED_VALIDATOR_VAULT: tokenDataByNetwork.Base.DVstETH,

    SKY_STAKING_REWARDS: NOT_DEPLOYED,
    DAI_USDS: NOT_DEPLOYED,
  },
  //
  //
  //
  //
  //  SONIC
  //
  //
  //
  //
  Sonic: {
    UNISWAP_V2_ROUTER: NOT_DEPLOYED,
    UNISWAP_V3_ROUTER: NOT_DEPLOYED,
    PANCAKESWAP_V3_ROUTER: NOT_DEPLOYED,
    SUSHISWAP_ROUTER: NOT_DEPLOYED,
    FRAXSWAP_ROUTER: NOT_DEPLOYED,
    VELODROME_V2_ROUTER: NOT_DEPLOYED,
    VELODROME_CL_ROUTER: NOT_DEPLOYED,
    EQUALIZER_ROUTER: "0xcC6169aA1E879d3a4227536671F85afdb2d23fAD",
    SHADOW_ROUTER: "0x5543c6176FEb9B4b179078205d7C29EEa2e2d695",

    CAMELOT_V3_ROUTER: NOT_DEPLOYED,
    PENDLE_ROUTER: NOT_DEPLOYED,

    // CURVE
    CURVE_3CRV_POOL_OP: NOT_DEPLOYED,
    CURVE_3CRV_POOL: NOT_DEPLOYED,
    CURVE_FRAX_USDC_POOL: NOT_DEPLOYED,
    CURVE_STETH_GATEWAY: NOT_DEPLOYED,
    CURVE_FRAX_POOL: NOT_DEPLOYED,
    CURVE_LUSD_POOL: NOT_DEPLOYED,
    CURVE_SUSD_POOL: NOT_DEPLOYED,
    CURVE_SUSD_DEPOSIT: NOT_DEPLOYED,
    CURVE_GUSD_POOL: NOT_DEPLOYED,
    CURVE_CRVETH_POOL: NOT_DEPLOYED,
    CURVE_CVXETH_POOL: NOT_DEPLOYED,
    CURVE_3CRYPTO_POOL: NOT_DEPLOYED,
    CURVE_LDOETH_POOL: NOT_DEPLOYED,
    CURVE_USDE_USDC_POOL: NOT_DEPLOYED,
    CURVE_FRAX_USDE_POOL: NOT_DEPLOYED,
    CURVE_USDE_CRVUSD_POOL: NOT_DEPLOYED,
    CURVE_FRAX_SDAI_POOL: NOT_DEPLOYED,
    CURVE_DOLA_SUSDE_POOL: NOT_DEPLOYED,
    CURVE_DOLA_FRAXBP_POOL: NOT_DEPLOYED,
    CURVE_DOLA_CRVUSD_POOL: NOT_DEPLOYED,
    CURVE_USDE_DAI_POOL: NOT_DEPLOYED,
    CURVE_SDAI_SUSDE_POOL: NOT_DEPLOYED,
    CURVE_GHO_USDE_POOL: NOT_DEPLOYED,
    CURVE_PUFETH_WSTETH_POOL: NOT_DEPLOYED,
    CURVE_GHO_CRVUSD_POOL: NOT_DEPLOYED,
    CURVE_ETH_WSTETH_GATEWAY_OP: NOT_DEPLOYED,
    CURVE_EZETH_ETH_POOL: NOT_DEPLOYED,
    CURVE_EZPZ_ETH_POOL: NOT_DEPLOYED,
    CURVE_LBTC_WBTC_POOL: NOT_DEPLOYED,
    CURVE_EBTC_WBTC_POOL: NOT_DEPLOYED,
    CURVE_PUMPBTC_WBTC_POOL: NOT_DEPLOYED,
    CURVE_TRIBTC_POOL: NOT_DEPLOYED,
    CURVE_tBTC_WBTC_POOL: NOT_DEPLOYED,
    CURVE_tETH_wstETH_POOL: NOT_DEPLOYED,
    CURVE_tETH_weETH_POOL: NOT_DEPLOYED,
    CURVE_pzETH_stETH_POOL: NOT_DEPLOYED,
    CURVE_USDL_USDC_POOL: NOT_DEPLOYED,

    CURVE_GEAR_POOL: NOT_DEPLOYED,

    CURVE_CRVUSD_USDC_POOL: NOT_DEPLOYED,
    CURVE_CRVUSD_USDT_POOL: NOT_DEPLOYED,
    CURVE_CRVUSD_FRAX_POOL: NOT_DEPLOYED,
    CURVE_TRI_CRV_POOL: NOT_DEPLOYED,
    CURVE_CRVUSD_SUSDE_POOL: NOT_DEPLOYED,
    CURVE_LLAMA_THENA_POOL: NOT_DEPLOYED,

    CURVE_RETH_ETH_POOL: NOT_DEPLOYED,

    CURVE_2CRV_POOL_ARB: NOT_DEPLOYED,
    CURVE_TRICRYPTO_CRVUSD_POOL_ARB: NOT_DEPLOYED,
    CURVE_CRVUSD_USDC_POOL_ARB: NOT_DEPLOYED,
    CURVE_CRVUSD_USDT_POOL_ARB: NOT_DEPLOYED,
    CURVE_CRVUSD_USDC_E_POOL_ARB: NOT_DEPLOYED,
    CURVE_USDE_USDC_POOL_ARB: NOT_DEPLOYED,

    // YEARN
    YEARN_DAI_VAULT: NOT_DEPLOYED,
    YEARN_USDC_VAULT: NOT_DEPLOYED,
    YEARN_USDC_E_VAULT: NOT_DEPLOYED,
    YEARN_WETH_VAULT: NOT_DEPLOYED,
    YEARN_WBTC_VAULT: NOT_DEPLOYED,
    YEARN_USDT_VAULT: NOT_DEPLOYED,
    YEARN_OP_VAULT: NOT_DEPLOYED,
    YEARN_CURVE_FRAX_VAULT: NOT_DEPLOYED,
    YEARN_CURVE_STETH_VAULT: NOT_DEPLOYED,

    /// ERC4626
    MAKER_DSR_VAULT: NOT_DEPLOYED,
    YIELD_ETH_VAULT: NOT_DEPLOYED,
    STAKED_USDE_VAULT: NOT_DEPLOYED,
    STAKED_USDS_VAULT: NOT_DEPLOYED,
    SAVINGS_CRVUSD_VAULT: NOT_DEPLOYED,
    AAVE_WSTETH_VAULT: NOT_DEPLOYED,
    WRAPPED_USDL_VAULT: NOT_DEPLOYED,
    COINSHIFT_USDL_VAULT: NOT_DEPLOYED,

    // CONVEX
    CONVEX_BOOSTER: NOT_DEPLOYED,
    CONVEX_3CRV_POOL: NOT_DEPLOYED,
    CONVEX_FRAX_USDC_POOL: NOT_DEPLOYED,
    CONVEX_STECRV_POOL: NOT_DEPLOYED,
    CONVEX_SUSD_POOL: NOT_DEPLOYED,
    CONVEX_FRAX3CRV_POOL: NOT_DEPLOYED,
    CONVEX_LUSD3CRV_POOL: NOT_DEPLOYED,
    CONVEX_GUSD_POOL: NOT_DEPLOYED,
    CONVEX_CRVETH_POOL: NOT_DEPLOYED,
    CONVEX_CVXETH_POOL: NOT_DEPLOYED,
    CONVEX_3CRYPTO_POOL: NOT_DEPLOYED,
    CONVEX_LDOETH_POOL: NOT_DEPLOYED,
    CONVEX_CRVUSD_USDC_POOL: NOT_DEPLOYED,
    CONVEX_CRVUSD_USDT_POOL: NOT_DEPLOYED,
    CONVEX_CRVUSD_FRAX_POOL: NOT_DEPLOYED,
    CONVEX_TRI_CRV_POOL: NOT_DEPLOYED,
    CONVEX_GHO_CRVUSD_POOL: NOT_DEPLOYED,
    CONVEX_LLAMA_THENA_POOL: NOT_DEPLOYED,

    CONVEX_BOOSTER_ARB: NOT_DEPLOYED,
    CONVEX_CRVUSD_USDT_POOL_ARB: NOT_DEPLOYED,

    // AURA
    AURA_BOOSTER: NOT_DEPLOYED,
    AURA_WEETH_RETH_POOL: NOT_DEPLOYED,
    AURA_OSETH_WETH_POOL: NOT_DEPLOYED,
    AURA_B_RETH_STABLE_POOL: NOT_DEPLOYED,
    AURA_BPT_RETH_ETH_POOL: NOT_DEPLOYED,
    AURA_BPT_WSTETH_ETH_POOL: NOT_DEPLOYED,
    AURA_RETH_WETH_POOL_ARB: NOT_DEPLOYED,
    AURA_WSTETH_WETH_POOL_ARB: NOT_DEPLOYED,
    AURA_CBETH_RETH_WSTETH_POOL_ARB: NOT_DEPLOYED,
    AURA_WSTETH_RETH_SFRXETH_POOL_ARB: NOT_DEPLOYED,

    // LIDO
    LIDO_STETH_GATEWAY: NOT_DEPLOYED,
    LIDO_WSTETH: NOT_DEPLOYED,

    // BALANCER
    BALANCER_VAULT: "0xBA12222222228d8Ba445958a75a0704d566BF2C8",
    BALANCER_V3_ROUTER: NOT_DEPLOYED,

    // GEARBOX
    UNIVERSAL_ADAPTER: NOT_DEPLOYED,

    // AAVE
    AAVE_V2_LENDING_POOL: NOT_DEPLOYED,
    AAVE_V3_LENDING_POOL: NOT_DEPLOYED,

    AAVE_V2_DAI_TOKEN_WRAPPER: NOT_DEPLOYED,
    AAVE_V2_USDC_TOKEN_WRAPPER: NOT_DEPLOYED,
    AAVE_V2_USDT_TOKEN_WRAPPER: NOT_DEPLOYED,
    AAVE_V2_WETH_TOKEN_WRAPPER: NOT_DEPLOYED,

    COMPOUND_V2_DAI_POOL: NOT_DEPLOYED,
    COMPOUND_V2_USDC_POOL: NOT_DEPLOYED,
    COMPOUND_V2_USDT_POOL: NOT_DEPLOYED,
    COMPOUND_V2_LINK_POOL: NOT_DEPLOYED,
    COMPOUND_V2_ETH_GATEWAY: NOT_DEPLOYED,

    FLUX_USDC_POOL: NOT_DEPLOYED,
    ZIRCUIT_POOL: NOT_DEPLOYED,

    // MELLOW
    MELLOW_STEAKHOUSE_VAULT: NOT_DEPLOYED,
    MELLOW_RE7_LABS_VAULT: NOT_DEPLOYED,
    MELLOW_AMPHOR_VAULT: NOT_DEPLOYED,
    MELLOW_RESTAKING_VAULT: NOT_DEPLOYED,
    MELLOW_RENZO_VAULT: NOT_DEPLOYED,
    MELLOW_DECENTALIZED_VALIDATOR_VAULT: NOT_DEPLOYED,

    SKY_STAKING_REWARDS: NOT_DEPLOYED,
    DAI_USDS: NOT_DEPLOYED,
  },
};

interface BaseContractParams {
  name: string;
}

type CurveParams = {
  type:
    | AdapterInterface.CURVE_V1_2ASSETS
    | AdapterInterface.CURVE_V1_3ASSETS
    | AdapterInterface.CURVE_V1_4ASSETS
    | AdapterInterface.CURVE_V1_WRAPPER
    | AdapterInterface.CURVE_STABLE_NG;
  version: number;
  lpToken: CurveLPToken;
  tokens: Array<NormalToken | CurveLPToken | ERC4626LPToken>;
  underlyings?: Array<NormalToken>;
  wrapper?: CurvePoolContract;
} & BaseContractParams;

export type CurveSteCRVPoolParams = {
  type: AdapterInterface.CURVE_V1_STECRV_POOL;
  version: number;

  pool: Record<NetworkType, Address>;
  tokens: ["WETH", "STETH"] | ["WETH", "wstETH"];
  lpToken: "steCRV" | "wstETHCRV";
} & BaseContractParams;

export const contractParams: Record<
  CurvePoolContract,
  CurveParams | CurveSteCRVPoolParams
> = {
  CURVE_3CRV_POOL: {
    name: "Curve 3Pool",

    type: AdapterInterface.CURVE_V1_3ASSETS,
    version: 10,
    lpToken: "3Crv",
    tokens: ["DAI", "USDC", "USDT"],
  },
  CURVE_FRAX_USDC_POOL: {
    name: "Curve crvFRAX",

    type: AdapterInterface.CURVE_V1_2ASSETS,
    version: 10,
    lpToken: "crvFRAX",
    tokens: ["FRAX", "USDC"],
  },
  CURVE_STETH_GATEWAY: {
    name: "Curve stETH",

    type: AdapterInterface.CURVE_V1_STECRV_POOL,
    version: 10,
    pool: {
      Mainnet: "0xDC24316b9AE028F1497c275EB9192a3Ea0f67022",
      Arbitrum: NOT_DEPLOYED, // CURVE_STECRV_POOL
      Optimism: NOT_DEPLOYED,
      Base: NOT_DEPLOYED,
      Sonic: NOT_DEPLOYED,
      MegaETH: NOT_DEPLOYED,
    },
    tokens: ["WETH", "STETH"],
    lpToken: "steCRV",
  },
  CURVE_ETH_WSTETH_GATEWAY_OP: {
    name: "Curve wstETH Gateway (Optimism)",

    type: AdapterInterface.CURVE_V1_STECRV_POOL,
    version: 10,
    pool: {
      Mainnet: NOT_DEPLOYED,
      Arbitrum: NOT_DEPLOYED,
      Optimism: "0xb90b9b1f91a01ea22a182cd84c1e22222e39b415",
      Base: NOT_DEPLOYED,
      Sonic: NOT_DEPLOYED,
      MegaETH: NOT_DEPLOYED,
    },
    tokens: ["WETH", "wstETH"],
    lpToken: "wstETHCRV",
  },
  CURVE_FRAX_POOL: {
    name: "Curve FRAX",

    type: AdapterInterface.CURVE_V1_2ASSETS,
    version: 10,
    lpToken: "FRAX3CRV",
    tokens: ["FRAX", "3Crv"],
    underlyings: ["FRAX", "DAI", "USDC", "USDT"],
  },
  CURVE_LUSD_POOL: {
    name: "Curve LUSD",

    type: AdapterInterface.CURVE_V1_2ASSETS,
    version: 10,
    lpToken: "LUSD3CRV",
    tokens: ["LUSD", "3Crv"],
    underlyings: ["LUSD", "DAI", "USDC", "USDT"],
  },
  CURVE_SUSD_POOL: {
    name: "Curve SUSD",

    type: AdapterInterface.CURVE_V1_4ASSETS,
    version: 10,
    lpToken: "crvPlain3andSUSD",
    tokens: ["DAI", "USDC", "USDT", "sUSD"],
    wrapper: "CURVE_SUSD_DEPOSIT",
  },
  CURVE_SUSD_DEPOSIT: {
    name: "Curve SUSD",

    type: AdapterInterface.CURVE_V1_WRAPPER,
    version: 10,
    lpToken: "crvPlain3andSUSD",
    tokens: ["DAI", "USDC", "USDT", "sUSD"],
  },
  CURVE_GUSD_POOL: {
    name: "Curve GUSD",

    type: AdapterInterface.CURVE_V1_2ASSETS,
    version: 10,
    lpToken: "gusd3CRV",
    tokens: ["GUSD", "3Crv"],
    underlyings: ["GUSD", "DAI", "USDC", "USDT"],
  },

  CURVE_CRVETH_POOL: {
    name: "Curve CRVETH",

    type: AdapterInterface.CURVE_V1_2ASSETS,
    version: 20,
    lpToken: "crvCRVETH",
    tokens: ["WETH", "CRV"],
  },
  CURVE_CVXETH_POOL: {
    name: "Curve CVXETH",

    type: AdapterInterface.CURVE_V1_2ASSETS,
    version: 20,
    lpToken: "crvCVXETH",
    tokens: ["WETH", "CVX"],
  },
  CURVE_3CRYPTO_POOL: {
    name: "Curve 3Crypto",

    type: AdapterInterface.CURVE_V1_3ASSETS,
    version: 20,
    lpToken: "crvUSDTWBTCWETH",
    tokens: ["USDT", "WBTC", "WETH"],
  },
  CURVE_LDOETH_POOL: {
    name: "Curve LDOETH",

    type: AdapterInterface.CURVE_V1_2ASSETS,
    version: 20,
    lpToken: "LDOETH",
    tokens: ["WETH", "LDO"],
  },

  CURVE_CRVUSD_USDC_POOL: {
    name: "Curve crvUSDUSDC",

    version: 10,
    type: AdapterInterface.CURVE_V1_2ASSETS,
    lpToken: "crvUSDUSDC",
    tokens: ["crvUSD", "USDC"],
  },

  CURVE_CRVUSD_USDT_POOL: {
    name: "Curve crvUSDUSDT",

    version: 10,
    type: AdapterInterface.CURVE_V1_2ASSETS,
    lpToken: "crvUSDUSDT",
    tokens: ["crvUSD", "USDT"],
  },
  CURVE_CRVUSD_SUSDE_POOL: {
    name: "Curve crvUsUSDe",

    version: 10,
    type: AdapterInterface.CURVE_V1_2ASSETS,
    lpToken: "crvUsUSDe",
    tokens: ["crvUSD", "sUSDe"],
  },
  CURVE_LLAMA_THENA_POOL: {
    name: "Curve llamathena",

    version: 10,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "llamathena",
    tokens: ["scrvUSD", "sUSDe"],
  },

  CURVE_CRVUSD_FRAX_POOL: {
    name: "Curve crvUSDFRAX",

    version: 10,
    type: AdapterInterface.CURVE_V1_2ASSETS,
    lpToken: "crvUSDFRAX",
    tokens: ["crvUSD", "FRAX"],
  },

  CURVE_TRI_CRV_POOL: {
    name: "Curve crvUSDUSDC",

    version: 20,
    type: AdapterInterface.CURVE_V1_3ASSETS,
    lpToken: "crvUSDETHCRV",
    tokens: ["crvUSD", "WETH", "CRV"],
  },

  CURVE_RETH_ETH_POOL: {
    name: "Curve rETH",

    version: 20,
    type: AdapterInterface.CURVE_V1_2ASSETS,
    lpToken: "rETH_f",
    tokens: ["WETH", "rETH"],
  },

  CURVE_DOLA_FRAXBP_POOL: {
    name: "Curve DOLAFRAXBP3CRV",

    version: 20,
    type: AdapterInterface.CURVE_V1_2ASSETS,
    lpToken: "DOLAFRAXBP3CRV_f",
    tokens: ["DOLA", "crvFRAX"],
  },

  CURVE_DOLA_CRVUSD_POOL: {
    name: "Curve crvUSDDOLA",

    version: 20,
    type: AdapterInterface.CURVE_V1_2ASSETS,
    lpToken: "crvUSDDOLA_f",
    tokens: ["DOLA", "crvUSD"],
  },

  CURVE_USDE_USDC_POOL: {
    name: "Curve USDeUSDC",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "USDeUSDC",
    tokens: ["USDe", "USDC"],
  },

  CURVE_FRAX_USDE_POOL: {
    name: "Curve FRAXUSDe",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "FRAXUSDe",
    tokens: ["FRAX", "USDe"],
  },

  CURVE_USDE_CRVUSD_POOL: {
    name: "Curve USDecrvUSD",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "USDecrvUSD",
    tokens: ["USDe", "crvUSD"],
  },

  CURVE_USDE_DAI_POOL: {
    name: "Curve USDeDAI",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "USDeDAI",
    tokens: ["USDe", "DAI"],
  },

  CURVE_SDAI_SUSDE_POOL: {
    name: "Curve MtEthena",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "MtEthena",
    tokens: ["sDAI", "sUSDe"],
  },

  CURVE_GHO_USDE_POOL: {
    name: "Curve GHOUSDe",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "GHOUSDe",
    tokens: ["GHO", "USDe"],
  },

  CURVE_FRAX_SDAI_POOL: {
    name: "Curve FRAXsDAI",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "FRAXsDAI",
    tokens: ["FRAX", "sDAI"],
  },
  CURVE_DOLA_SUSDE_POOL: {
    name: "Curve DOLAsUSDe",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "DOLAsUSDe",
    tokens: ["DOLA", "sUSDe"],
  },

  CURVE_PUFETH_WSTETH_POOL: {
    name: "Curve pufETH/wstETH",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "pufETHwstE",
    tokens: ["pufETH", "wstETH"],
  },

  CURVE_GHO_CRVUSD_POOL: {
    name: "Curve GHO/crvUSD Pool",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "GHOcrvUSD",
    tokens: ["GHO", "crvUSD"],
  },

  CURVE_EZETH_ETH_POOL: {
    name: "Curve ezETH/WETH Pool",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "ezETHWETH",
    tokens: ["ezETH", "WETH"],
  },
  CURVE_EZPZ_ETH_POOL: {
    name: "Curve ezpz ETH Pool",

    version: 20,
    type: AdapterInterface.CURVE_V1_2ASSETS,
    lpToken: "ezpzETH",
    tokens: ["ezETH", "pzETH"],
  },
  CURVE_LBTC_WBTC_POOL: {
    name: "Curve LBTC/WBTC Pool",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "LBTCWBTC",
    tokens: ["LBTC", "WBTC"],
  },

  CURVE_EBTC_WBTC_POOL: {
    name: "Curve eBTC/WBTC LP",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "eBTCWBTC",
    tokens: ["eBTC", "WBTC"],
  },
  CURVE_PUMPBTC_WBTC_POOL: {
    name: "Curve pumpBTC/WBTC LP",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "pumpBTCWBTC",
    tokens: ["pumpBTC", "WBTC"],
  },
  CURVE_TRIBTC_POOL: {
    name: "Curve Tri BTC-Fi LP",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "TriBTC",
    tokens: ["eBTC", "LBTC", "WBTC"],
  },
  CURVE_tBTC_WBTC_POOL: {
    name: "Curve tBTC/WBTC LP",

    version: 20,
    type: AdapterInterface.CURVE_V1_2ASSETS,
    lpToken: "2BTC-f",
    tokens: ["WBTC", "tBTC"],
  },
  CURVE_tETH_wstETH_POOL: {
    name: "Curve tETH/wstETH LP",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "tETHwstETH",
    tokens: ["tETH", "wstETH"],
  },
  CURVE_tETH_weETH_POOL: {
    name: "Curve tETH/weETH LP",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "tETHweETH",
    tokens: ["tETH", "weETH"],
  },
  CURVE_pzETH_stETH_POOL: {
    name: "Curve pzETH/wstETH LP",

    version: 20,
    type: AdapterInterface.CURVE_V1_2ASSETS,
    lpToken: "pzETHstETH",
    tokens: ["pzETH", "wstETH"],
  },

  CURVE_USDL_USDC_POOL: {
    name: "Curve pzETH/wstETH LP",
    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "USDLUSDC",
    tokens: ["USDL", "USDC"],
  },

  CURVE_2CRV_POOL_ARB: {
    name: "Curve USDC/USDT Pool (Arbitrum)",

    version: 20,
    type: AdapterInterface.CURVE_V1_2ASSETS,
    lpToken: "2CRV",
    tokens: ["USDC_e", "USDT"],
  },

  CURVE_TRICRYPTO_CRVUSD_POOL_ARB: {
    name: "Curve Tricrypto-crvUSD Pool (Arbitrum)",

    version: 20,
    type: AdapterInterface.CURVE_V1_3ASSETS,
    lpToken: "3c-crvUSD",
    tokens: ["crvUSD", "WBTC", "WETH"],
  },

  CURVE_CRVUSD_USDC_POOL_ARB: {
    name: "Curve crvUSD/USDC Pool (Arbitrum)",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "crvUSDC",
    tokens: ["crvUSD", "USDC"],
  },

  CURVE_CRVUSD_USDC_E_POOL_ARB: {
    name: "Curve crvUSD/USDC.e Pool (Arbitrum)",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "crvUSDC_e",
    tokens: ["crvUSD", "USDC_e"],
  },

  CURVE_CRVUSD_USDT_POOL_ARB: {
    name: "Curve crvUSD/USDT Pool (Arbitrum)",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "crvUSDT",
    tokens: ["crvUSD", "USDT"],
  },

  CURVE_USDE_USDC_POOL_ARB: {
    name: "Curve USDe/USDC Pool (Arbitrum)",

    version: 20,
    type: AdapterInterface.CURVE_STABLE_NG,
    lpToken: "USDEUSDC",
    tokens: ["USDC", "USDe"],
  },

  CURVE_3CRV_POOL_OP: {
    name: "Curve 3CRV Pool (Optimism)",

    version: 20,
    type: AdapterInterface.CURVE_V1_3ASSETS,
    lpToken: "3CRV",
    tokens: ["DAI", "USDC_e", "USDT"],
  },
};
