"use strict";
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
Object.defineProperty(exports, "__esModule", { value: true });
exports.IUniswapV3AdapterExceptions__factory = void 0;
var ethers_1 = require("ethers");
var _abi = [
    {
        inputs: [],
        name: "IncorrectPathLengthException",
        type: "error",
    },
];
var IUniswapV3AdapterExceptions__factory = /** @class */ (function () {
    function IUniswapV3AdapterExceptions__factory() {
    }
    IUniswapV3AdapterExceptions__factory.createInterface = function () {
        return new ethers_1.utils.Interface(_abi);
    };
    IUniswapV3AdapterExceptions__factory.connect = function (address, signerOrProvider) {
        return new ethers_1.Contract(address, _abi, signerOrProvider);
    };
    IUniswapV3AdapterExceptions__factory.abi = _abi;
    return IUniswapV3AdapterExceptions__factory;
}());
exports.IUniswapV3AdapterExceptions__factory = IUniswapV3AdapterExceptions__factory;
