export const iAddressProviderV300Abi = [
  {
    type: "function",
    name: "addresses",
    inputs: [
      { name: "key", type: "bytes32", internalType: "bytes32" },
      { name: "_version", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getAddressOrRevert",
    inputs: [
      { name: "key", type: "bytes32", internalType: "bytes32" },
      { name: "_version", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "result", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setAddress",
    inputs: [
      { name: "key", type: "bytes32", internalType: "bytes32" },
      { name: "value", type: "address", internalType: "address" },
      { name: "saveVersion", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "version",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "SetAddress",
    inputs: [
      { name: "key", type: "bytes32", indexed: true, internalType: "bytes32" },
      {
        name: "value",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "version",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
] as const;

export const iCreditConfiguratorV300Abi = [
  {
    type: "function",
    name: "addCollateralToken",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "liquidationThreshold", type: "uint16", internalType: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addEmergencyLiquidator",
    inputs: [{ name: "liquidator", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addressProvider",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allowAdapter",
    inputs: [{ name: "adapter", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "allowToken",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "allowedAdapters",
    inputs: [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creditFacade",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creditManager",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "emergencyLiquidators",
    inputs: [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "forbidAdapter",
    inputs: [{ name: "adapter", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "forbidBorrowing",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "forbidToken",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "makeTokenQuoted",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "rampLiquidationThreshold",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      {
        name: "liquidationThresholdFinal",
        type: "uint16",
        internalType: "uint16",
      },
      { name: "rampStart", type: "uint40", internalType: "uint40" },
      { name: "rampDuration", type: "uint24", internalType: "uint24" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "removeEmergencyLiquidator",
    inputs: [{ name: "liquidator", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "resetCumulativeLoss",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setBotList",
    inputs: [{ name: "newVersion", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCreditFacade",
    inputs: [
      { name: "newCreditFacade", type: "address", internalType: "address" },
      { name: "migrateParams", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setExpirationDate",
    inputs: [
      { name: "newExpirationDate", type: "uint40", internalType: "uint40" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setFees",
    inputs: [
      { name: "feeInterest", type: "uint16", internalType: "uint16" },
      { name: "feeLiquidation", type: "uint16", internalType: "uint16" },
      { name: "liquidationPremium", type: "uint16", internalType: "uint16" },
      { name: "feeLiquidationExpired", type: "uint16", internalType: "uint16" },
      {
        name: "liquidationPremiumExpired",
        type: "uint16",
        internalType: "uint16",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setLiquidationThreshold",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "liquidationThreshold", type: "uint16", internalType: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMaxCumulativeLoss",
    inputs: [
      {
        name: "newMaxCumulativeLoss",
        type: "uint128",
        internalType: "uint128",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMaxDebtLimit",
    inputs: [{ name: "newMaxDebt", type: "uint128", internalType: "uint128" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMaxDebtPerBlockMultiplier",
    inputs: [
      {
        name: "newMaxDebtLimitPerBlockMultiplier",
        type: "uint8",
        internalType: "uint8",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMaxEnabledTokens",
    inputs: [
      { name: "newMaxEnabledTokens", type: "uint8", internalType: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMinDebtLimit",
    inputs: [{ name: "newMinDebt", type: "uint128", internalType: "uint128" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPriceOracle",
    inputs: [{ name: "newVersion", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "underlying",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "upgradeCreditConfigurator",
    inputs: [
      {
        name: "newCreditConfigurator",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "version",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AddCollateralToken",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AddEmergencyLiquidator",
    inputs: [
      {
        name: "liquidator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AllowAdapter",
    inputs: [
      {
        name: "targetContract",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "adapter",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AllowToken",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CreditConfiguratorUpgraded",
    inputs: [
      {
        name: "creditConfigurator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ForbidAdapter",
    inputs: [
      {
        name: "targetContract",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "adapter",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "ForbidToken",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "QuoteToken",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "RemoveEmergencyLiquidator",
    inputs: [
      {
        name: "liquidator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  { type: "event", name: "ResetCumulativeLoss", inputs: [], anonymous: false },
  {
    type: "event",
    name: "ScheduleTokenLiquidationThresholdRamp",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "liquidationThresholdInitial",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
      {
        name: "liquidationThresholdFinal",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
      {
        name: "timestampRampStart",
        type: "uint40",
        indexed: false,
        internalType: "uint40",
      },
      {
        name: "timestampRampEnd",
        type: "uint40",
        indexed: false,
        internalType: "uint40",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetBorrowingLimits",
    inputs: [
      {
        name: "minDebt",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "maxDebt",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetBotList",
    inputs: [
      {
        name: "botList",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetCreditFacade",
    inputs: [
      {
        name: "creditFacade",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetExpirationDate",
    inputs: [
      {
        name: "expirationDate",
        type: "uint40",
        indexed: false,
        internalType: "uint40",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetMaxCumulativeLoss",
    inputs: [
      {
        name: "maxCumulativeLoss",
        type: "uint128",
        indexed: false,
        internalType: "uint128",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetMaxDebtPerBlockMultiplier",
    inputs: [
      {
        name: "maxDebtPerBlockMultiplier",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetMaxEnabledTokens",
    inputs: [
      {
        name: "maxEnabledTokens",
        type: "uint8",
        indexed: false,
        internalType: "uint8",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetPriceOracle",
    inputs: [
      {
        name: "priceOracle",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetTokenLiquidationThreshold",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "liquidationThreshold",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UpdateFees",
    inputs: [
      {
        name: "feeInterest",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
      {
        name: "feeLiquidation",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
      {
        name: "liquidationPremium",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
      {
        name: "feeLiquidationExpired",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
      {
        name: "liquidationPremiumExpired",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
    ],
    anonymous: false,
  },
] as const;

export const iCreditFacadeV300Abi = [
  {
    type: "function",
    name: "botList",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "botMulticall",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      {
        name: "calls",
        type: "tuple[]",
        internalType: "struct MultiCall[]",
        components: [
          { name: "target", type: "address", internalType: "address" },
          { name: "callData", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "canLiquidateWhilePaused",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "closeCreditAccount",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      {
        name: "calls",
        type: "tuple[]",
        internalType: "struct MultiCall[]",
        components: [
          { name: "target", type: "address", internalType: "address" },
          { name: "callData", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "creditManager",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "debtLimits",
    inputs: [],
    outputs: [
      { name: "minDebt", type: "uint128", internalType: "uint128" },
      { name: "maxDebt", type: "uint128", internalType: "uint128" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "degenNFT",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "expirable",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "expirationDate",
    inputs: [],
    outputs: [{ name: "", type: "uint40", internalType: "uint40" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "forbiddenTokenMask",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "liquidateCreditAccount",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      { name: "to", type: "address", internalType: "address" },
      {
        name: "calls",
        type: "tuple[]",
        internalType: "struct MultiCall[]",
        components: [
          { name: "target", type: "address", internalType: "address" },
          { name: "callData", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "lossParams",
    inputs: [],
    outputs: [
      {
        name: "currentCumulativeLoss",
        type: "uint128",
        internalType: "uint128",
      },
      { name: "maxCumulativeLoss", type: "uint128", internalType: "uint128" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxDebtPerBlockMultiplier",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxQuotaMultiplier",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "multicall",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      {
        name: "calls",
        type: "tuple[]",
        internalType: "struct MultiCall[]",
        components: [
          { name: "target", type: "address", internalType: "address" },
          { name: "callData", type: "bytes", internalType: "bytes" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "openCreditAccount",
    inputs: [
      { name: "onBehalfOf", type: "address", internalType: "address" },
      {
        name: "calls",
        type: "tuple[]",
        internalType: "struct MultiCall[]",
        components: [
          { name: "target", type: "address", internalType: "address" },
          { name: "callData", type: "bytes", internalType: "bytes" },
        ],
      },
      { name: "referralCode", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
    ],
    stateMutability: "payable",
  },
  {
    type: "function",
    name: "setBotList",
    inputs: [{ name: "newBotList", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setBotPermissions",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      { name: "bot", type: "address", internalType: "address" },
      { name: "permissions", type: "uint192", internalType: "uint192" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCumulativeLossParams",
    inputs: [
      {
        name: "newMaxCumulativeLoss",
        type: "uint128",
        internalType: "uint128",
      },
      { name: "resetCumulativeLoss", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setDebtLimits",
    inputs: [
      { name: "newMinDebt", type: "uint128", internalType: "uint128" },
      { name: "newMaxDebt", type: "uint128", internalType: "uint128" },
      {
        name: "newMaxDebtPerBlockMultiplier",
        type: "uint8",
        internalType: "uint8",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setEmergencyLiquidator",
    inputs: [
      { name: "liquidator", type: "address", internalType: "address" },
      {
        name: "allowance",
        type: "uint8",
        internalType: "enum AllowanceAction",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setExpirationDate",
    inputs: [
      { name: "newExpirationDate", type: "uint40", internalType: "uint40" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setTokenAllowance",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      {
        name: "allowance",
        type: "uint8",
        internalType: "enum AllowanceAction",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "version",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "weth",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AddCollateral",
    inputs: [
      {
        name: "creditAccount",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "CloseCreditAccount",
    inputs: [
      {
        name: "creditAccount",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "borrower",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "DecreaseDebt",
    inputs: [
      {
        name: "creditAccount",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Execute",
    inputs: [
      {
        name: "creditAccount",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "targetContract",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  { type: "event", name: "FinishMultiCall", inputs: [], anonymous: false },
  {
    type: "event",
    name: "IncreaseDebt",
    inputs: [
      {
        name: "creditAccount",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "LiquidateCreditAccount",
    inputs: [
      {
        name: "creditAccount",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "liquidator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "to", type: "address", indexed: false, internalType: "address" },
      {
        name: "remainingFunds",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "OpenCreditAccount",
    inputs: [
      {
        name: "creditAccount",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "onBehalfOf",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "caller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "referralCode",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "StartMultiCall",
    inputs: [
      {
        name: "creditAccount",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "caller",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "WithdrawCollateral",
    inputs: [
      {
        name: "creditAccount",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      { name: "to", type: "address", indexed: false, internalType: "address" },
    ],
    anonymous: false,
  },
] as const;

export const iCreditFacadeV300MulticallAbi = [
  {
    type: "function",
    name: "addCollateral",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addCollateralWithPermit",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "deadline", type: "uint256", internalType: "uint256" },
      { name: "v", type: "uint8", internalType: "uint8" },
      { name: "r", type: "bytes32", internalType: "bytes32" },
      { name: "s", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "compareBalances",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "decreaseDebt",
    inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "disableToken",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "enableToken",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "increaseDebt",
    inputs: [{ name: "amount", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "onDemandPriceUpdate",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "reserve", type: "bool", internalType: "bool" },
      { name: "data", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "revokeAdapterAllowances",
    inputs: [
      {
        name: "revocations",
        type: "tuple[]",
        internalType: "struct RevocationPair[]",
        components: [
          { name: "spender", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "address" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setFullCheckParams",
    inputs: [
      { name: "collateralHints", type: "uint256[]", internalType: "uint256[]" },
      { name: "minHealthFactor", type: "uint16", internalType: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "storeExpectedBalances",
    inputs: [
      {
        name: "balanceDeltas",
        type: "tuple[]",
        internalType: "struct BalanceDelta[]",
        components: [
          { name: "token", type: "address", internalType: "address" },
          { name: "amount", type: "int256", internalType: "int256" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateQuota",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "quotaChange", type: "int96", internalType: "int96" },
      { name: "minQuota", type: "uint96", internalType: "uint96" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawCollateral",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "to", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
] as const;

export const iCreditManagerV300Abi = [
  {
    type: "function",
    name: "accountFactory",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "adapterToContract",
    inputs: [{ name: "adapter", type: "address", internalType: "address" }],
    outputs: [
      { name: "targetContract", type: "address", internalType: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "addCollateral",
    inputs: [
      { name: "payer", type: "address", internalType: "address" },
      { name: "creditAccount", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [
      { name: "tokensToEnable", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addToken",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addressProvider",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approveCreditAccount",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "approveToken",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "address" },
      { name: "spender", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "calcDebtAndCollateral",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      { name: "task", type: "uint8", internalType: "enum CollateralCalcTask" },
    ],
    outputs: [
      {
        name: "cdd",
        type: "tuple",
        internalType: "struct CollateralDebtData",
        components: [
          { name: "debt", type: "uint256", internalType: "uint256" },
          {
            name: "cumulativeIndexNow",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "cumulativeIndexLastUpdate",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "cumulativeQuotaInterest",
            type: "uint128",
            internalType: "uint128",
          },
          { name: "accruedInterest", type: "uint256", internalType: "uint256" },
          { name: "accruedFees", type: "uint256", internalType: "uint256" },
          { name: "totalDebtUSD", type: "uint256", internalType: "uint256" },
          { name: "totalValue", type: "uint256", internalType: "uint256" },
          { name: "totalValueUSD", type: "uint256", internalType: "uint256" },
          { name: "twvUSD", type: "uint256", internalType: "uint256" },
          {
            name: "enabledTokensMask",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "quotedTokensMask",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "quotedTokens",
            type: "address[]",
            internalType: "address[]",
          },
          {
            name: "_poolQuotaKeeper",
            type: "address",
            internalType: "address",
          },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "closeCreditAccount",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "collateralTokenByMask",
    inputs: [{ name: "tokenMask", type: "uint256", internalType: "uint256" }],
    outputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "liquidationThreshold", type: "uint16", internalType: "uint16" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "collateralTokensCount",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "contractToAdapter",
    inputs: [
      { name: "targetContract", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "adapter", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creditAccountInfo",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
    ],
    outputs: [
      { name: "debt", type: "uint256", internalType: "uint256" },
      {
        name: "cumulativeIndexLastUpdate",
        type: "uint256",
        internalType: "uint256",
      },
      {
        name: "cumulativeQuotaInterest",
        type: "uint128",
        internalType: "uint128",
      },
      { name: "quotaFees", type: "uint128", internalType: "uint128" },
      { name: "enabledTokensMask", type: "uint256", internalType: "uint256" },
      { name: "flags", type: "uint16", internalType: "uint16" },
      { name: "lastDebtUpdate", type: "uint64", internalType: "uint64" },
      { name: "borrower", type: "address", internalType: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creditAccounts",
    inputs: [
      { name: "offset", type: "uint256", internalType: "uint256" },
      { name: "limit", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creditAccounts",
    inputs: [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creditAccountsLen",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creditConfigurator",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creditFacade",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "enabledTokensMaskOf",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "execute",
    inputs: [{ name: "data", type: "bytes", internalType: "bytes" }],
    outputs: [{ name: "result", type: "bytes", internalType: "bytes" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "externalCall",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      { name: "target", type: "address", internalType: "address" },
      { name: "callData", type: "bytes", internalType: "bytes" },
    ],
    outputs: [{ name: "result", type: "bytes", internalType: "bytes" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "fees",
    inputs: [],
    outputs: [
      { name: "feeInterest", type: "uint16", internalType: "uint16" },
      { name: "feeLiquidation", type: "uint16", internalType: "uint16" },
      { name: "liquidationDiscount", type: "uint16", internalType: "uint16" },
      { name: "feeLiquidationExpired", type: "uint16", internalType: "uint16" },
      {
        name: "liquidationDiscountExpired",
        type: "uint16",
        internalType: "uint16",
      },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "flagsOf",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "fullCollateralCheck",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      { name: "enabledTokensMask", type: "uint256", internalType: "uint256" },
      { name: "collateralHints", type: "uint256[]", internalType: "uint256[]" },
      { name: "minHealthFactor", type: "uint16", internalType: "uint16" },
      { name: "useSafePrices", type: "bool", internalType: "bool" },
    ],
    outputs: [
      {
        name: "enabledTokensMaskAfter",
        type: "uint256",
        internalType: "uint256",
      },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "getActiveCreditAccountOrRevert",
    inputs: [],
    outputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getBorrowerOrRevert",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "borrower", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTokenByMask",
    inputs: [{ name: "tokenMask", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "token", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTokenMaskOrRevert",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [{ name: "tokenMask", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isLiquidatable",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      { name: "minHealthFactor", type: "uint16", internalType: "uint16" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "liquidateCreditAccount",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      {
        name: "collateralDebtData",
        type: "tuple",
        internalType: "struct CollateralDebtData",
        components: [
          { name: "debt", type: "uint256", internalType: "uint256" },
          {
            name: "cumulativeIndexNow",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "cumulativeIndexLastUpdate",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "cumulativeQuotaInterest",
            type: "uint128",
            internalType: "uint128",
          },
          { name: "accruedInterest", type: "uint256", internalType: "uint256" },
          { name: "accruedFees", type: "uint256", internalType: "uint256" },
          { name: "totalDebtUSD", type: "uint256", internalType: "uint256" },
          { name: "totalValue", type: "uint256", internalType: "uint256" },
          { name: "totalValueUSD", type: "uint256", internalType: "uint256" },
          { name: "twvUSD", type: "uint256", internalType: "uint256" },
          {
            name: "enabledTokensMask",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "quotedTokensMask",
            type: "uint256",
            internalType: "uint256",
          },
          {
            name: "quotedTokens",
            type: "address[]",
            internalType: "address[]",
          },
          {
            name: "_poolQuotaKeeper",
            type: "address",
            internalType: "address",
          },
        ],
      },
      { name: "to", type: "address", internalType: "address" },
      { name: "isExpired", type: "bool", internalType: "bool" },
    ],
    outputs: [
      { name: "remainingFunds", type: "uint256", internalType: "uint256" },
      { name: "loss", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "liquidationThresholds",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [{ name: "lt", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "ltParams",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [
      { name: "ltInitial", type: "uint16", internalType: "uint16" },
      { name: "ltFinal", type: "uint16", internalType: "uint16" },
      { name: "timestampRampStart", type: "uint40", internalType: "uint40" },
      { name: "rampDuration", type: "uint24", internalType: "uint24" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "manageDebt",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "enabledTokensMask", type: "uint256", internalType: "uint256" },
      { name: "action", type: "uint8", internalType: "enum ManageDebtAction" },
    ],
    outputs: [
      { name: "newDebt", type: "uint256", internalType: "uint256" },
      { name: "tokensToEnable", type: "uint256", internalType: "uint256" },
      { name: "tokensToDisable", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "maxEnabledTokens",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "name",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "openCreditAccount",
    inputs: [{ name: "onBehalfOf", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "pool",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "poolQuotaKeeper",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "priceOracle",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "quotedTokensMask",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "revokeAdapterAllowances",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      {
        name: "revocations",
        type: "tuple[]",
        internalType: "struct RevocationPair[]",
        components: [
          { name: "spender", type: "address", internalType: "address" },
          { name: "token", type: "address", internalType: "address" },
        ],
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setActiveCreditAccount",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCollateralTokenData",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "ltInitial", type: "uint16", internalType: "uint16" },
      { name: "ltFinal", type: "uint16", internalType: "uint16" },
      { name: "timestampRampStart", type: "uint40", internalType: "uint40" },
      { name: "rampDuration", type: "uint24", internalType: "uint24" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setContractAllowance",
    inputs: [
      { name: "adapter", type: "address", internalType: "address" },
      { name: "targetContract", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCreditConfigurator",
    inputs: [
      { name: "creditConfigurator", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCreditFacade",
    inputs: [
      { name: "creditFacade", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setFees",
    inputs: [
      { name: "feeInterest", type: "uint16", internalType: "uint16" },
      { name: "feeLiquidation", type: "uint16", internalType: "uint16" },
      { name: "liquidationDiscount", type: "uint16", internalType: "uint16" },
      { name: "feeLiquidationExpired", type: "uint16", internalType: "uint16" },
      {
        name: "liquidationDiscountExpired",
        type: "uint16",
        internalType: "uint16",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setFlagFor",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      { name: "flag", type: "uint16", internalType: "uint16" },
      { name: "value", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setMaxEnabledTokens",
    inputs: [
      { name: "maxEnabledTokens", type: "uint8", internalType: "uint8" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPriceOracle",
    inputs: [{ name: "priceOracle", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setQuotedMask",
    inputs: [
      { name: "quotedTokensMask", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "underlying",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "updateQuota",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "address" },
      { name: "quotaChange", type: "int96", internalType: "int96" },
      { name: "minQuota", type: "uint96", internalType: "uint96" },
      { name: "maxQuota", type: "uint96", internalType: "uint96" },
    ],
    outputs: [
      { name: "tokensToEnable", type: "uint256", internalType: "uint256" },
      { name: "tokensToDisable", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "version",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "withdrawCollateral",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "to", type: "address", internalType: "address" },
    ],
    outputs: [
      { name: "tokensToDisable", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "event",
    name: "SetCreditConfigurator",
    inputs: [
      {
        name: "newConfigurator",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
] as const;

export const iGaugeV300Abi = [
  {
    type: "function",
    name: "addQuotaToken",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "minRate", type: "uint16", internalType: "uint16" },
      { name: "maxRate", type: "uint16", internalType: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "changeQuotaMaxRate",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "maxRate", type: "uint16", internalType: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "changeQuotaMinRate",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "minRate", type: "uint16", internalType: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "epochFrozen",
    inputs: [],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "epochLastUpdate",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getRates",
    inputs: [{ name: "tokens", type: "address[]", internalType: "address[]" }],
    outputs: [{ name: "rates", type: "uint16[]", internalType: "uint16[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isTokenAdded",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pool",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "quotaRateParams",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [
      { name: "minRate", type: "uint16", internalType: "uint16" },
      { name: "maxRate", type: "uint16", internalType: "uint16" },
      { name: "totalVotesLpSide", type: "uint96", internalType: "uint96" },
      { name: "totalVotesCaSide", type: "uint96", internalType: "uint96" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setFrozenEpoch",
    inputs: [{ name: "status", type: "bool", internalType: "bool" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "unvote",
    inputs: [
      { name: "user", type: "address", internalType: "address" },
      { name: "votes", type: "uint96", internalType: "uint96" },
      { name: "extraData", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateEpoch",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "userTokenVotes",
    inputs: [
      { name: "user", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "address" },
    ],
    outputs: [
      { name: "votesLpSide", type: "uint96", internalType: "uint96" },
      { name: "votesCaSide", type: "uint96", internalType: "uint96" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "version",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "vote",
    inputs: [
      { name: "user", type: "address", internalType: "address" },
      { name: "votes", type: "uint96", internalType: "uint96" },
      { name: "extraData", type: "bytes", internalType: "bytes" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "voter",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AddQuotaToken",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "minRate",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
      {
        name: "maxRate",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetFrozenEpoch",
    inputs: [
      { name: "status", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetQuotaTokenParams",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "minRate",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
      {
        name: "maxRate",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Unvote",
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "votes", type: "uint96", indexed: false, internalType: "uint96" },
      { name: "lpSide", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UpdateEpoch",
    inputs: [
      {
        name: "epochNow",
        type: "uint16",
        indexed: false,
        internalType: "uint16",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Vote",
    inputs: [
      { name: "user", type: "address", indexed: true, internalType: "address" },
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "votes", type: "uint96", indexed: false, internalType: "uint96" },
      { name: "lpSide", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
] as const;

export const iPoolQuotaKeeperV300Abi = [
  {
    type: "function",
    name: "accrueQuotaInterest",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      { name: "tokens", type: "address[]", internalType: "address[]" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addCreditManager",
    inputs: [
      { name: "_creditManager", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "addQuotaToken",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "creditManagers",
    inputs: [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "cumulativeIndex",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint192", internalType: "uint192" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "gauge",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getQuota",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "address" },
    ],
    outputs: [
      { name: "quota", type: "uint96", internalType: "uint96" },
      { name: "cumulativeIndexLU", type: "uint192", internalType: "uint192" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getQuotaAndOutstandingInterest",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "address" },
    ],
    outputs: [
      { name: "quoted", type: "uint96", internalType: "uint96" },
      { name: "outstandingInterest", type: "uint128", internalType: "uint128" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getQuotaRate",
    inputs: [{ name: "", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getTokenQuotaParams",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [
      { name: "rate", type: "uint16", internalType: "uint16" },
      { name: "cumulativeIndexLU", type: "uint192", internalType: "uint192" },
      { name: "quotaIncreaseFee", type: "uint16", internalType: "uint16" },
      { name: "totalQuoted", type: "uint96", internalType: "uint96" },
      { name: "limit", type: "uint96", internalType: "uint96" },
      { name: "isActive", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "isQuotedToken",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastQuotaRateUpdate",
    inputs: [],
    outputs: [{ name: "", type: "uint40", internalType: "uint40" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "pool",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "poolQuotaRevenue",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "quotedTokens",
    inputs: [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "removeQuotas",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      { name: "tokens", type: "address[]", internalType: "address[]" },
      { name: "setLimitsToZero", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setGauge",
    inputs: [{ name: "_gauge", type: "address", internalType: "address" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setTokenLimit",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "limit", type: "uint96", internalType: "uint96" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setTokenQuotaIncreaseFee",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "fee", type: "uint16", internalType: "uint16" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "underlying",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "updateQuota",
    inputs: [
      { name: "creditAccount", type: "address", internalType: "address" },
      { name: "token", type: "address", internalType: "address" },
      { name: "requestedChange", type: "int96", internalType: "int96" },
      { name: "minQuota", type: "uint96", internalType: "uint96" },
      { name: "maxQuota", type: "uint96", internalType: "uint96" },
    ],
    outputs: [
      {
        name: "caQuotaInterestChange",
        type: "uint128",
        internalType: "uint128",
      },
      { name: "fees", type: "uint128", internalType: "uint128" },
      { name: "enableToken", type: "bool", internalType: "bool" },
      { name: "disableToken", type: "bool", internalType: "bool" },
    ],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "updateRates",
    inputs: [],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "version",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AddCreditManager",
    inputs: [
      {
        name: "creditManager",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "AddQuotaToken",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetGauge",
    inputs: [
      {
        name: "newGauge",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetQuotaIncreaseFee",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "fee", type: "uint16", indexed: false, internalType: "uint16" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetTokenLimit",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "limit", type: "uint96", indexed: false, internalType: "uint96" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UpdateQuota",
    inputs: [
      {
        name: "creditAccount",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "quotaChange",
        type: "int96",
        indexed: false,
        internalType: "int96",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "UpdateTokenQuotaRate",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "rate", type: "uint16", indexed: false, internalType: "uint16" },
    ],
    anonymous: false,
  },
] as const;

export const iPoolV300Abi = [
  {
    type: "function",
    name: "DOMAIN_SEPARATOR",
    inputs: [],
    outputs: [{ name: "", type: "bytes32", internalType: "bytes32" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "addressProvider",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "allowance",
    inputs: [
      { name: "owner", type: "address", internalType: "address" },
      { name: "spender", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "approve",
    inputs: [
      { name: "spender", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "asset",
    inputs: [],
    outputs: [
      { name: "assetTokenAddress", type: "address", internalType: "address" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "availableLiquidity",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "balanceOf",
    inputs: [{ name: "account", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "baseInterestIndex",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "baseInterestIndexLU",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "baseInterestRate",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "convertToAssets",
    inputs: [{ name: "shares", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "assets", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "convertToShares",
    inputs: [{ name: "assets", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "shares", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creditManagerBorrowable",
    inputs: [
      { name: "creditManager", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "borrowable", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creditManagerBorrowed",
    inputs: [
      { name: "creditManager", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creditManagerDebtLimit",
    inputs: [
      { name: "creditManager", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "creditManagers",
    inputs: [],
    outputs: [{ name: "", type: "address[]", internalType: "address[]" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "decimals",
    inputs: [],
    outputs: [{ name: "", type: "uint8", internalType: "uint8" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "deposit",
    inputs: [
      { name: "assets", type: "uint256", internalType: "uint256" },
      { name: "receiver", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "shares", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "depositWithReferral",
    inputs: [
      { name: "assets", type: "uint256", internalType: "uint256" },
      { name: "receiver", type: "address", internalType: "address" },
      { name: "referralCode", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "shares", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "expectedLiquidity",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "expectedLiquidityLU",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "interestRateModel",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastBaseInterestUpdate",
    inputs: [],
    outputs: [{ name: "", type: "uint40", internalType: "uint40" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lastQuotaRevenueUpdate",
    inputs: [],
    outputs: [{ name: "", type: "uint40", internalType: "uint40" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "lendCreditAccount",
    inputs: [
      { name: "borrowedAmount", type: "uint256", internalType: "uint256" },
      { name: "creditAccount", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "maxDeposit",
    inputs: [{ name: "receiver", type: "address", internalType: "address" }],
    outputs: [{ name: "maxAssets", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxMint",
    inputs: [{ name: "receiver", type: "address", internalType: "address" }],
    outputs: [{ name: "maxShares", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxRedeem",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
    outputs: [{ name: "maxShares", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "maxWithdraw",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
    outputs: [{ name: "maxAssets", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "mint",
    inputs: [
      { name: "shares", type: "uint256", internalType: "uint256" },
      { name: "receiver", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "assets", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "mintWithReferral",
    inputs: [
      { name: "shares", type: "uint256", internalType: "uint256" },
      { name: "receiver", type: "address", internalType: "address" },
      { name: "referralCode", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "assets", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "name",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "nonces",
    inputs: [{ name: "owner", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "permit",
    inputs: [
      { name: "owner", type: "address", internalType: "address" },
      { name: "spender", type: "address", internalType: "address" },
      { name: "value", type: "uint256", internalType: "uint256" },
      { name: "deadline", type: "uint256", internalType: "uint256" },
      { name: "v", type: "uint8", internalType: "uint8" },
      { name: "r", type: "bytes32", internalType: "bytes32" },
      { name: "s", type: "bytes32", internalType: "bytes32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "poolQuotaKeeper",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "previewDeposit",
    inputs: [{ name: "assets", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "shares", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "previewMint",
    inputs: [{ name: "shares", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "assets", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "previewRedeem",
    inputs: [{ name: "shares", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "assets", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "previewWithdraw",
    inputs: [{ name: "assets", type: "uint256", internalType: "uint256" }],
    outputs: [{ name: "shares", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "quotaRevenue",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "redeem",
    inputs: [
      { name: "shares", type: "uint256", internalType: "uint256" },
      { name: "receiver", type: "address", internalType: "address" },
      { name: "owner", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "assets", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "repayCreditAccount",
    inputs: [
      { name: "repaidAmount", type: "uint256", internalType: "uint256" },
      { name: "profit", type: "uint256", internalType: "uint256" },
      { name: "loss", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setCreditManagerDebtLimit",
    inputs: [
      { name: "creditManager", type: "address", internalType: "address" },
      { name: "newLimit", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setInterestRateModel",
    inputs: [
      {
        name: "newInterestRateModel",
        type: "address",
        internalType: "address",
      },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setPoolQuotaKeeper",
    inputs: [
      { name: "newPoolQuotaKeeper", type: "address", internalType: "address" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setQuotaRevenue",
    inputs: [
      { name: "newQuotaRevenue", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setTotalDebtLimit",
    inputs: [{ name: "newLimit", type: "uint256", internalType: "uint256" }],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setWithdrawFee",
    inputs: [
      { name: "newWithdrawFee", type: "uint256", internalType: "uint256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "supplyRate",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "symbol",
    inputs: [],
    outputs: [{ name: "", type: "string", internalType: "string" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalAssets",
    inputs: [],
    outputs: [
      { name: "totalManagedAssets", type: "uint256", internalType: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalBorrowed",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalDebtLimit",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "totalSupply",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "transfer",
    inputs: [
      { name: "to", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "transferFrom",
    inputs: [
      { name: "from", type: "address", internalType: "address" },
      { name: "to", type: "address", internalType: "address" },
      { name: "amount", type: "uint256", internalType: "uint256" },
    ],
    outputs: [{ name: "", type: "bool", internalType: "bool" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "treasury",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "underlyingToken",
    inputs: [],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "updateQuotaRevenue",
    inputs: [
      { name: "quotaRevenueDelta", type: "int256", internalType: "int256" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "version",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "withdraw",
    inputs: [
      { name: "assets", type: "uint256", internalType: "uint256" },
      { name: "receiver", type: "address", internalType: "address" },
      { name: "owner", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "shares", type: "uint256", internalType: "uint256" }],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "withdrawFee",
    inputs: [],
    outputs: [{ name: "", type: "uint16", internalType: "uint16" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "AddCreditManager",
    inputs: [
      {
        name: "creditManager",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Approval",
    inputs: [
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "spender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "value",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Borrow",
    inputs: [
      {
        name: "creditManager",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "creditAccount",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Deposit",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "assets",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "shares",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "IncurUncoveredLoss",
    inputs: [
      {
        name: "creditManager",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "loss",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Refer",
    inputs: [
      {
        name: "onBehalfOf",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "referralCode",
        type: "uint256",
        indexed: true,
        internalType: "uint256",
      },
      {
        name: "amount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Repay",
    inputs: [
      {
        name: "creditManager",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "borrowedAmount",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "profit",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "loss",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetCreditManagerDebtLimit",
    inputs: [
      {
        name: "creditManager",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "newLimit",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetInterestRateModel",
    inputs: [
      {
        name: "newInterestRateModel",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetPoolQuotaKeeper",
    inputs: [
      {
        name: "newPoolQuotaKeeper",
        type: "address",
        indexed: true,
        internalType: "address",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetTotalDebtLimit",
    inputs: [
      {
        name: "limit",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetWithdrawFee",
    inputs: [
      { name: "fee", type: "uint256", indexed: false, internalType: "uint256" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Transfer",
    inputs: [
      { name: "from", type: "address", indexed: true, internalType: "address" },
      { name: "to", type: "address", indexed: true, internalType: "address" },
      {
        name: "value",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "Withdraw",
    inputs: [
      {
        name: "sender",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "receiver",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "owner",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "assets",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
      {
        name: "shares",
        type: "uint256",
        indexed: false,
        internalType: "uint256",
      },
    ],
    anonymous: false,
  },
] as const;

export const iPriceOracleV300Abi = [
  {
    type: "function",
    name: "convert",
    inputs: [
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "tokenFrom", type: "address", internalType: "address" },
      { name: "tokenTo", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "convertFromUSD",
    inputs: [
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "token", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "convertToUSD",
    inputs: [
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "token", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPrice",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPriceRaw",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "reserve", type: "bool", internalType: "bool" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "getPriceSafe",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "priceFeedParams",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [
      { name: "priceFeed", type: "address", internalType: "address" },
      { name: "stalenessPeriod", type: "uint32", internalType: "uint32" },
      { name: "skipCheck", type: "bool", internalType: "bool" },
      { name: "decimals", type: "uint8", internalType: "uint8" },
      { name: "trusted", type: "bool", internalType: "bool" },
    ],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "priceFeeds",
    inputs: [{ name: "token", type: "address", internalType: "address" }],
    outputs: [{ name: "priceFeed", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "priceFeedsRaw",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "reserve", type: "bool", internalType: "bool" },
    ],
    outputs: [{ name: "", type: "address", internalType: "address" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "safeConvertToUSD",
    inputs: [
      { name: "amount", type: "uint256", internalType: "uint256" },
      { name: "token", type: "address", internalType: "address" },
    ],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "function",
    name: "setPriceFeed",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "priceFeed", type: "address", internalType: "address" },
      { name: "stalenessPeriod", type: "uint32", internalType: "uint32" },
      { name: "trusted", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setReservePriceFeed",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "priceFeed", type: "address", internalType: "address" },
      { name: "stalenessPeriod", type: "uint32", internalType: "uint32" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "setReservePriceFeedStatus",
    inputs: [
      { name: "token", type: "address", internalType: "address" },
      { name: "active", type: "bool", internalType: "bool" },
    ],
    outputs: [],
    stateMutability: "nonpayable",
  },
  {
    type: "function",
    name: "version",
    inputs: [],
    outputs: [{ name: "", type: "uint256", internalType: "uint256" }],
    stateMutability: "view",
  },
  {
    type: "event",
    name: "SetPriceFeed",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "priceFeed",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "stalenessPeriod",
        type: "uint32",
        indexed: false,
        internalType: "uint32",
      },
      { name: "skipCheck", type: "bool", indexed: false, internalType: "bool" },
      { name: "trusted", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetReservePriceFeed",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "priceFeed",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      {
        name: "stalenessPeriod",
        type: "uint32",
        indexed: false,
        internalType: "uint32",
      },
      { name: "skipCheck", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
  {
    type: "event",
    name: "SetReservePriceFeedStatus",
    inputs: [
      {
        name: "token",
        type: "address",
        indexed: true,
        internalType: "address",
      },
      { name: "active", type: "bool", indexed: false, internalType: "bool" },
    ],
    anonymous: false,
  },
] as const;
