name: Release

on:
  push:
    branches:
      - "master"
      - "next"
      - "v4"
      - "v4-abi"

env:
  HUSKY: 0
  CI: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Latest Corepack
        run: |
          echo "Before: corepack version => $(corepack --version || echo 'not installed')"
          npm install -g corepack@latest
          echo "After : corepack version => $(corepack --version)"
          corepack enable

      - uses: actions/setup-node@v4
        with:
          cache: "yarn"
          node-version-file: ".nvmrc"

      - name: Configure access to private npm packages
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > .npmrc

      # No lint or prettier here since they were supposed to run on PR action
      - name: Build
        run: |
          yarn install --immutable
          yarn typecheck:ci
          yarn lint:ci
          yarn build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
