name: Release

on:
  push:
    branches:
      - "master"
      - "next"
      - "kyc"
      - "apy-plugin"
      - "*.x"

env:
  HUSKY: 0
  CI: true

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v6
        with:
          lfs: true

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@v1
        with:
          version: "v1.5.1"

      - uses: actions/setup-node@v6
        with:
          node-version-file: ".nvmrc"

      - uses: pnpm/action-setup@v5
        with:
          cache: true

      - name: Test and build
        env:
          RPC_URL: "https://eth-mainnet.g.alchemy.com/v2/${{ secrets.ALCHEMY_KEY_CI }}"
        run: |
          pnpm install --frozen-lockfile
          pnpm typecheck:ci
          pnpm test:all
          pnpm build

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
