/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as multiCallSol from "./MultiCall.sol";
export type { multiCallSol };
export type { ContractUpgrader } from "./ContractUpgrader";
export type { PathFinder } from "./PathFinder";
export type { PauseMulticall } from "./PauseMulticall";
