"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.NewBoosterMock__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var NewBoosterMock__factory_1 = require("./NewBoosterMock__factory");
Object.defineProperty(exports, "NewBoosterMock__factory", { enumerable: true, get: function () { return NewBoosterMock__factory_1.NewBoosterMock__factory; } });
