"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.CurveV1StEthAdapterTest__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var CurveV1StEthAdapterTest__factory_1 = require("./CurveV1StEthAdapterTest__factory");
Object.defineProperty(exports, "CurveV1StEthAdapterTest__factory", { enumerable: true, get: function () { return CurveV1StEthAdapterTest__factory_1.CurveV1StEthAdapterTest__factory; } });
